import { sumCents } from './money.js';

const observation=(id,type,priority,text,trace,signature)=>({id,type,priority,text,trace,signature});
const currency=cents=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(cents/100);

export function normalizeWarning(input){return{code:input.code,severity:input.severity??'warning',year:input.year??null,date:input.date??(input.year?`${input.year}-12-31`:null),entityId:input.entityId??null,explanation:input.explanation??input.message??input.code,provenanceIds:structuredClone(input.provenanceIds??[]),trace:structuredClone(input.trace??{})};}

export function narrateYear(yearResult,previousResult=null,{maxObservations=4,previousSignatures=[]}={}){
  const candidates=[];
  for(const event of yearResult.events.filter(e=>e.result==='executed'))candidates.push(observation(`obs:event:${event.id}`,'majorRealizedEvent',1,event.reason,{eventId:event.id,entityId:event.target},`${event.type}:${event.target}`));
  for(const goal of yearResult.goals){const prev=previousResult?.goals.find(g=>g.goalId===goal.goalId);if(goal.status!==prev?.status&&['possible','comfortablyAffordable','delayed','executed','needsUserChoice'].includes(goal.status)){const blocker=goal.primaryBlocker?.explanation,cost=goal.targetPriceNominalCents??goal.requiredCents??0;candidates.push(observation(`obs:goal:${goal.decisionId??goal.goalId}:${goal.status}`,'goalTransition',2,goal.status==='delayed'?`${goal.name} remains delayed: ${blocker}`:`${goal.name} is ${goal.status}; its modeled requirement is ${currency(cost)}.`,{goalId:goal.goalId,decisionId:goal.decisionId,ruleId:goal.primaryBlocker?.ruleId},`goal:${goal.goalId}:${goal.status}`));}}
  const currentCareers=new Map(yearResult.careers.map(c=>[c.personId,`${c.type}:${c.role}`])),previousCareers=new Map((previousResult?.careers??[]).map(c=>[c.personId,`${c.type}:${c.role}`]));for(const [personId,role] of currentCareers)if(previousCareers.get(personId)!==role)candidates.push(observation(`obs:career:${yearResult.year}:${personId}`,'careerTransition',3,`${yearResult.careers.find(c=>c.personId===personId).role} is active this year for ${personId}.`,{entityId:personId,calculationId:`income:${yearResult.year}`},`career:${personId}:${role}`));
  for(const property of yearResult.properties){const previous=previousResult?.properties.find(p=>p.propertyId===property.propertyId);if(previous&&previous.status!==property.status)candidates.push(observation(`obs:property:${yearResult.year}:${property.propertyId}`,'propertyTransition',4,`${property.name} changed from ${previous.status} to ${property.status}.`,{entityId:property.propertyId,eventId:property.lastTransitionEventId??null},`property:${property.propertyId}:${property.status}`));}
  const components=yearResult.netWorthDecomposition.components.filter(c=>c.economicEffectCents!==0).sort((a,b)=>Math.abs(b.economicEffectCents)-Math.abs(a.economicEffectCents));if(components[0])candidates.push(observation(`obs:nw:${yearResult.year}`,'netWorthDriver',5,`${components[0].label??components[0].type} was the largest modeled net-worth driver at ${currency(components[0].economicEffectCents)}.`,{calculationId:`nw-decomposition:${yearResult.year}`,componentId:components[0].id??components[0].type},`nw:${components[0].type}`));
  const importantWarning=yearResult.warnings.find(w=>['error','blocking','warning'].includes(w.severity));if(importantWarning)candidates.push(observation(`obs:warning:${yearResult.year}:${importantWarning.code}`,'modelWarning',6,importantWarning.explanation,{warningCode:importantWarning.code,entityId:importantWarning.entityId},`warning:${importantWarning.code}`));
  if(yearResult.nextMajorMilestone)candidates.push(observation(`obs:upcoming:${yearResult.year}:${yearResult.nextMajorMilestone.timelineId}`,'upcomingMilestone',7,`Next major milestone: ${yearResult.nextMajorMilestone.description} (${yearResult.nextMajorMilestone.targetYear}).`,{timelineId:yearResult.nextMajorMilestone.timelineId},`upcoming:${yearResult.nextMajorMilestone.timelineId}`));
  const seen=new Set(),prior=new Set(previousSignatures),ranked=candidates.map(c=>({...c,rankScore:c.priority+(prior.has(c.signature)?20:0)})).sort((a,b)=>a.rankScore-b.rankScore||a.id.localeCompare(b.id)).filter(c=>{if(seen.has(c.signature))return false;seen.add(c.signature);return true;}).slice(0,maxObservations);
  return ranked.map(({rankScore,...item})=>item);
}

export function contributionVsGrowth({accountActivity={},propertyResults=[]}){
  const financial={openingBalanceCents:sumCents(Object.values(accountActivity).map(a=>a.openingBalanceCents)),employeeContributionsCents:sumCents(Object.values(accountActivity).map(a=>a.employeeContributionsCents??a.contributionsCents??0)),employerGovernmentContributionsCents:sumCents(Object.values(accountActivity).map(a=>a.employerGovernmentContributionsCents??0)),transfersInCents:sumCents(Object.values(accountActivity).map(a=>a.transfersInCents??0)),transfersOutCents:sumCents(Object.values(accountActivity).map(a=>a.transfersOutCents??0)),withdrawalsCents:sumCents(Object.values(accountActivity).map(a=>a.withdrawalsCents??0)),growthCents:sumCents(Object.values(accountActivity).map(a=>a.growthCents??0)),closingBalanceCents:sumCents(Object.values(accountActivity).map(a=>a.closingBalanceCents))};
  const property={openingEquityCents:sumCents(propertyResults.map(p=>(p.valuation?.openingValueCents??0)-(p.mortgage?.openingBalanceCents??0))),acquisitionTransferCents:sumCents(propertyResults.map(p=>p.acquisitionTransferCents??0)),appreciationCents:sumCents(propertyResults.map(p=>p.valuation?.appreciationCents??0)),mortgagePrincipalMovementCents:sumCents(propertyResults.map(p=>p.mortgage?.principalCents??0)),transactionCostsCents:sumCents(propertyResults.map(p=>p.transactionCostsCents??0)),operatingEconomicsCents:sumCents(propertyResults.map(p=>(p.rental?.netOperatingIncomeCents??0)-(p.mortgage?.interestCents??0))),closingEquityCents:sumCents(propertyResults.map(p=>p.equity?.equityCents??0))};return{financialAccounts:financial,property};
}
