import { validateModelDocument } from '../storage/schema.js';
import { buildPriceIndex } from './currency.js';
import { simulateHousehold } from './simulate-household.js';
import { simulatePropertyLifecycle } from './property-lifecycle.js';
import { evaluateLongTermHome, compareHomeStrategies, homeGoalToPropertyIntent } from './home-goal.js';
import { appendGoalStatus, allocateGoalFunding, goalTargetForYear } from './goals.js';
import { buildBalanceSheetSnapshot, buildCashFlowSnapshot, yearOverYearDeltas } from './snapshots.js';
import { buildTimeline, plannedVsRealizedDelta, nextMajorMilestone } from './timeline.js';
import { contributionVsGrowth, narrateYear, normalizeWarning } from './explainability.js';
import { WITHIN_YEAR_ORDER, MONTHLY_SUBPERIOD_RULES, orderEvents } from './event-order.js';
import { reconcileCash, reconcileBalanceSheet } from './reconciliation.js';
import { reconcileNetWorthChange } from './decomposition.js';
import { resolvePeople, ageOnDate, resolveEventDate } from './calendar.js';
import { sumCents } from './money.js';

const y=date=>Number(String(date).slice(0,4));
const isPropertyEvent=event=>event.type.startsWith('property.')||event.type==='asset.transfer.expected';
const mapObject=map=>Object.fromEntries(map);
const valuesByType=(accounts,balances,type)=>sumCents(accounts.filter(a=>a.type===type).map(a=>balances.get(a.id)??0));
const firstAccount=(accounts,type)=>accounts.find(a=>a.type===type);
const clone=value=>structuredClone(value);

function singleYearHouseholdModel(model,year,accounts,liabilities){
  return{...clone(model),household:{...clone(model.household),simulationStartYear:year,simulationEndYear:year},accounts:model.accounts.map(a=>({...clone(a),openingBalanceCents:accounts.get(a.id)??0})),liabilities:model.liabilities.filter(l=>l.type!=='mortgage').map(l=>({...clone(l),openingBalanceCents:liabilities.get(l.id)??0})),assets:[],properties:[],propertyIntents:[],goals:[],plannedEvents:model.plannedEvents.filter(e=>!isPropertyEvent(e)&&!e.type.startsWith('goal.'))};
}

function homeHousehold({model,year,accounts,properties,propertyLiabilities,householdYear,cashFlow}){
  const general=valuesByType(model.accounts,accounts,'generalCash'),dedicated=valuesByType(model.accounts,accounts,'goalCash'),taxable=valuesByType(model.accounts,accounts,'taxableInvestment'),retirement=valuesByType(model.accounts,accounts,'retirementInvestment'),reserve=valuesByType(model.accounts,accounts,'emergencyReserve');
  const retained=properties.filter(p=>p.status==='rental').map(p=>({propertyId:p.id,actualCents:p.propertyReserve?.balanceCents??0,requiredCents:p.metadata?.lastRequiredReserveCents??0})),primary=properties.find(p=>p.status==='primaryResidence');
  return{generalCashCents:general,dedicatedGoalCashCents:dedicated,taxableInvestmentsCents:taxable,retirementInvestmentsCents:retirement,emergencyReserveActualCents:reserve,emergencyReserveRequiredCents:householdYear.reserve.requiredCents,retainedPropertyReserves:retained,grossCashCompensationCents:householdYear.income.cashCompensationCents,afterTaxIncomeCents:householdYear.income.cashCompensationCents-householdYear.taxes.totalTaxCents,prePurchaseFreeCashFlowCents:cashFlow.freeCashFlowCents,currentAnnualHousingCostCents:sumCents(householdYear.spending.entries.filter(e=>e.category==='housing').map(e=>e.amountCents)),discretionaryCapacityCents:Math.max(0,householdYear.income.cashCompensationCents-householdYear.taxes.totalTaxCents-householdYear.spending.essentialCents),requiredDebtObligationsPayable:true,protectedRetirementViable:true,nearTermProtectedObligationsFunded:true,existingPrimaryResidenceId:primary?.id??null,propertyLiabilities:mapObject(propertyLiabilities)};
}

function updateAggregatedAccount(accounts,balances,type,value){const matches=accounts.filter(a=>a.type===type);if(!matches.length)return;const current=sumCents(matches.map(a=>balances.get(a.id)??0));let remaining=value;for(let i=0;i<matches.length;i++){const amount=i===matches.length-1?remaining:current?Math.round(value*(balances.get(matches[i].id)??0)/current):0;balances.set(matches[i].id,amount);remaining-=amount;}}
function propertyLiabilityDefinitions(properties,balances){return Object.keys(balances).map(id=>{const property=properties.find(p=>p.linkedLiabilityIds?.includes(id));return{id,name:`${property?.name??id} mortgage`,ownerId:property?.ownership?.length===1?property.ownership[0].ownerId:'household',type:'mortgage',linkedAssetId:property?.id,openingBalanceCents:balances[id]};});}

export function simulateFinancialLife(model,{data,taxTables}={}){
  const validation=validateModelDocument(model);if(!validation.valid)return{metadata:{valid:false},years:[],timeline:[],realizedEvents:[],decisions:[],goalResults:[],warnings:validation.warnings.map(normalizeWarning),errors:validation.errors,invariants:{passes:false}};
  const original=JSON.stringify(model),people=resolvePeople(model.people),start=model.household.simulationStartYear,end=model.household.simulationEndYear,index=buildPriceIndex(data.priceIndex,end),resolvedPlanned=orderEvents(model.plannedEvents.map(event=>({...clone(event),resolvedDate:resolveEventDate(event,people),effectiveDate:resolveEventDate(event,people)})));
  const accounts=new Map(model.accounts.map(a=>[a.id,a.openingBalanceCents])),nonPropertyLiabilities=new Map(model.liabilities.filter(l=>l.type!=='mortgage').map(l=>[l.id,l.openingBalanceCents])),propertyLiabilities=new Map(Object.entries(model.extensions?.integrated?.openingPropertyLiabilities??{})),goalStates=new Map(model.goals.map(g=>[g.id,clone(g)]));let properties=clone(model.properties??[]);
  const years=[],allEvents=[],allDecisions=[],allWarnings=[],goalResults=[];let previous=null;
  for(let year=start;year<=end;year++){
    const openingAccounts=mapObject(accounts),openingProperties=clone(properties),openingAllLiabilities={...mapObject(nonPropertyLiabilities),...mapObject(propertyLiabilities)},openingSnapshot=buildBalanceSheetSnapshot({accounts:model.accounts,accountBalances:openingAccounts,assets:model.assets,properties:openingProperties,liabilities:[...model.liabilities.filter(l=>l.type!=='mortgage'),...propertyLiabilityDefinitions(openingProperties,mapObject(propertyLiabilities))],liabilityBalances:openingAllLiabilities});
    const householdRun=simulateHousehold(singleYearHouseholdModel(model,year,accounts,nonPropertyLiabilities),{data,taxTables}),householdYear=householdRun.years[0];if(!householdYear)throw new Error(`Household simulation failed for ${year}.`);
    for(const [id,balance] of Object.entries(householdYear.closingBalances.accounts))accounts.set(id,balance);for(const [id,balance] of Object.entries(householdYear.closingBalances.liabilities))nonPropertyLiabilities.set(id,balance);
    const housingCents=sumCents(householdYear.spending.entries.filter(e=>e.category==='housing').map(e=>e.amountCents)),general=firstAccount(model.accounts,'generalCash');if(housingCents)accounts.set(general.id,(accounts.get(general.id)??0)+housingCents);
    const preliminaryCashFlow=buildCashFlowSnapshot({householdYear,propertyYear:null}),yearGoalResults=[],yearDecisions=[],goalIntents=[];
    for(const inputGoal of model.goals.filter(g=>g.type==='longTermHome'&&g.enabled!==false)){
      let goal=goalStates.get(inputGoal.id);if(goal.status==='executed'||goal.status==='completed'){if(goal.status==='executed')goal=appendGoalStatus(goal,{date:`${year}-01-01`,status:'completed',reason:'The goal-created property remains in the authoritative balance sheet.'});goalStates.set(goal.id,goal);yearGoalResults.push({goalId:goal.id,name:goal.name,status:goal.status,decisionId:null});continue;}
      const household=homeHousehold({model,year,accounts,properties,propertyLiabilities,householdYear,cashFlow:preliminaryCashFlow}),strategy=model.extensions?.integrated?.goalStrategiesByYear?.[year]?.baseline??{id:'keep',proposedSaleProperties:[]},alternatives=model.extensions?.integrated?.goalStrategiesByYear?.[year]?.alternatives;
      let decision=evaluateLongTermHome({goal,year,index,household,strategy});if(alternatives?.length){const comparison=compareHomeStrategies({goal,year,index,household,strategies:[strategy,...alternatives]});if(comparison.needsUserChoice){const warning=normalizeWarning({code:'UNRESOLVED_USER_CHOICE',severity:'warning',year,entityId:goal.id,explanation:comparison.explanation,trace:{decisionIds:comparison.evaluations.map(e=>e.id)}});allWarnings.push(warning);if(model.policies?.unresolvedChoice?.action!=='useBaseline')decision={...decision,status:'needsUserChoice',explanation:comparison.explanation};}}
      const evaluated={...decision,type:'homeAffordability',category:'goal',target:goal.id,date:`${year}-12-31`};yearDecisions.push(evaluated);allDecisions.push(evaluated);goal=appendGoalStatus(goal,{date:`${year}-12-31`,status:evaluated.status,reason:evaluated.explanation,decisionId:evaluated.id,blockerIds:evaluated.blockers.map(b=>b.ruleId),metrics:{targetPriceNominalCents:evaluated.targetPriceNominalCents,requiredUpfrontCents:evaluated.requiredUpfrontCents,housingBurden:evaluated.housingBurden.burden,postPurchaseFreeCashFlowCents:evaluated.postPurchaseFreeCashFlowCents}});
      if(evaluated.status==='comfortablyAffordable'&&model.extensions?.integrated?.autoExecuteGoals!==false){goalIntents.push(homeGoalToPropertyIntent({goal,decision:evaluated,year}));goal=appendGoalStatus(goal,{date:`${year}-12-31`,status:'executed',reason:'Comfort constraints passed; execution was delegated to the authoritative property lifecycle.',decisionId:evaluated.id,metrics:{propertyId:goal.home.resultingPropertyId}});}
      goalStates.set(goal.id,goal);yearGoalResults.push({goalId:goal.id,name:goal.name,status:goal.status,decisionId:evaluated.id,targetPriceRealCents:evaluated.targetPriceRealCents,targetPriceNominalCents:evaluated.targetPriceNominalCents,fundedAmountCents:evaluated.progress.dedicatedCents,permittedFundingCents:evaluated.permittedFundingAvailableCents,shortfallCents:evaluated.progress.remainingShortfallCents,possible:['possible','comfortablyAffordable','executed'].includes(goal.status),comfortable:['comfortablyAffordable','executed'].includes(goal.status),blockers:evaluated.blockers,primaryBlocker:evaluated.primaryBlocker,nextReevaluationYear:evaluated.nextReevaluationYear,fundingPlan:evaluated.fundingPlan});
    }
    const propertyEvents=resolvedPlanned.filter(e=>isPropertyEvent(e)&&y(e.resolvedDate)===year),activeIntents=model.propertyIntents.filter(i=>i.enabled!==false&&year>=i.desiredYear),propertyModel={schemaVersion:model.schemaVersion,modelVersion:model.modelVersion,baseCurrencyYear:model.baseCurrencyYear,properties,propertyIntents:[...activeIntents,...goalIntents],plannedEvents:propertyEvents,propertySimulation:{startYear:year,endYear:year,mortgageThroughYear:end,openingCashCents:valuesByType(model.accounts,accounts,'generalCash'),emergencyReserveActualCents:valuesByType(model.accounts,accounts,'emergencyReserve'),emergencyReserveRequiredByYear:{[year]:householdYear.reserve.requiredCents},openingTaxableInvestmentsCents:valuesByType(model.accounts,accounts,'taxableInvestment'),openingRetirementInvestmentsCents:valuesByType(model.accounts,accounts,'retirementInvestment'),openingLiabilities:mapObject(propertyLiabilities),annualHouseholdFreeCashFlowByYear:{[year]:0},feasibilityFreeCashFlowByYear:{[year]:preliminaryCashFlow.freeCashFlowCents},genericHousingSpendingByYear:{[year]:housingCents},appreciationRate:model.assumptions?.propertyAppreciationRate??.03,sellerTransactionCostRate:model.assumptions?.sellerTransactionCostRate??.06}};
    const propertyRun=simulatePropertyLifecycle(propertyModel),propertyYear=propertyRun.annualResults[0];properties=Object.values(propertyYear.closing.properties);propertyLiabilities.clear();for(const [id,balance] of Object.entries(propertyYear.closing.liabilities))propertyLiabilities.set(id,balance);updateAggregatedAccount(model.accounts,accounts,'generalCash',propertyYear.closing.cashCents);updateAggregatedAccount(model.accounts,accounts,'emergencyReserve',propertyYear.closing.emergencyReserveCents);updateAggregatedAccount(model.accounts,accounts,'taxableInvestment',propertyYear.closing.taxableInvestmentsCents);
    for(const result of propertyYear.propertyResults){const property=properties.find(p=>p.id===result.propertyId);if(property&&result.reserve)property.metadata={...property.metadata,lastRequiredReserveCents:result.reserve.requiredCents};}
    yearDecisions.push(...propertyYear.decisions.map(d=>({...d,id:`${d.id}:${d.status}`,type:d.action?'propertyConversion':'propertyPurchase',category:'property',date:d.actualDate??`${year}-12-31`})));allDecisions.push(...yearDecisions.filter((d,index,list)=>list.findIndex(other=>other.id===d.id)===index&&!allDecisions.some(existing=>existing.id===d.id)));allEvents.push(...householdRun.realizedEvents,...propertyYear.realizedEvents);goalResults.push(...yearGoalResults.map(result=>({year,...clone(result)})));
    let goalFundingCents=0;const genericGoals=model.goals.filter(g=>g.type!=='longTermHome'&&g.enabled!==false&&g.metadata?.annualFunding),goalAccountRows=genericGoals.map(g=>({goal:g,account:model.accounts.find(a=>a.type==='goalCash'&&a.metadata?.goalId===g.id)})).filter(r=>r.account);if(goalAccountRows.length){const available=Math.max(0,accounts.get(general.id)??0),allocation=allocateGoalFunding({availableCashCents:available,goals:goalAccountRows.map(({goal,account})=>({...goal,remainingCents:Math.max(0,goalTargetForYear(goal,year,index).nominalAmountCents-(accounts.get(account.id)??0))})),samePriorityPolicy:model.policies?.samePriorityGoalFunding??'proportional'});for(const row of allocation.allocations){const account=goalAccountRows.find(r=>r.goal.id===row.goalId).account;accounts.set(general.id,accounts.get(general.id)-row.allocatedCents);accounts.set(account.id,(accounts.get(account.id)??0)+row.allocatedCents);goalFundingCents+=row.allocatedCents;}}
    const allLiabilityDefs=[...model.liabilities.filter(l=>l.type!=='mortgage'),...propertyLiabilityDefinitions(properties,mapObject(propertyLiabilities))],closingBalances={...mapObject(nonPropertyLiabilities),...mapObject(propertyLiabilities)},balanceSheet=buildBalanceSheetSnapshot({accounts:model.accounts,accountBalances:mapObject(accounts),assets:model.assets,properties,liabilities:allLiabilityDefs,liabilityBalances:closingBalances}),cashFlow=buildCashFlowSnapshot({householdYear,propertyYear,goalFundingCents});
    const propertyComponents=propertyYear.reconciliation.netWorthChange.components.filter(c=>!['householdFreeCashFlow','genericHousingCosts'].includes(c.type)),investmentGrowth=sumCents(Object.values(householdYear.accountActivity).map(a=>a.growthCents??0)),explicit=[{id:`investment-growth:${year}`,type:'investmentGrowth',label:'Investment and cash growth',economicEffectCents:investmentGrowth},...propertyComponents.map((c,i)=>({...c,id:`property:${year}:${i}`,label:c.type}))],explicitEconomic=sumCents(explicit.map(c=>c.economicEffectCents)),actualChange=balanceSheet.totalNetWorthCents-openingSnapshot.totalNetWorthCents,retained={id:`retained-economics:${year}`,type:'retainedEarnedIncomeSurplus',label:'Retained household economics',economicEffectCents:actualChange-explicitEconomic},components=[retained,...explicit,{id:`account-transfers:${year}`,type:'accountTransfers',label:'Account and goal transfers',economicEffectCents:0,transferCents:goalFundingCents+householdYear.allocation.taxableInvestmentCents+householdYear.allocation.employeeRetirementCents},{id:`principal-transfers:${year}`,type:'principalTransfers',label:'Debt principal transfers',economicEffectCents:0,transferCents:cashFlow.debt.principalCents}];
    const decomposition=reconcileNetWorthChange({year,openingNetWorthCents:openingSnapshot.totalNetWorthCents,closingNetWorthCents:balanceSheet.totalNetWorthCents,components});
    const hEntries=householdYear.reconciliation.cash.entries,hSources=hEntries.filter(e=>['compensation','cashInterest'].includes(e.type)),hUses=hEntries.filter(e=>!['compensation','cashInterest'].includes(e.type)),cashSources=[...hSources,...(housingCents?[{id:`housing-reclass:${year}`,type:'housingReclassification',amountCents:housingCents}]:[]),...propertyYear.cashSources],cashUses=[...hUses,...propertyYear.cashUses,...(goalFundingCents?[{id:`goal-funding:${year}`,type:'goalFundingTransfer',amountCents:goalFundingCents}]:[])],cashRec=reconcileCash({year,openingCashCents:openingAccounts[general.id],sources:cashSources,uses:cashUses,actualClosingCashCents:accounts.get(general.id)}),balanceRec=reconcileBalanceSheet({year,accountValuesCents:model.accounts.map(a=>accounts.get(a.id)??0),assetValuesCents:[...properties.filter(p=>p.status!=='sold').map(p=>p.currentValueCents),...model.assets.map(a=>a.currentValueCents??a.valueCents??0)],liabilityValuesCents:Object.values(closingBalances),reportedGrossAssetsCents:balanceSheet.grossAssetsCents,reportedLiabilitiesCents:balanceSheet.totalLiabilitiesCents,reportedNetWorthCents:balanceSheet.totalNetWorthCents});
    const warnings=[...householdRun.warnings.filter(w=>w.code!=='NET_WORTH_DECOMPOSITION_FAILED'),...propertyRun.warnings.filter(w=>w.code!=='NET_WORTH_DECOMPOSITION_FAILED')].map(w=>normalizeWarning({...w,year:w.year??year}));if(cashFlow.freeCashFlowCents<0)warnings.push(normalizeWarning({code:'NEGATIVE_FREE_CASH_FLOW',severity:'warning',year,entityId:'household',explanation:`Free cash flow is negative by ${Math.abs(cashFlow.freeCashFlowCents)} cents.`,trace:{calculationId:`cash-flow:${year}`}}));if(householdYear.reserve.shortfallCents>0)warnings.push(normalizeWarning({code:'HOUSEHOLD_RESERVE_SHORTFALL',severity:'warning',year,entityId:'household',explanation:`Emergency reserves are short by ${householdYear.reserve.shortfallCents} cents.`,trace:{calculationId:`reserve:${year}`}}));if(householdYear.income.records.some(record=>record.metadata?.payState==='projected'||record.metadata?.bahState==='projected')||householdYear.taxes.provenanceIds?.some(id=>id.includes('projected')))warnings.push(normalizeWarning({code:'PROJECTED_DATA_FALLBACK',severity:'info',year,entityId:'household',explanation:'One or more official year-keyed values were unavailable; the documented projected fallback was used.',provenanceIds:householdYear.taxes.provenanceIds,trace:{calculationId:`income-tax:${year}`}}));allWarnings.push(...warnings);
    const accountActivity=clone(householdYear.accountActivity);for(const activity of Object.values(accountActivity)){activity.employeeContributionsCents=activity.contributionsCents;activity.employerGovernmentContributionsCents=0;activity.transfersInCents=0;activity.transfersOutCents=0;}if(accountActivity[general.id])accountActivity[general.id].employeeContributionsCents-=accountActivity[general.id].growthCents;for(const retirement of householdYear.retirement){const activity=accountActivity[retirement.accountId];if(activity){const employer=retirement.employerAutomaticCents+retirement.employerMatchCents;activity.employerGovernmentContributionsCents+=employer;activity.employeeContributionsCents-=employer;}}for(const account of model.accounts){const activity=accountActivity[account.id];if(!activity)continue;const actual=accounts.get(account.id)??0,difference=actual-activity.closingBalanceCents;if(difference>0)activity.transfersInCents=difference;else activity.transfersOutCents=-difference;activity.closingBalanceCents=actual;}
    const result={id:`annual:${year}`,year,ages:Object.fromEntries(people.map(p=>[p.id,ageOnDate(p,`${year}-12-31`)])),careers:householdYear.careers,householdState:householdYear.householdState,income:householdYear.income,taxes:householdYear.taxes,spending:householdYear.spending,cashFlow,accounts:{items:model.accounts.map(a=>({...clone(a),openingBalanceCents:openingAccounts[a.id],closingBalanceCents:accounts.get(a.id)})),activity:accountActivity},liabilities:{items:allLiabilityDefs,activity:[...householdYear.debt.changes,...propertyYear.propertyResults.map(p=>p.mortgage).filter(Boolean)]},properties:propertyYear.propertyResults,propertyPortfolio:propertyYear.portfolio,goals:yearGoalResults,decisions:yearDecisions,events:[...householdRun.realizedEvents,...propertyYear.realizedEvents],warnings,balanceSheet,netWorthDecomposition:decomposition,contributionVsGrowth:contributionVsGrowth({accountActivity,propertyResults:propertyYear.propertyResults}),reconciliation:{cash:cashRec,balanceSheet:balanceRec,netWorthChange:decomposition,propertyEquity:{passes:propertyYear.propertyResults.every(p=>p.equity.equityCents===p.equity.marketValueCents-p.equity.debtCents)},goalFunding:{passes:yearGoalResults.every(g=>!g.fundingPlan||g.fundingPlan.totalPlannedCents+g.fundingPlan.shortfallCents===g.fundingPlan.requiredCents)}},timeline:[],nextMajorMilestone:null,deltas:null,narrator:[]};
    years.push(result);previous=result;
  }
  const goalHistories=[...goalStates.values()].map(goal=>({goalId:goal.id,name:goal.name,plannedDate:goal.earliestDesiredDate,statusHistory:goal.statusHistory,provenanceIds:goal.provenanceIds})),intentEvents=model.propertyIntents.map(intent=>({id:intent.id,type:'property.purchaseIntent',propertyId:intent.propertyId,date:`${intent.desiredYear}-01-01`,resolvedDate:`${intent.desiredYear}-01-01`,title:`Planned purchase: ${intent.name}`,provenanceIds:intent.provenanceIds})),careerEvents=model.careers.map(stage=>({id:`career-start:${stage.id}`,type:'career.stage.start',personId:stage.personId,target:stage.personId,date:stage.startDate??`${stage.startYear}-01-01`,resolvedDate:stage.startDate??`${stage.startYear}-01-01`,title:`${stage.role} begins`,provenanceIds:stage.provenanceIds??[]})),timeline=buildTimeline({plannedEvents:[...resolvedPlanned,...intentEvents,...careerEvents],realizedEvents:allEvents,decisions:allDecisions,goalHistories});for(let i=0;i<years.length;i++){const row=years[i];row.timeline=timeline.filter(item=>y(item.realizedDate??item.plannedDate)===row.year);row.nextMajorMilestone=nextMajorMilestone({year:row.year,timeline,referenceAge:Object.values(row.ages)[0]});row.deltas=yearOverYearDeltas(row,years[i-1]);row.narrator=narrateYear(row,years[i-1],{previousSignatures:years[i-1]?.narrator.map(o=>o.signature)??[]});}
  const timelineDeltas=timeline.map(item=>({timelineId:item.id,...plannedVsRealizedDelta(item)})).filter(item=>item.plannedDate),invariants={cash:years.every(r=>r.reconciliation.cash.passes),balanceSheet:years.every(r=>r.reconciliation.balanceSheet.passes),netWorthChange:years.every(r=>r.reconciliation.netWorthChange.passes),propertyEquity:years.every(r=>r.reconciliation.propertyEquity.passes),goalFunding:years.every(r=>r.reconciliation.goalFunding.passes)};invariants.passes=Object.values(invariants).every(Boolean);
  if(JSON.stringify(model)!==original)throw new Error('Unified financial-life simulation mutated model input.');return{metadata:{valid:true,schemaVersion:model.schemaVersion,modelVersion:'2.0.0-m5',baseCurrencyYear:model.baseCurrencyYear,deterministic:true,authoritativeEntryPoint:'simulateFinancialLife',withinYearOrder:WITHIN_YEAR_ORDER,monthlySubperiodRules:MONTHLY_SUBPERIOD_RULES,unresolvedChoicePolicy:model.policies?.unresolvedChoice??{action:'leaveUnexecuted'}},years,timeline,timelineDeltas,realizedEvents:allEvents,decisions:allDecisions,goalResults,goals:[...goalStates.values()],warnings:allWarnings,errors:[],invariants};
}
