import { monthlyPaymentCents } from './mortgage.js';
import { goalTargetForYear, goalFundingProgress } from './goals.js';
import { sumCents } from './money.js';

const moneyRule=(ruleId,actualCents,requiredCents,explanation,{kind='hard',comparison='gte'}={})=>{const pass=comparison==='lte'?actualCents<=requiredCents:actualCents>=requiredCents,shortfallCents=pass?0:comparison==='lte'?actualCents-requiredCents:requiredCents-actualCents;return{ruleId,kind,actualCents,requiredCents,pass,shortfallCents,severity:pass?'none':kind==='comfort'?'comfort':'blocking',explanation:pass?`${ruleId} passes.`:explanation};};
const booleanRule=(ruleId,pass,explanation,{kind='hard'}={})=>({ruleId,kind,actual:pass,required:true,pass,shortfall:pass?0:1,severity:pass?'none':kind==='comfort'?'comfort':'blocking',explanation:pass?`${ruleId} passes.`:explanation});
const yearOf=date=>date?Number(String(date).slice(0,4)):null;

export function calculateHousingBurden({annualHousingCostCents,afterTaxIncomeCents,grossCashCompensationCents,denominator='afterTaxIncome',comfortThreshold}){
  const denominatorCents=denominator==='grossCashCompensation'?grossCashCompensationCents:afterTaxIncomeCents,burden=denominatorCents>0?annualHousingCostCents/denominatorCents:Infinity,excessCents=burden<=comfortThreshold?0:Math.max(0,annualHousingCostCents-Math.floor(denominatorCents*comfortThreshold));return{annualHousingCostCents,denominator,denominatorCents,burden,comfortThreshold,pass:burden<=comfortThreshold,excessCents};
}

export function buildHomeFundingPlan({requiredCents,sources,permittedSourceTypes}){
  let remaining=requiredCents;const order=[...permittedSourceTypes],composition=[];
  for(const type of order){if(!permittedSourceTypes.includes(type))continue;for(const source of sources.filter(s=>s.type===type).sort((a,b)=>String(a.sourceId).localeCompare(String(b.sourceId)))){const amount=Math.min(remaining,Math.max(0,source.availableCents));composition.push({sourceId:source.sourceId,type,amountCents:amount,provenanceIds:structuredClone(source.provenanceIds??[])});remaining-=amount;if(!remaining)break;}if(!remaining)break;}
  return{requiredCents,composition,totalPlannedCents:sumCents(composition.map(c=>c.amountCents)),shortfallCents:remaining,protectedFundsUsedCents:0,retirementUsedCents:0,emergencyReserveUsedCents:0,propertyReservesUsedCents:0};
}

export function rankGoalBlockers(rules){
  const failed=rules.filter(r=>!r.pass),category=r=>r.kind==='hard'?0:r.ruleId.includes('Reserve')?1:r.ruleId.includes('freeCashFlow')?2:r.ruleId.includes('protected')?3:4,normalized=r=>r.requiredCents>0?r.shortfallCents/r.requiredCents:r.shortfall??1;
  return failed.sort((a,b)=>category(a)-category(b)||normalized(b)-normalized(a)||String(a.ruleId).localeCompare(String(b.ruleId))).map((r,index)=>({...r,rank:index+1,role:index===0?'primary':'secondary'}));
}

export function evaluateLongTermHome({goal,year,index,household,strategy={}}){
  const target=goalTargetForYear(goal,year,index),price=target.nominalAmountCents,downPaymentCents=Math.round(price*goal.home.downPaymentRate),closingCostsCents=Math.round(price*goal.home.buyerClosingCostRate),setupCostsCents=goal.home.moveSetupCostsBasis==='real'?Math.round(goal.home.moveSetupCostsCents*price/goal.target.amountCents):goal.home.moveSetupCostsCents,initialHomeReserveCents=goal.home.initialHomeReserveCents??0,requiredUpfrontCents=downPaymentCents+closingCostsCents+setupCostsCents+initialHomeReserveCents,financedAmountCents=price-downPaymentCents;
  const saleSources=(strategy.proposedSaleProperties??[]).filter(p=>goal.fundingPolicy.permittedPropertySaleIds?.includes(p.propertyId)).map(p=>({sourceId:p.propertyId,type:'selectedPropertySaleProceeds',availableCents:p.netSaleProceedsCents,provenanceIds:p.provenanceIds}));
  const sources=[{sourceId:'dedicated-home-fund',type:'dedicatedGoalCash',availableCents:household.dedicatedGoalCashCents??0},{sourceId:'general-cash',type:'generalCash',availableCents:household.generalCashCents??0},{sourceId:'taxable-investments',type:'taxableInvestments',availableCents:goal.fundingPolicy.allowTaxableInvestments?household.taxableInvestmentsCents??0:0},...saleSources];
  const fundingPlan=buildHomeFundingPlan({requiredCents:requiredUpfrontCents,sources,permittedSourceTypes:goal.fundingPolicy.permittedSources}),progress=goalFundingProgress({requiredCents:requiredUpfrontCents,dedicatedCents:household.dedicatedGoalCashCents,permittedSources:sources.filter(s=>goal.fundingPolicy.permittedSources.includes(s.type))});
  const annualMortgageCents=monthlyPaymentCents(financedAmountCents,goal.home.mortgageRate,goal.home.mortgageTermMonths)*12,propertyTaxCents=Math.round(price*(goal.home.propertyTaxRate??0)),insuranceCents=Math.round(price*(goal.home.insuranceRate??0)),maintenanceCents=Math.round(price*(goal.home.maintenanceRate??0)),annualHousingCostCents=annualMortgageCents+propertyTaxCents+insuranceCents+(goal.home.hoaAnnualCents??0)+maintenanceCents+(goal.home.otherAnnualCarryingCostsCents??0),replacedHousingCents=household.currentAnnualHousingCostCents??0,postPurchaseFreeCashFlowCents=(household.prePurchaseFreeCashFlowCents??0)+replacedHousingCents-annualHousingCostCents;
  const burden=calculateHousingBurden({annualHousingCostCents,afterTaxIncomeCents:household.afterTaxIncomeCents,grossCashCompensationCents:household.grossCashCompensationCents,denominator:goal.constraints.housingBurdenDenominator??'afterTaxIncome',comfortThreshold:goal.constraints.maxComfortHousingBurden});
  const retainedReserves=(household.retainedPropertyReserves??[]).filter(r=>!strategy.proposedSaleProperties?.some(p=>p.propertyId===r.propertyId)),propertyReserveRequired=sumCents(retainedReserves.map(r=>r.requiredCents)),propertyReserveActual=sumCents(retainedReserves.map(r=>r.actualCents)),hasExistingPrimary=Boolean(household.existingPrimaryResidenceId),primaryPlan=goal.home.existingPrimaryDispositionPlan;
  const timingPass=year>=(yearOf(goal.earliestDesiredDate)??year),financingValid=financedAmountCents>=0&&goal.home.mortgageRate>=0&&goal.home.mortgageTermMonths>0;
  const hardRules=[booleanRule('desiredTimingReached',timingPass,'The earliest desired purchase date has not been reached.'),moneyRule('permittedUpfrontFunding',progress.permittedFundingCents,requiredUpfrontCents,`Permitted upfront funding is short by ${Math.max(0,requiredUpfrontCents-progress.permittedFundingCents)} cents.`),moneyRule('downPaymentAvailable',progress.permittedFundingCents,downPaymentCents,'Permitted down-payment funding is insufficient.'),moneyRule('closingAndSetupAvailable',Math.max(0,progress.permittedFundingCents-downPaymentCents),closingCostsCents+setupCostsCents+initialHomeReserveCents,'Closing, setup, or initial reserve funding is insufficient.'),moneyRule('householdEmergencyReservePreserved',household.emergencyReserveActualCents,household.emergencyReserveRequiredCents,'Household emergency reserve would fall below its floor.'),moneyRule('retainedPropertyReservesPreserved',propertyReserveActual,propertyReserveRequired,'Retained-property reserves would fall below their required floor.'),booleanRule('protectedAccountsUntouched',!goal.fundingPolicy.permittedSources.includes('retirement')&&!goal.fundingPolicy.permittedSources.includes('emergencyReserve')&&!goal.fundingPolicy.permittedSources.includes('propertyReserves'),'Protected accounts cannot fund the home.'),booleanRule('financingTermsValid',financingValid,'Mortgage financing terms are invalid.'),booleanRule('requiredDebtObligationsPayable',household.requiredDebtObligationsPayable!==false,'Required debt obligations would not remain payable.'),moneyRule('postPurchaseFreeCashFlowNonnegative',postPurchaseFreeCashFlowCents,goal.constraints.minimumPossibleFreeCashFlowCents??0,'Post-purchase free cash flow would be below the hard minimum.'),booleanRule('existingPrimaryDispositionExplicit',!hasExistingPrimary||Boolean(primaryPlan),'An existing primary residence requires an explicit sell, convert, or transition plan.')];
  const discretionaryAfter=Math.max(0,(household.discretionaryCapacityCents??0)-(annualHousingCostCents-replacedHousingCents));
  const comfortRules=[moneyRule('housingBurdenComfort',Math.round(burden.burden*1e6),Math.round(burden.comfortThreshold*1e6),`Housing burden ${(burden.burden*100).toFixed(1)}% exceeds the ${(burden.comfortThreshold*100).toFixed(1)}% comfort limit.`,{kind:'comfort',comparison:'lte'}),moneyRule('postPurchaseFreeCashFlowComfort',postPurchaseFreeCashFlowCents,goal.constraints.minimumComfortFreeCashFlowCents??0,'Post-purchase free cash flow is below the comfort floor.',{kind:'comfort'}),moneyRule('discretionaryCapacityPreserved',discretionaryAfter,goal.constraints.minimumDiscretionaryCapacityCents??0,'The home would reduce discretionary/lifestyle capacity below its protected level.',{kind:'comfort'}),booleanRule('protectedRetirementViable',household.protectedRetirementViable!==false,'Protected retirement funding would not remain viable.',{kind:'comfort'}),booleanRule('nearTermProtectedObligationsFunded',household.nearTermProtectedObligationsFunded!==false,'A higher-priority near-term obligation would be displaced.',{kind:'comfort'}),moneyRule('fragileLiquidityBuffer',Math.max(0,progress.permittedFundingCents-requiredUpfrontCents),goal.constraints.minimumPostPurchaseLiquidityCents??0,'Post-purchase permitted liquidity would be below the configured buffer.',{kind:'comfort'})];
  const hardPass=hardRules.every(r=>r.pass),comfortPass=hardPass&&comfortRules.every(r=>r.pass),primaryChoiceFailure=hardRules.find(r=>r.ruleId==='existingPrimaryDispositionExplicit'&&!r.pass),latest=yearOf(goal.latestAcceptableDate),status=primaryChoiceFailure?'needsUserChoice':!hardPass?(latest&&year>=latest?'rejected':'delayed'):comfortPass?'comfortablyAffordable':'possible',rules=[...hardRules,...comfortRules],rankedBlockers=rankGoalBlockers(rules),fundingStatus=progress.remainingShortfallCents===0?'funded':progress.permittedFundingCents>0?'funding':'planned',preferredStart=yearOf(goal.preferredWindow?.startDate),preferredEnd=yearOf(goal.preferredWindow?.endDate),preferredWindowStatus=!preferredStart&&!preferredEnd?'notConfigured':preferredStart&&year<preferredStart?'beforePreferredWindow':preferredEnd&&year>preferredEnd?'afterPreferredWindow':'withinPreferredWindow',nextReevaluationYear=['delayed','possible','needsUserChoice'].includes(status)?year+1:null;
  return{id:`decision:${goal.id}:${year}`,goalId:goal.id,evaluatedYear:year,status,fundingStatus,preferredWindowStatus,nextReevaluationYear,targetPriceRealCents:target.realAmountCents,targetPriceNominalCents:price,downPaymentRequiredCents:downPaymentCents,closingCostsCents,setupCostsCents,initialHomeReserveCents,requiredUpfrontCents,permittedFundingAvailableCents:progress.permittedFundingCents,progress,financedAmountCents,annualHousingCostCents,housingCost:{annualMortgageCents,propertyTaxCents,insuranceCents,hoaCents:goal.home.hoaAnnualCents??0,maintenanceCents,otherCents:goal.home.otherAnnualCarryingCostsCents??0},housingBurden:burden,prePurchaseFreeCashFlowCents:household.prePurchaseFreeCashFlowCents,postPurchaseFreeCashFlowCents,freeCashFlowDifferenceCents:postPurchaseFreeCashFlowCents-household.prePurchaseFreeCashFlowCents,householdReserveAfterCents:household.emergencyReserveActualCents,propertyReservesAfterCents:propertyReserveActual,fundingPlan,rules,blockers:rankedBlockers,primaryBlocker:rankedBlockers[0]??null,secondaryBlockers:rankedBlockers.slice(1),retainedPropertyIds:retainedReserves.map(r=>r.propertyId),proposedSalePropertyIds:(strategy.proposedSaleProperties??[]).map(p=>p.propertyId),estimatedSaleProceedsCents:sumCents(saleSources.map(s=>s.availableCents)),rentalCashFlowEffectCents:sumCents((strategy.proposedSaleProperties??[]).map(p=>-(p.annualRentalCashFlowCents??0))),explanation:status==='comfortablyAffordable'?'The home is comfortably affordable under the configured planning constraints.':status==='possible'?'The transaction passes hard constraints but fails one or more comfort constraints.':status==='needsUserChoice'?'A preference-dependent property disposition decision is required.':rankedBlockers[0]?.explanation??'The goal is not feasible within this evaluation.'};
}

export function compareHomeStrategies({goal,year,index,household,strategies,preferenceSensitive=true}){const evaluations=strategies.map(strategy=>({...evaluateLongTermHome({goal,year,index,household,strategy}),strategyId:strategy.id})),healthy=evaluations.filter(e=>['possible','comfortablyAffordable'].includes(e.status));return{status:preferenceSensitive&&healthy.length>1?'needsUserChoice':healthy.sort((a,b)=>(a.status==='comfortablyAffordable'?-1:1)-(b.status==='comfortablyAffordable'?-1:1))[0]?.status??'delayed',evaluations,needsUserChoice:preferenceSensitive&&healthy.length>1,explanation:preferenceSensitive&&healthy.length>1?'Multiple financially viable keep/sell strategies remain; the engine will not optimize the preference away.':'Only one strategy is currently viable or no preference choice is needed.'};}

export function homeGoalToPropertyIntent({goal,decision,year}){return{id:`${goal.id}:property-intent`,propertyId:goal.home.resultingPropertyId,name:goal.name,desiredYear:year,earliestAcceptableYear:year,latestAcceptableYear:year,enabled:true,propertyRole:'primaryResidence',locationKey:goal.home.locationKey,ownership:structuredClone(goal.home.ownership),expectedPriceCents:decision.targetPriceNominalCents,downPaymentCents:decision.downPaymentRequiredCents,financedAmountCents:decision.financedAmountCents,buyerClosingCostsCents:decision.closingCostsCents,initialSetupCostsCents:decision.setupCostsCents,initialPropertyReserveCents:decision.initialHomeReserveCents,propertyReserveMonths:goal.home.initialHomeReserveMonths??0,mortgageId:`${goal.home.resultingPropertyId}:mortgage`,mortgageRate:goal.home.mortgageRate,mortgageTermMonths:goal.home.mortgageTermMonths,estimatedAnnualDebtServiceCents:0,minimumPostPurchaseFreeCashFlowCents:0,fundingPolicy:{sources:goal.fundingPolicy.allowTaxableInvestments?['generalCash','taxableInvestments']:['generalCash'],allowTaxableInvestments:goal.fundingPolicy.allowTaxableInvestments},operations:{baseYear:year,monthlyRentCents:0,rentGrowthRate:0,vacancyRate:0,propertyTaxCents:decision.housingCost.propertyTaxCents,insuranceCents:decision.housingCost.insuranceCents,hoaCents:decision.housingCost.hoaCents,maintenanceRate:0,capexRate:0,managementRate:0,primaryMaintenanceCents:decision.housingCost.maintenanceCents+decision.housingCost.otherCents},provenanceIds:structuredClone(goal.provenanceIds),goalId:goal.id};}
