import { buildPriceIndex } from './currency.js';
import { appendGoalStatus, allocateGoalFunding } from './goals.js';
import { compareHomeStrategies, evaluateLongTermHome, homeGoalToPropertyIntent } from './home-goal.js';
import { simulatePropertyLifecycle } from './property-lifecycle.js';
import { reconcileBalanceSheet, reconcileCash } from './reconciliation.js';
import { reconcileNetWorthChange } from './decomposition.js';
import { sumCents } from './money.js';

function homeHouseholdState(cfg,state,year,rental){return{generalCashCents:state.generalCashCents,dedicatedGoalCashCents:state.dedicatedGoalCashCents,taxableInvestmentsCents:state.taxableInvestmentsCents,retirementInvestmentsCents:state.retirementInvestmentsCents,emergencyReserveActualCents:state.emergencyReserveCents,emergencyReserveRequiredCents:cfg.emergencyReserveRequiredByYear[year],retainedPropertyReserves:rental?.held?[{propertyId:rental.propertyId,actualCents:rental.reserveCents,requiredCents:rental.requiredReserveCents}]:[],grossCashCompensationCents:cfg.grossCashCompensationByYear[year],afterTaxIncomeCents:cfg.afterTaxIncomeByYear[year],prePurchaseFreeCashFlowCents:cfg.prePurchaseFreeCashFlowByYear[year],currentAnnualHousingCostCents:cfg.currentAnnualHousingCostByYear[year],discretionaryCapacityCents:cfg.discretionaryCapacityByYear[year],requiredDebtObligationsPayable:true,protectedRetirementViable:true,nearTermProtectedObligationsFunded:true,existingPrimaryResidenceId:cfg.existingPrimaryResidenceId??null};}

function saleStrategyForYear(cfg,year){const strategy=structuredClone(cfg.strategyByYear?.[year]??cfg.defaultStrategy??{id:'keep-rental',proposedSaleProperties:[]});return strategy;}

export function simulateHomeGoal(model){
  const before=structuredClone(model),cfg=model.goalSimulation,index=buildPriceIndex(model.assumptions.priceIndex,cfg.endYear),goalInput=model.goals.find(g=>g.type==='longTermHome');if(!goalInput)throw new TypeError('A longTermHome goal is required.');let goal=structuredClone(goalInput),rental=structuredClone(cfg.existingRental??null),state={generalCashCents:cfg.openingGeneralCashCents,dedicatedGoalCashCents:cfg.openingDedicatedGoalCashCents,taxableInvestmentsCents:cfg.openingTaxableInvestmentsCents,retirementInvestmentsCents:cfg.openingRetirementInvestmentsCents,emergencyReserveCents:cfg.openingEmergencyReserveCents},home=null,homeDebtCents=0,homeReserveCents=0,executed=false,completedRecorded=false,earliestPossibleYear=null,earliestComfortableYear=null;
  const annualResults=[],decisions=[],realizedEvents=[],warnings=[];
  for(let year=cfg.startYear;year<=cfg.endYear;year++){
    const opening=structuredClone(state),openingCash=opening.generalCashCents+opening.dedicatedGoalCashCents,openingRentalEquity=rental?.held?rental.valueCents+rental.reserveCents-rental.debtCents:0,openingHomeEquity=home?home.currentValueCents+homeReserveCents-homeDebtCents:0,openingGrossAssets=sumCents(Object.values(opening))+Math.max(0,openingRentalEquity+(rental?.held?rental.debtCents:0))+Math.max(0,openingHomeEquity+homeDebtCents),openingLiabilities=(rental?.held?rental.debtCents:0)+homeDebtCents,openingNetWorth=openingGrossAssets-openingLiabilities,cashSources=[],cashUses=[],accountTransfers=[],yearDecisions=[],yearEvents=[];
    const annualFree=cfg.annualCashContributionByYear[year]??0;state.generalCashCents+=annualFree;if(annualFree)cashSources.push({id:`annualGoalCash:${year}`,type:'annualGoalCash',amountCents:annualFree});
    const dedicatedContribution=Math.min(state.generalCashCents,cfg.dedicatedHomeContributionByYear?.[year]??0);if(dedicatedContribution){state.generalCashCents-=dedicatedContribution;state.dedicatedGoalCashCents+=dedicatedContribution;accountTransfers.push({id:`homeFund:${year}`,type:'goalAccountTransfer',from:'generalCash',to:'dedicatedGoalCash',amountCents:dedicatedContribution,economicEffectCents:0});}
    let evaluation=null,strategy= saleStrategyForYear(cfg,year),strategyComparison=null,propertyExecution=null,saleEffectCents=0;
    if(!executed){const household=homeHouseholdState(cfg,state,year,rental);evaluation=evaluateLongTermHome({goal,year,index,household,strategy});
      if(cfg.alternativeStrategiesByYear?.[year])strategyComparison=compareHomeStrategies({goal,year,index,household,strategies:cfg.alternativeStrategiesByYear[year],preferenceSensitive:true});
      if(['possible','comfortablyAffordable'].includes(evaluation.status)&&earliestPossibleYear==null)earliestPossibleYear=year;if(evaluation.status==='comfortablyAffordable'&&earliestComfortableYear==null)earliestComfortableYear=year;
      yearDecisions.push(evaluation);decisions.push(evaluation);goal=appendGoalStatus(goal,{date:`${year}-12-31`,status:evaluation.status,reason:evaluation.explanation,decisionId:evaluation.id,blockerIds:evaluation.blockers.map(b=>b.ruleId),metrics:{targetPriceNominalCents:evaluation.targetPriceNominalCents,requiredUpfrontCents:evaluation.requiredUpfrontCents,housingBurden:evaluation.housingBurden.burden,postPurchaseFreeCashFlowCents:evaluation.postPurchaseFreeCashFlowCents}});
      if(evaluation.status==='comfortablyAffordable'&&cfg.autoExecute!==false){
        const sold=(strategy.proposedSaleProperties??[]).find(p=>p.propertyId===rental?.propertyId);if(sold){state.generalCashCents+=sold.netSaleProceedsCents;cashSources.push({id:`selectedSale:${sold.propertyId}:${year}`,type:'selectedPropertySaleProceeds',amountCents:sold.netSaleProceedsCents});saleEffectCents=sold.netSaleProceedsCents-(rental.valueCents+rental.reserveCents-rental.debtCents);rental.held=false;}
        const intent=homeGoalToPropertyIntent({goal,decision:evaluation,year}),propertyModel={schemaVersion:model.schemaVersion,modelVersion:model.modelVersion,baseCurrencyYear:model.baseCurrencyYear,propertySimulation:{startYear:year,endYear:year,openingCashCents:state.generalCashCents+state.dedicatedGoalCashCents,emergencyReserveActualCents:state.emergencyReserveCents,emergencyReserveRequiredByYear:{[year]:cfg.emergencyReserveRequiredByYear[year]},openingTaxableInvestmentsCents:state.taxableInvestmentsCents,openingRetirementInvestmentsCents:state.retirementInvestmentsCents,annualHouseholdFreeCashFlowByYear:{[year]:0},genericHousingSpendingByYear:{[year]:0},appreciationRate:cfg.homeAppreciationRate,sellerTransactionCostRate:cfg.sellerTransactionCostRate},propertyIntents:[intent],plannedEvents:[]};
        propertyExecution=simulatePropertyLifecycle(propertyModel);const propertyYear=propertyExecution.annualResults[0],purchase=propertyYear.portfolio.purchases[0];if(!purchase)throw new Error('Comfortable home goal did not produce a property purchase.');
        const taxableLiquidation=purchase.funding.taxableInvestmentCents;if(taxableLiquidation){cashSources.push({id:`brokerageLiquidation:${year}`,type:'brokerageLiquidation',amountCents:taxableLiquidation});cashUses.push({id:`brokeragePurchaseFunding:${year}`,type:'brokerageToHomeTransfer',amountCents:taxableLiquidation});accountTransfers.push({id:`brokerageToHome:${year}`,type:'brokerageToProperty',amountCents:taxableLiquidation,economicEffectCents:0});}
        cashUses.push(...propertyYear.cashUses);state.generalCashCents=propertyYear.closing.cashCents;state.dedicatedGoalCashCents=0;state.taxableInvestmentsCents=propertyYear.closing.taxableInvestmentsCents;state.retirementInvestmentsCents=propertyYear.closing.retirementInvestmentsCents;state.emergencyReserveCents=propertyYear.closing.emergencyReserveCents;home=propertyYear.closing.properties[intent.propertyId];homeDebtCents=propertyYear.closing.liabilities[intent.mortgageId];homeReserveCents=propertyYear.portfolio.propertyReserveCents;executed=true;const executedDecision={...evaluation,id:`${evaluation.id}:executed`,status:'executed',propertyId:intent.propertyId,mortgageId:intent.mortgageId,actualDate:`${year}-01-01`};yearDecisions.push(executedDecision);decisions.push(executedDecision);goal=appendGoalStatus(goal,{date:`${year}-01-01`,status:'executed',reason:'Comfort constraints passed and the normal property lifecycle executed the purchase.',decisionId:executedDecision.id,metrics:{propertyId:intent.propertyId,mortgageId:intent.mortgageId}});goal.metadata.resultingPropertyId=intent.propertyId;yearEvents.push(...propertyExecution.realizedEvents);realizedEvents.push(...propertyExecution.realizedEvents);
      }
    }else if(!completedRecorded){goal=appendGoalStatus(goal,{date:`${year}-01-01`,status:'completed',reason:'The goal-created primary residence remains on the balance sheet.',metrics:{propertyId:home.id}});completedRecorded=true;}
    const closingCash=state.generalCashCents+state.dedicatedGoalCashCents,retainedRentalValue=rental?.held?rental.valueCents:0,retainedRentalReserve=rental?.held?rental.reserveCents:0,retainedRentalDebt=rental?.held?rental.debtCents:0,homeValue=home?.currentValueCents??0,closingGrossAssets=closingCash+state.taxableInvestmentsCents+state.retirementInvestmentsCents+state.emergencyReserveCents+retainedRentalValue+retainedRentalReserve+homeValue+homeReserveCents,closingLiabilities=retainedRentalDebt+homeDebtCents,closingNetWorth=closingGrossAssets-closingLiabilities;
    const propertyComponents=propertyExecution?.annualResults[0].reconciliation.netWorthChange.components??[],components=[{type:'annualGoalCash',economicEffectCents:annualFree},{type:'selectedPropertySaleEffect',economicEffectCents:saleEffectCents},...propertyComponents];if(!propertyExecution&&home)components.push({type:'goalAssetCarry',economicEffectCents:0});
    const cashRec=reconcileCash({year,openingCashCents:openingCash,sources:cashSources,uses:cashUses,actualClosingCashCents:closingCash}),balanceRec=reconcileBalanceSheet({year,accountValuesCents:[closingCash,state.taxableInvestmentsCents,state.retirementInvestmentsCents,state.emergencyReserveCents,retainedRentalReserve,homeReserveCents],assetValuesCents:[retainedRentalValue,homeValue],liabilityValuesCents:[retainedRentalDebt,homeDebtCents],reportedGrossAssetsCents:closingGrossAssets,reportedLiabilitiesCents:closingLiabilities,reportedNetWorthCents:closingNetWorth}),decomp=reconcileNetWorthChange({year,openingNetWorthCents:openingNetWorth,closingNetWorthCents:closingNetWorth,components});if(cashRec.warning)warnings.push(cashRec.warning);if(balanceRec.warning)warnings.push(balanceRec.warning);if(decomp.warning)warnings.push(decomp.warning);
    annualResults.push({year,age:year-cfg.referenceBirthYear,evaluation,strategyComparison,goalStatus:goal.status,goalStatusHistory:structuredClone(goal.statusHistory),cashSources,cashUses,accountTransfers,decisionResults:yearDecisions,realizedEvents:yearEvents,fundingPlan:evaluation?.fundingPlan??null,propertyExecution:propertyExecution?.annualResults[0]??null,closing:{...structuredClone(state),home:structuredClone(home),homeDebtCents,homeReserveCents,retainedRental:structuredClone(rental),grossAssetsCents:closingGrossAssets,totalLiabilitiesCents:closingLiabilities,netWorthCents:closingNetWorth},reconciliation:{cash:cashRec,balanceSheet:balanceRec,netWorthChange:decomp}});
  }
  if(JSON.stringify(model)!==JSON.stringify(before))throw new Error('Goal simulation mutated model input.');return{annualResults,goal,decisions,realizedEvents,warnings,metadata:{modelVersion:'2.0.0-m4',deterministic:true,earliestPossibleYear,earliestComfortableYear,propertyEngine:'model/property-lifecycle.js',workOptionalCompatible:true}};
}

export function simulateGenericGoals(model){
  const before=structuredClone(model),cfg=model.genericGoalSimulation,goals=structuredClone(model.goals),dedicated=Object.fromEntries(goals.map(g=>[g.id,0])),state={generalCashCents:cfg.openingGeneralCashCents,reserveCents:cfg.openingReserveCents,retirementCents:cfg.openingRetirementCents},annualResults=[],warnings=[];
  for(let year=cfg.startYear;year<=cfg.endYear;year++){
    const opening=structuredClone(state),openingDedicated=sumCents(Object.values(dedicated)),openingCash=opening.generalCashCents+opening.reserveCents+openingDedicated,openingNW=openingCash+opening.retirementCents,cashSources=[],cashUses=[],transfers=[];const inflow=cfg.annualAvailableCashByYear[year]??0;state.generalCashCents+=inflow;cashSources.push({id:`genericIncome:${year}`,type:'availableCash',amountCents:inflow});
    const reserveNeed=Math.max(0,(cfg.reserveRequirementByYear[year]??0)-state.reserveCents),retirementNeed=cfg.protectedRetirementByYear[year]??0,hardNeed=cfg.hardObligationsByYear[year]??0,remainingGoals=goals.map(g=>({...g,remainingCents:Math.max(0,g.target.amountCents-dedicated[g.id])}));
    const allocation=allocateGoalFunding({availableCashCents:state.generalCashCents,preallocations:[{id:'hardObligations',rank:0,requiredCents:hardNeed},{id:'reserveFloor',rank:1,requiredCents:reserveNeed},{id:'protectedRetirement',rank:2,requiredCents:retirementNeed}],goals:remainingGoals,samePriorityPolicy:cfg.samePriorityPolicy});
    const pre=id=>allocation.preallocations.find(p=>p.id===id)?.allocatedCents??0,hardPaid=pre('hardObligations'),reserveFunded=pre('reserveFloor'),retirementFunded=pre('protectedRetirement');state.generalCashCents-=hardPaid+reserveFunded+retirementFunded;state.reserveCents+=reserveFunded;state.retirementCents+=retirementFunded;if(hardPaid)cashUses.push({id:`hard:${year}`,type:'hardObligations',amountCents:hardPaid});if(retirementFunded)cashUses.push({id:`retirement:${year}`,type:'protectedRetirementContribution',amountCents:retirementFunded});if(reserveFunded)transfers.push({id:`reserve:${year}`,type:'reserveRestoration',amountCents:reserveFunded,economicEffectCents:0});
    for(const row of allocation.allocations){state.generalCashCents-=row.allocatedCents;dedicated[row.goalId]+=row.allocatedCents;if(row.allocatedCents)transfers.push({id:`goal:${row.goalId}:${year}`,type:'goalFundingTransfer',amountCents:row.allocatedCents,economicEffectCents:0});}
    const executions=[];for(const goal of goals){if(goal.metadata?.executeWhenFunded&&dedicated[goal.id]>=goal.target.amountCents){const amount=goal.target.amountCents;dedicated[goal.id]-=amount;cashUses.push({id:`execute:${goal.id}:${year}`,type:'majorPurchase',amountCents:amount});executions.push({goalId:goal.id,status:'executed',amountCents:amount});goal.metadata.executeWhenFunded=false;}}
    const closingDedicated=sumCents(Object.values(dedicated)),closingCash=state.generalCashCents+state.reserveCents+closingDedicated,closingNW=closingCash+state.retirementCents,components=[{type:'availableCash',economicEffectCents:inflow},{type:'hardObligations',economicEffectCents:-hardPaid},{type:'protectedRetirementTransfer',economicEffectCents:0,transferCents:retirementFunded},{type:'reserveTransfers',economicEffectCents:0,transferCents:reserveFunded},{type:'goalFundingTransfers',economicEffectCents:0,transferCents:sumCents(allocation.allocations.map(a=>a.allocatedCents))},{type:'majorPurchases',economicEffectCents:-sumCents(executions.map(e=>e.amountCents))}],cashRec=reconcileCash({year,openingCashCents:openingCash,sources:cashSources,uses:cashUses,actualClosingCashCents:closingCash}),balanceRec=reconcileBalanceSheet({year,accountValuesCents:[state.generalCashCents,state.reserveCents,state.retirementCents,closingDedicated],assetValuesCents:[],liabilityValuesCents:[],reportedGrossAssetsCents:closingNW,reportedLiabilitiesCents:0,reportedNetWorthCents:closingNW}),decomp=reconcileNetWorthChange({year,openingNetWorthCents:openingNW,closingNetWorthCents:closingNW,components});if(cashRec.warning)warnings.push(cashRec.warning);if(balanceRec.warning)warnings.push(balanceRec.warning);if(decomp.warning)warnings.push(decomp.warning);annualResults.push({year,allocation,executions,dedicated:structuredClone(dedicated),closing:structuredClone(state),cashSources,cashUses,transfers,reconciliation:{cash:cashRec,balanceSheet:balanceRec,netWorthChange:decomp}});
  }
  if(JSON.stringify(model)!==JSON.stringify(before))throw new Error('Generic goal simulation mutated model input.');return{annualResults,warnings,metadata:{modelVersion:'2.0.0-m4',deterministic:true,majorPurchaseCompatible:true,workOptionalCompatible:true}};
}
