import { sumCents } from './money.js';

const accountCategory=type=>type==='generalCash'?'generalCash':type==='emergencyReserve'?'emergencyReserve':type==='goalCash'?'dedicatedGoalFunds':type==='taxableInvestment'?'taxableInvestments':type==='retirementInvestment'?'retirementAccounts':'otherFinancialAssets';
const ownerShares=(item)=>item.ownership??[{ownerId:item.ownerId??'household',share:1}];

export function buildBalanceSheetSnapshot({accounts,accountBalances,assets=[],properties=[],liabilities,liabilityBalances}){
  const accountItems=accounts.map(account=>({id:account.id,name:account.name??account.id,kind:'account',type:account.type,category:accountCategory(account.type),ownership:ownerShares(account),valueCents:accountBalances[account.id]??0,liquidity:account.liquidity??(account.type==='retirementInvestment'?'restricted':'immediate'),protected:Boolean(account.protected)}));
  const propertyItems=properties.filter(p=>p.status!=='sold').map(property=>({id:property.id,name:property.name,kind:'property',type:'property',category:property.status==='rental'?'rentalProperties':'primaryResidence',ownership:ownerShares(property),valueCents:property.currentValueCents,liquidity:'illiquid',linkedLiabilityIds:property.linkedLiabilityIds??[],status:property.status}));
  const otherItems=assets.filter(a=>a.status!=='sold'&&a.status!=='disposed').map(asset=>({id:asset.id,name:asset.name,kind:'asset',type:asset.type,category:'otherMaterialAssets',ownership:ownerShares(asset),valueCents:asset.currentValueCents??asset.valueCents??0,liquidity:asset.liquidity??'illiquid',status:asset.status}));
  const liabilityItems=liabilities.map(liability=>({id:liability.id,name:liability.name??liability.id,type:liability.type,ownerId:liability.ownerId??'household',balanceCents:liabilityBalances[liability.id]??0,linkedAssetId:liability.linkedAssetId??null,immediatelyPayable:Boolean(liability.immediatelyPayable)})).filter(item=>item.balanceCents>0);
  const items=[...accountItems,...propertyItems,...otherItems],grossAssetsCents=sumCents(items.map(i=>i.valueCents)),totalLiabilitiesCents=sumCents(liabilityItems.map(i=>i.balanceCents)),totalNetWorthCents=grossAssetsCents-totalLiabilitiesCents;
  const liquidAssetsCents=sumCents(accountItems.filter(i=>['generalCash','emergencyReserve','dedicatedGoalFunds','taxableInvestments'].includes(i.category)).map(i=>i.valueCents)),immediateDebtCents=sumCents(liabilityItems.filter(l=>l.immediatelyPayable).map(l=>l.balanceCents));
  const investableNetWorthCents=sumCents(accountItems.filter(i=>['generalCash','taxableInvestments','retirementAccounts','otherFinancialAssets'].includes(i.category)).map(i=>i.valueCents));
  const propertyValueCents=sumCents(propertyItems.map(p=>p.valueCents)),propertyDebtCents=sumCents(propertyItems.flatMap(p=>p.linkedLiabilityIds).map(id=>liabilityBalances[id]??0)),realEstateEquityCents=propertyValueCents-propertyDebtCents;
  const ownership={};for(const item of items)for(const share of item.ownership){ownership[share.ownerId]??={grossAssetsCents:0,liabilitiesCents:0,netWorthCents:0};ownership[share.ownerId].grossAssetsCents+=Math.round(item.valueCents*share.share);}for(const liability of liabilityItems){ownership[liability.ownerId]??={grossAssetsCents:0,liabilitiesCents:0,netWorthCents:0};ownership[liability.ownerId].liabilitiesCents+=liability.balanceCents;}for(const row of Object.values(ownership))row.netWorthCents=row.grossAssetsCents-row.liabilitiesCents;
  return{assets:{items,byCategory:Object.fromEntries([...new Set(items.map(i=>i.category))].map(category=>[category,sumCents(items.filter(i=>i.category===category).map(i=>i.valueCents))]))},liabilities:{items:liabilityItems,byType:Object.fromEntries([...new Set(liabilityItems.map(i=>i.type))].map(type=>[type,sumCents(liabilityItems.filter(i=>i.type===type).map(i=>i.balanceCents))]))},grossAssetsCents,totalLiabilitiesCents,totalNetWorthCents,liquidNetWorthCents:liquidAssetsCents-immediateDebtCents,investableNetWorthCents,realEstateEquityCents,ownership:{household:{grossAssetsCents,totalLiabilitiesCents,netWorthCents:totalNetWorthCents},entities:ownership}};
}

export function buildCashFlowSnapshot({householdYear,propertyYear,goalFundingCents=0}){
  const income={militaryTaxableCents:householdYear.income.militaryTaxableCents,militaryNontaxableCents:householdYear.income.militaryNontaxableCents,physicianCents:householdYear.income.physicianCents,otherEmploymentCents:householdYear.income.otherEmploymentCents,pensionCents:householdYear.income.pensionCents,rentalDistributionsCents:propertyYear?.portfolio.cashFlowAfterFinancingCents??0,otherRecurringCents:0,oneTimeIncomeCents:0};
  income.totalCashIncomeCents=sumCents(Object.values(income));
  const taxes={federalIncomeTaxCents:householdYear.taxes.federalIncomeTaxCents,socialSecurityTaxCents:householdYear.taxes.socialSecurityTaxCents,medicareTaxCents:householdYear.taxes.medicareTaxCents,additionalMedicareTaxCents:householdYear.taxes.additionalMedicareTaxCents,totalTaxCents:householdYear.taxes.totalTaxCents,pretaxRetirementCents:householdYear.taxes.pretaxRetirementCents};
  const propertyPrimaryCents=sumCents((propertyYear?.propertyResults??[]).map(p=>p.primary?.totalCashCostCents??0)),rentalCostsCents=sumCents((propertyYear?.propertyResults??[]).map(p=>p.rental?(p.rental.operatingExpensesCents+p.rental.mortgageDebtServiceCents):0));
  const spending={essentialCents:householdYear.spending.essentialCents,discretionaryCents:householdYear.spending.discretionaryCents,oneTimeCents:householdYear.spending.oneTimeCents,ownerOccupiedPropertyCents:propertyPrimaryCents,rentalPropertyCents:rentalCostsCents,totalHouseholdSpendingCents:householdYear.spending.totalCents};
  const debt={interestCents:householdYear.debt.interestCents+sumCents((propertyYear?.propertyResults??[]).map(p=>p.mortgage?.interestCents??0)),principalCents:householdYear.debt.principalCents+sumCents((propertyYear?.propertyResults??[]).map(p=>p.mortgage?.principalCents??0)),debtServiceCents:sumCents(householdYear.debt.changes.map(d=>d.totalPaymentCents))+sumCents((propertyYear?.propertyResults??[]).map(p=>p.mortgage?.paymentsCents??0))};
  const allocation={reserveRestorationCents:householdYear.allocation.reserveRestorationCents,taxableInvestingCents:householdYear.allocation.taxableInvestmentCents,employeeRetirementCents:householdYear.allocation.employeeRetirementCents,employerGovernmentRetirementCents:householdYear.allocation.employerGovernmentRetirementCents,goalFundingCents,retainedCashCents:householdYear.allocation.retainedCashCents};
  const freeCashFlowCents=householdYear.income.cashCompensationCents-householdYear.taxes.totalTaxCents-householdYear.spending.totalCents-sumCents(householdYear.debt.changes.map(d=>d.totalPaymentCents))-householdYear.allocation.employeeRetirementCents;
  const assetTransactions={propertySaleGrossProceedsCents:sumCents((propertyYear?.cashSources??[]).filter(e=>e.type==='propertySalePrice').map(e=>e.amountCents)),releasedPropertyReservesCents:sumCents((propertyYear?.cashSources??[]).filter(e=>e.type==='propertyReserveRelease').map(e=>e.amountCents))};
  return{income,taxes,spending,debt,allocation,assetTransactions,freeCashFlowCents,definition:'Cash remaining after taxes, modeled spending, required debt service, and required one-time expenses, before optional investing and goals.'};
}

export function yearOverYearDeltas(current,previous){
  if(!previous)return null;const c=current.balanceSheet,p=previous.balanceSheet,cf=current.cashFlow,pf=previous.cashFlow;
  return{netWorthCents:c.totalNetWorthCents-p.totalNetWorthCents,liquidNetWorthCents:c.liquidNetWorthCents-p.liquidNetWorthCents,investableNetWorthCents:c.investableNetWorthCents-p.investableNetWorthCents,incomeCents:cf.income.totalCashIncomeCents-pf.income.totalCashIncomeCents,spendingCents:cf.spending.totalHouseholdSpendingCents-pf.spending.totalHouseholdSpendingCents,taxesCents:cf.taxes.totalTaxCents-pf.taxes.totalTaxCents,freeCashFlowCents:cf.freeCashFlowCents-pf.freeCashFlowCents,propertyEquityCents:c.realEstateEquityCents-p.realEstateEquityCents,debtCents:c.totalLiabilitiesCents-p.totalLiabilitiesCents,investmentBalanceCents:(c.assets.byCategory.taxableInvestments??0)+(c.assets.byCategory.retirementAccounts??0)-(p.assets.byCategory.taxableInvestments??0)-(p.assets.byCategory.retirementAccounts??0),goalFundingCents:cf.allocation.goalFundingCents-pf.allocation.goalFundingCents};
}
