import { orderEvents } from './event-order.js';

const categoryFor=type=>type.startsWith('career')||type.includes('promotion')?'career':type.startsWith('household')||type.startsWith('tax.')?'household':type.startsWith('property')||type.startsWith('asset.transfer')?'property':type.startsWith('goal')?'goal':'model';
const titleFor=item=>item.title??item.name??item.type.replaceAll('.',' ');

export function buildTimeline({plannedEvents=[],realizedEvents=[],decisions=[],goalHistories=[]}){
  const realizedByPlanned=new Map(realizedEvents.filter(e=>e.plannedEventId).map(e=>[e.plannedEventId,e]));
  const items=plannedEvents.map(event=>{const realized=realizedByPlanned.get(event.id);return{id:`timeline:planned:${event.id}`,type:event.type,category:categoryFor(event.type),target:event.target??event.propertyId??event.goalId??null,plannedDate:event.resolvedDate??event.date??null,realizedDate:realized?.actualDate??null,status:realized?.result??'planned',title:titleFor(event),summary:realized?.reason??`Planned ${titleFor(event)}.`,reason:realized?.reason??null,financialEffects:structuredClone(realized?.financialEffects??[]),sourceEventId:event.id,relatedDecisionId:null,relatedIds:{propertyId:event.propertyId??null,goalId:event.goalId??null,personId:event.personId??null},provenanceIds:structuredClone(event.provenanceIds??[])};});
  for(const event of realizedEvents.filter(e=>!plannedEvents.some(p=>p.id===e.plannedEventId)))items.push({id:`timeline:realized:${event.id}`,type:event.type,category:categoryFor(event.type),target:event.target??null,plannedDate:event.plannedDate??null,realizedDate:event.actualDate,status:event.result??'executed',title:titleFor(event),summary:event.reason,reason:event.reason,financialEffects:structuredClone(event.financialEffects??[]),sourceEventId:event.plannedEventId??null,relatedDecisionId:event.decisionId??null,relatedIds:structuredClone(event.relatedIds??{}),provenanceIds:structuredClone(event.provenanceIds??[])});
  for(const decision of decisions)items.push({id:`timeline:decision:${decision.id}`,type:decision.type??'decision',category:decision.category??(decision.goalId?'goal':'decision'),target:decision.target??decision.goalId??decision.intentId??null,plannedDate:decision.plannedDate??null,realizedDate:decision.actualDate??`${decision.evaluatedYear??decision.year}-12-31`,status:decision.status,title:decision.title??`Decision: ${decision.goalId??decision.intentId??decision.type??'model action'}`,summary:decision.explanation??decision.primaryBlocker?.explanation??decision.status,reason:decision.explanation??null,financialEffects:structuredClone(decision.financialEffects??[]),sourceEventId:decision.intentId??null,relatedDecisionId:decision.id,relatedIds:{goalId:decision.goalId??null,propertyId:decision.propertyId??null},provenanceIds:structuredClone(decision.provenanceIds??[])});
  for(const history of goalHistories)for(const entry of history.statusHistory??[])items.push({id:`timeline:goal:${history.goalId}:${entry.date}:${entry.status}`,type:'goal.status',category:'goal',target:history.goalId,plannedDate:history.plannedDate??null,realizedDate:entry.date,status:entry.status,title:`${history.name}: ${entry.status}`,summary:entry.reason,reason:entry.reason,financialEffects:[],sourceEventId:null,relatedDecisionId:entry.decisionId??null,relatedIds:{goalId:history.goalId},provenanceIds:structuredClone(history.provenanceIds??[])});
  return orderEvents(items.map(item=>({...item,effectiveDate:item.realizedDate??item.plannedDate??'9999-12-31'}))).map(({effectiveDate,...item})=>item);
}

export function plannedVsRealizedDelta(item){
  if(!item?.plannedDate||!item?.realizedDate)return null;const planned=Date.parse(`${item.plannedDate}T00:00:00Z`),realized=Date.parse(`${item.realizedDate}T00:00:00Z`),deltaDays=Math.round((realized-planned)/86400000);return{plannedDate:item.plannedDate,actualDate:item.realizedDate,deltaDays,deltaYears:Number((deltaDays/365.2425).toFixed(2)),timing:deltaDays===0?'onTime':deltaDays>0?'late':'early',reason:item.reason,relatedDecisionId:item.relatedDecisionId};
}

export function nextMajorMilestone({year,timeline,referenceAge}){
  const cutoff=`${year}-12-31`,candidate=timeline.filter(item=>(item.realizedDate??item.plannedDate)>cutoff&&['career','household','property','goal'].includes(item.category)).sort((a,b)=>(a.realizedDate??a.plannedDate).localeCompare(b.realizedDate??b.plannedDate))[0];if(!candidate)return null;const targetDate=candidate.realizedDate??candidate.plannedDate,targetYear=Number(targetDate.slice(0,4));return{timelineId:candidate.id,targetDate,targetYear,age:referenceAge+(targetYear-year),type:candidate.type,description:candidate.summary,status:candidate.status,yearsAway:targetYear-year};
}
