import { createAppStore, selectedAnnualResult, referenceAge } from '../js/v2/ui/app-state.js';
import { installRouting } from '../js/v2/ui/routing.js';
import { createNewModel, loadSavedModel, prepareImport, persistModel, serializeModelExport, runReadyModel, inspectModel } from '../js/v2/ui/model-entry.js';
import { overviewMarkup, overviewBodyMarkup, trajectorySvg, jumpCandidates } from '../js/v2/ui/overview.js';
import { timelineMarkup } from '../js/v2/ui/timeline-view.js';
import { modelViewMarkup, noModelMarkup, blockedProjectionMarkup, loadErrorMarkup } from '../js/v2/ui/readiness-view.js';
import { createDraftSession, editDraft, discardDraft, parseMoneyInput, canDeleteEntity, issuesForEditorField } from '../js/v2/ui/editor-state.js';
import { configureAccountBalance, configureReference, configurePartner, addGenericCareer, addJagTemplate, addPediatricsTemplate, addLiability, upsertHouseholdEvent, configureSpending, configureAssumption, configureExpectedTransfer, configureLongTermHome, SPENDING_CATEGORIES } from '../js/v2/ui/model-editor-actions.js';

const store=createAppStore(),view=document.querySelector('#app-view'),fileInput=document.querySelector('#model-file'),healthButton=document.querySelector('#health-button');
let simulationRunCount=0;
const toast=message=>{const item=document.createElement('div');item.className='toast';item.textContent=message;document.querySelector('#toast-region').append(item);setTimeout(()=>item.remove(),3600);};
function installModel(model,{loadState='VALID_MODEL',migration=null,save=false}={}){const inspection=inspectModel(model,{migration}),run=runReadyModel(model);simulationRunCount+=run.ran?1:0;if(save){const saved=persistModel(localStorage,model,run.manifest);if(!saved.ok)return toast('The model could not be saved. Your previous save was preserved.');}const selected=run.result?.years?.[0]?.year??null;store.setState({model,editor:createDraftSession(model),loadState,...inspection,simulation:run.result,manifest:run.manifest,selectedYear:selected,selectedTimelineItemId:null,error:run.error});}
function boot(){const loaded=loadSavedModel(localStorage);if(loaded.model){const run=runReadyModel(loaded.model);simulationRunCount+=run.ran?1:0;store.setState({...loaded,editor:createDraftSession(loaded.model),simulation:run.result,manifest:run.manifest,selectedYear:run.result?.years?.[0]?.year??null,error:run.error});}else store.setState({loadState:loaded.loadState,loadFailure:loaded.loaded});}
function render(){const state=store.getState(),row=selectedAnnualResult(state);for(const link of document.querySelectorAll('[data-route]'))link.toggleAttribute('aria-current',link.dataset.route===state.activeView);const health=state.health?.status??(state.loadState==='NO_MODEL'?'NO_MODEL':'INVALID'),healthClass=health==='READY'?'healthy':health==='READY_WITH_WARNINGS'||health==='INCOMPLETE_CONFIGURATION'?'warning':health==='NO_MODEL'?'neutral':'attention';healthButton.dataset.status=healthClass;document.querySelector('#shell-health').textContent=health==='NO_MODEL'?'No model':health.replaceAll('_',' ').toLowerCase();document.querySelector('#shell-period').textContent=row?`Age ${referenceAge(row,state.model)} · ${row.year}`:'Not configured';if(state.error){view.innerHTML=errorMarkup(state.error,state.manifest);return bind();}if(['BROKEN_MODEL','BROKEN_WITH_BACKUP'].includes(state.loadState)){view.innerHTML=loadErrorMarkup(state.loadState,state.loadFailure);return bind();}if(!state.model){view.innerHTML=noModelMarkup();return bind();}if(state.activeView==='model')view.innerHTML=modelViewMarkup(state);else if(!state.readiness?.ready)view.innerHTML=blockedProjectionMarkup(state.readiness);else if(state.activeView==='timeline')view.innerHTML=timelineMarkup({simulation:state.simulation,selectedTimelineItemId:state.selectedTimelineItemId,category:state.timelineCategory});else view.innerHTML=overviewMarkup({row,simulation:state.simulation,model:state.model});bind();}
function bind(){const state=store.getState(),slider=document.querySelector('#age-slider');if(slider){slider.addEventListener('input',event=>{store.setSelectedYear(event.target.value,{notify:false});refreshOverviewPeriod();});document.querySelector('#wealth-chart').innerHTML=trajectorySvg(state.simulation.years,state.selectedYear);document.querySelector('#age-jumps').innerHTML=jumpCandidates(state.simulation,state.model).map(item=>`<button type="button" data-jump-year="${item.year}">${item.label} · ${item.year}</button>`).join('');}for(const button of document.querySelectorAll('[data-action]'))button.addEventListener('click',()=>handleAction(button.dataset.action));for(const button of document.querySelectorAll('[data-jump-year]'))button.addEventListener('click',()=>store.setSelectedYear(button.dataset.jumpYear));for(const button of document.querySelectorAll('[data-timeline-filter]'))button.addEventListener('click',()=>store.setState({timelineCategory:button.dataset.timelineFilter}));for(const item of document.querySelectorAll('[data-timeline-id]')){const select=()=>store.selectTimeline(state.simulation.timeline.find(row=>row.id===item.dataset.timelineId));item.addEventListener('click',select);item.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select();}});}for(const button of document.querySelectorAll('[data-setup-section]'))button.addEventListener('click',()=>store.setState({setupSection:button.dataset.setupSection}));for(const control of document.querySelectorAll('[data-model-field]'))control.addEventListener('change',()=>commitField(control));applyFieldIssues(state.editor);for(const button of document.querySelectorAll('[data-editor-action]'))button.addEventListener('click',()=>handleEditorAction(button.dataset.editorAction));for(const button of document.querySelectorAll('[data-remove-career]'))button.addEventListener('click',()=>removeCareer(button.dataset.removeCareer));for(const button of document.querySelectorAll('[data-remove-debt]'))button.addEventListener('click',()=>removeDebt(button.dataset.removeDebt));for(const button of document.querySelectorAll('[data-reset-assumption]'))button.addEventListener('click',()=>updateEditor(d=>configureAssumption(d,{key:button.dataset.resetAssumption,reset:true}),`assumptions.${button.dataset.resetAssumption}`));}
function applyFieldIssues(editor){if(!editor)return;for(const control of document.querySelectorAll('[data-model-field]')){const issue=issuesForEditorField(editor,control.dataset.modelField).find(row=>row.severity!=='warning')??issuesForEditorField(editor,control.dataset.modelField)[0];if(!issue)continue;const id=`field-issue-${control.dataset.modelField.replace(/[^a-z0-9]+/gi,'-')}`;control.setAttribute('aria-invalid',issue.severity==='warning'?'false':'true');control.setAttribute('aria-describedby',[control.getAttribute('aria-describedby'),id].filter(Boolean).join(' '));const message=document.createElement('small');message.id=id;message.className=`field-issue ${issue.severity==='warning'?'warning':'error'}`;message.textContent=issue.message;control.closest('label')?.append(message);}}
function refreshOverviewPeriod(){const state=store.getState(),row=selectedAnnualResult(state),grid=document.querySelector('.overview-grid'),slider=document.querySelector('#age-slider');if(!row||!grid||!slider)return;grid.outerHTML=overviewBodyMarkup({row,simulation:state.simulation,model:state.model});const age=referenceAge(row,state.model);document.querySelector('.age-value strong').textContent=`Age ${age} · ${row.year}`;slider.value=String(row.year);slider.setAttribute('aria-valuetext',`Age ${age}, year ${row.year}`);document.querySelector('#shell-period').textContent=`Age ${age} · ${row.year}`;document.querySelector('#wealth-chart').innerHTML=trajectorySvg(state.simulation.years,state.selectedYear);}
function updateEditor(mutator,path='model'){const state=store.getState();if(!state.editor)return;try{store.setState({editor:editDraft(state.editor,mutator,{path})});}catch(error){toast(error.message);}}

function commitField(control){const field=control.dataset.modelField,value=control.type==='checkbox'?control.checked:control.value;updateEditor(draft=>{
  if(field==='simulationStartYear'||field==='simulationEndYear')draft.household[field]=value===''?null:Number(value);
  else if(field==='referenceName'||field==='referenceBirthDate'){const ref=draft.people.find(p=>p.isReference);configureReference(draft,{name:field==='referenceName'?value:ref.name,birthDate:field==='referenceBirthDate'?value:ref.birthDate});}
  else if(['partnerEnabled','partnerName','partnerBirthMode','partnerBirthDate','partnerAgeOffset'].includes(field)){const partner=draft.people.find(p=>!p.isReference)??{},mode=document.querySelector('[data-model-field="partnerBirthMode"]')?.value??(partner.birthDate?'date':'offset');configurePartner(draft,{enabled:field==='partnerEnabled'?value:partner.enabled,name:field==='partnerName'?value:partner.name,birthMode:field==='partnerBirthMode'?value:mode,birthDate:field==='partnerBirthDate'?value:partner.birthDate,ageOffset:field==='partnerAgeOffset'?Number(value):partner.ageOffsetFromReference});}
  else if(field.startsWith('account:'))configureAccountBalance(draft,field.split(':')[1],parseMoneyInput(value));
  else if(field.startsWith('accountOwner:'))draft.accounts.find(a=>a.id===field.split(':')[1]).ownerId=value;
  else if(field.startsWith('debtName:'))draft.liabilities.find(x=>x.id===field.split(':')[1]).name=value;
  else if(field.startsWith('debtOwner:'))draft.liabilities.find(x=>x.id===field.split(':')[1]).ownerId=value;
  else if(field.startsWith('debtBalance:')){const debt=draft.liabilities.find(x=>x.id===field.split(':')[1]),cents=parseMoneyInput(value);debt.openingBalanceCents=cents;debt.originalPrincipalCents=cents;}
  else if(field.startsWith('debtRate:'))draft.liabilities.find(x=>x.id===field.split(':')[1]).annualRate=Number(value)/100;
  else if(field.startsWith('debtPayment:')){const debt=draft.liabilities.find(x=>x.id===field.split(':')[1]),amountCents=parseMoneyInput(value)??0,start=draft.household.simulationStartYear,end=draft.household.simulationEndYear;debt.scheduledPayments=Number.isInteger(start)&&Number.isInteger(end)?Array.from({length:Math.max(0,end-start+1)},(_,i)=>({year:start+i,amountCents})):[];}
  else if(field.startsWith('careerPerson:'))draft.careers.find(x=>x.id===field.split(':')[1]).personId=value;
  else if(field.startsWith('careerRole:'))draft.careers.find(x=>x.id===field.split(':')[1]).role=value;
  else if(field.startsWith('careerStart:'))draft.careers.find(x=>x.id===field.split(':')[1]).startDate=value;
  else if(field.startsWith('careerEnd:'))draft.careers.find(x=>x.id===field.split(':')[1]).endDate=value;
  else if(field.startsWith('careerPay:'))draft.careers.find(x=>x.id===field.split(':')[1]).compensationRule.annualCents=parseMoneyInput(value);
  else if(field==='filingStatus')draft.household.filingStatus=value||null;
  else if(field==='locationKey')draft.household.locationKey=value||null;
  else if(field==='combinationDate')upsertHouseholdEvent(draft,{id:'household-combination',type:'household.combine',date:value});
  else if(field==='filingChangeDate')upsertHouseholdEvent(draft,{id:'filing-status-change',type:'tax.filingStatus.change',date:value,filingStatus:'marriedFilingJointly'});
  else if(field.startsWith('spending:')){const category=field.split(':')[1],classification=draft.spendingSchedules.find(s=>s.category===category)?.classification??SPENDING_CATEGORIES.find(row=>row[0]===category)[2];configureSpending(draft,{category,monthlyCents:parseMoneyInput(value),classification});}
  else if(field.startsWith('spendingClass:')){const schedule=draft.spendingSchedules.find(s=>s.category===field.split(':')[1]);if(schedule)schedule.classification=value;}
  else if(field.startsWith('assumption:'))configureAssumption(draft,{key:field.split(':')[1],value:Number(value)/100});
  else if(field==='reserveMonths')draft.policies.reserveMonths=Number(value);
  else if(field.startsWith('transfer'))updateTransferFromForm(draft,field,value);
  else if(field.startsWith('home'))updateHomeFromForm(draft,field,value);
},field);}

function updateTransferFromForm(draft,field,value){const current=draft.plannedEvents.find(e=>e.type==='asset.transfer.expected'),enabled=field==='transferEnabled'?value:Boolean(current),date=field==='transferDate'?value:current?.date??`${draft.household.simulationStartYear??2026}-01-01`,amount=field==='transferValue'?parseMoneyInput(value):current?.property?.estimatedValueCents??0,ownerId=field==='transferOwner'?value:current?.property?.ownership?.[0]?.ownerId??draft.people.find(p=>p.isReference).id,status=field==='transferStatus'?value:current?.property?.initialStatus??'other';configureExpectedTransfer(draft,{enabled,date,valueCents:amount,ownerId,status});}
function updateHomeFromForm(draft,field,value){const current=draft.goals.find(g=>g.type==='longTermHome'),enabled=field==='homeEnabled'?value:Boolean(current),year=draft.household.simulationEndYear??2050,startDate=field==='homeStart'?value:current?.preferredWindow?.startDate??`${year}-01-01`,endDate=field==='homeEnd'?value:current?.preferredWindow?.endDate??`${year}-12-31`,targetCents=field==='homeTarget'?parseMoneyInput(value):current?.target?.amountCents??0,locationKey=field==='homeLocation'?value:current?.home?.locationKey??'UNSET',downPaymentRate=field==='homeDownPayment'?Number(value)/100:current?.home?.downPaymentRate??.2,allowTaxableInvestments=field==='homeAllowBrokerage'?value:Boolean(current?.fundingPolicy?.allowTaxableInvestments);configureLongTermHome(draft,{enabled,targetCents,startDate,endDate,locationKey,downPaymentRate,allowTaxableInvestments});}

function handleEditorAction(action){const state=store.getState(),editor=state.editor;if(!editor)return;if(action==='discard'){if(!editor.dirty||confirm('Discard all unsaved model changes?'))store.setState({editor:discardDraft(editor)});return;}if(action==='save'){if(!editor.validation.valid)return toast('Fix the structural errors before saving.');const saved=persistModel(localStorage,editor.draft,state.manifest);if(!saved.ok)return toast('Save failed; the previous valid model was preserved.');installModel(editor.draft,{loadState:'VALID_MODEL'});toast(editor.readiness.ready?'Model saved and simulation refreshed.':'Progress saved. More setup is still needed.');return;}if(action==='add-debt')return updateEditor(d=>addLiability(d,{name:'Education debt',ownerId:d.people.find(p=>p.isReference).id,balanceCents:0,annualRate:0,scheduledPaymentCents:0,startYear:d.household.simulationStartYear,endYear:d.household.simulationEndYear}),'liabilities');if(action==='add-career')return updateEditor(d=>addGenericCareer(d,{personId:d.people.find(p=>p.isReference).id,role:'Employment',startDate:`${d.household.simulationStartYear??2026}-01-01`,endDate:`${(d.household.simulationEndYear??2050)+1}-01-01`,annualCents:0}),'careers');if(action==='preset-jag'&&confirm('Apply the editable Air Force JAG planning template to this draft?'))return updateEditor(d=>addJagTemplate(d,{personId:d.people.find(p=>p.isReference).id,startDate:`${d.household.simulationStartYear??2026}-07-01`,endDate:`${(d.household.simulationEndYear??2050)+1}-01-01`}),'careers');if(action==='preset-pediatrics'&&confirm('Apply the editable pediatrics planning template to this draft?'))return updateEditor(d=>addPediatricsTemplate(d,{personId:d.people.find(p=>!p.isReference&&p.enabled)?.id??d.people.find(p=>p.isReference).id,residencyStart:`${d.household.simulationStartYear??2026}-07-01`,attendingEnd:`${(d.household.simulationEndYear??2050)+1}-01-01`}),'careers');if(action==='remove-partner'){const person=editor.draft.people.find(p=>!p.isReference),check=canDeleteEntity(editor.draft,'people',person.id);if(!check.allowed)return toast(`Cannot remove: ${check.references.join(', ')}`);if(confirm('Remove the second person from this draft?'))updateEditor(d=>{d.people=d.people.filter(p=>p.id!==person.id);},'people');}}
function removeCareer(id){if(confirm('Remove this career stage from the draft?'))updateEditor(d=>{d.careers=d.careers.filter(c=>c.id!==id);delete d.retirementPolicies[id];},`careers.${id}`);}
function removeDebt(id){if(confirm('Remove this debt from the draft?'))updateEditor(d=>{d.liabilities=d.liabilities.filter(x=>x.id!==id);},`liabilities.${id}`);}

function handleAction(action){const state=store.getState();if(action==='create'){if(state.editor?.dirty&&!confirm('Replace this unsaved draft with a clean model?'))return;const created=createNewModel();installModel(created.model,{loadState:created.loadState,save:true});location.hash='#model';toast('A clean V2 model was created. Personal inputs remain unset.');}else if(action==='import'){if(state.editor?.dirty&&!confirm('Import another model and leave this unsaved draft?'))return;fileInput.click();}else if(action==='confirm-import'&&state.importCandidate){const migrated=state.importResult.result.migration?.migrated,candidate=state.importCandidate,ready=state.importResult.inspection.readiness.ready,migration=state.importResult.result.migration;store.setState({importCandidate:null,importResult:null});installModel(candidate,{loadState:migrated?'MIGRATED_MODEL':'VALID_MODEL',migration,save:true});location.hash=ready?'#overview':'#model';toast('Imported model validated and saved.');}else if(action==='cancel-import')store.setState({importCandidate:null,importResult:null});else if(action==='export'&&state.model){if(state.editor?.dirty)toast('Exporting the persisted model; unsaved draft changes are not included.');const result=serializeModelExport(state.model,state.manifest);if(!result.ok)return toast('Export failed validation.');const blob=new Blob([result.serialized],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='life-wealth-v2-model.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0);toast('Model export prepared.');}else if(action==='reset'&&confirm('Start over with a clean V2 model? Saved V2 configuration will be replaced.')){const created=createNewModel();installModel(created.model,{loadState:created.loadState,save:true});location.hash='#model';}}
fileInput.addEventListener('change',async()=>{const file=fileInput.files?.[0];fileInput.value='';if(!file)return;const prepared=prepareImport(await file.text());if(!prepared.result.ok)return toast(`Import failed: ${prepared.result.validation.errors[0]?.message??'invalid model'}`);store.setState({importCandidate:prepared.candidate,importResult:prepared,activeView:'model'});location.hash='#model';toast('Import validated. Review it before saving.');});
healthButton.addEventListener('click',()=>{location.hash='#model';});window.addEventListener('beforeunload',event=>{if(store.getState().editor?.dirty){event.preventDefault();event.returnValue='';}});store.subscribe(render);installRouting(route=>{const state=store.getState();if(route!=='model'&&state.editor?.dirty&&!confirm('Leave Model Setup with unsaved changes? Your draft will remain available.')){location.hash='#model';return;}store.setView(route);});try{boot();}catch(error){store.setState({error:{type:'SIMULATION_ERROR',message:error.message}});}
function errorMarkup(error,manifest){return `<section class="view start-layout"><div class="panel start-card"><p class="eyebrow">Simulation error</p><h1>V2 could not complete this run.</h1><p class="lede">${String(error.message??'An unexpected model error occurred.').replace(/[&<>]/g,'')}</p><span class="error-code">${error.type??'SIMULATION_ERROR'}</span>${manifest?.runId?`<p class="muted">Run ${manifest.runId}</p>`:''}<div class="button-row"><a class="button primary" href="#model">Inspect model</a></div></div></section>`;}
export const uiDiagnostics={getSimulationRunCount:()=>simulationRunCount,getState:()=>store.getState()};
