import test from 'node:test';import assert from 'node:assert/strict';
import {createLifePlan,applyLifePlanInput as apply,prepareLifePlanForExploration,refreshLifePlanFinanceStatus} from '../templates/life-plan.js';
import {createDraftSession} from '../ui/editor-state.js';
import {runReadyModel,serializeModelExport,prepareImport} from '../ui/model-entry.js';
import {lifeTimelineMarkup,compositionMarkup,planAtGlanceMarkup} from '../ui/life-story.js';
import {overviewMarkup} from '../ui/overview.js';
import {configureSpending,configureAccountBalance} from '../ui/model-editor-actions.js';
const ready=(partner=false)=>{const m=createLifePlan();for(const [k,v]of Object.entries({birthYear:2008,filingStatus:'single',partner:partner?'yes':'no',bah:'2400',zeroBalances:true}))apply(m,k,v);return m;};
test('Life Plan preserves unknown facts and preconfigures planning structure',()=>{const m=createLifePlan();assert.equal(createDraftSession(m).readiness.ready,false);assert(m.accounts.every(a=>a.openingBalanceCents===null));assert.equal(m.liabilities.length,0);assert.equal(m.people[1].enabled,false);assert.equal(m.careers[0].compensationRule.bahFallback,undefined);assert.equal(m.careers[0].compensationRule.locationKey,'UNSET');assert.equal(m.properties.length,0);assert.equal(m.extensions.production.optionalIntents.expectedPropertyTransfer.timing,null);assert.equal(m.goals[0].target.amountCents,150000000);assert.equal(m.spendingSchedules.reduce((n,s)=>n+s.amountCents,0),5460000);assert.equal(m.policies.reserveMonths,6);assert.deepEqual(m.extensions.production.template.education.filter(row=>row.personId==='reference').map(row=>row.stage),['Current high-school junior','UT Knoxville undergraduate (planned)','Law school']);assert.equal(m.extensions.production.template.currentChapter,'Current high-school junior → UT Knoxville → law school → Air Force JAG');});
test('Minimum inputs produce a finite, deterministic full-horizon projection with optional partner',()=>{for(const partner of [false,true]){const m=ready(partner);assert.equal(createDraftSession(m).readiness.ready,true);const a=runReadyModel(m),b=runReadyModel(m);assert.equal(a.error,null);assert.equal(a.result.years.length,78);assert.deepEqual(a.result.years,b.result.years);assert.equal(a.manifest.outputHash,b.manifest.outputHash);const walk=v=>{if(typeof v==='number')assert(Number.isFinite(v));else if(v&&typeof v==='object')Object.values(v).forEach(walk);};walk(a.result);assert.equal(a.result.years.at(-1).ages.reference,95);assert(a.result.years.every(r=>r.cashFlow.income.pensionCents===0));assert.equal(m.plannedEvents.filter(e=>e.type==='household.combine').length,partner?1:0);assert.equal(m.household.filingStatus,'single');}});
test('Setup accepts BAH before birth, preserves explicit balances and rejects invalid amounts',()=>{const m=createLifePlan();apply(m,'bah','2400');apply(m,'balance:general-cash','123.45');apply(m,'zeroBalances',true);assert.equal(m.accounts[0].openingBalanceCents,12345);assert.throws(()=>apply(m,'balance:general-cash','nonsense'));assert.throws(()=>apply(m,'balance:general-cash','-1'));apply(m,'bah','');assert.equal(m.careers[0].compensationRule.bahFallback,undefined);});
test('Life Plan spending edits replace the existing category without double counting',()=>{const m=ready();configureSpending(m,{category:'housing',monthlyCents:100000,classification:'essential'});assert.equal(m.spendingSchedules.filter(s=>s.category==='housing').length,1);});
test('Life Plan exports, imports and renders authoritative stories without mutation',()=>{const m=ready(true),r=runReadyModel(m),before=JSON.stringify(r.result),out=serializeModelExport(m,r.manifest);assert(out.ok);assert(prepareImport(out.serialized).result.ok);for(const row of [r.result.years[0],r.result.years[30],r.result.years.at(-1)]){const html=overviewMarkup({row,model:m,simulation:r.result});assert(html.includes('Your life timeline'));assert(html.includes('Where income comes from'));assert(html.includes('What you own and owe'));assert(!/NaN|Infinity/.test(html));assert(compositionMarkup(row).includes(String(row.year)));}assert(lifeTimelineMarkup(m,r.result,2026).includes('First possible'));assert(planAtGlanceMarkup(m).includes('pension'));assert.equal(JSON.stringify(r.result),before);});


test('Life Plan begins with the current-life chapter and still runs through age 95',()=>{const m=createLifePlan();apply(m,'birthYear',2009);assert.equal(m.household.simulationStartYear,2026);assert.equal(m.household.simulationEndYear,2104);const current=m.extensions.production.template.education[0];assert.equal(current.startYear,2026);assert.equal(current.stage,'Current high-school junior');});
test('one personal input creates a real exploratory projection with disclosed planning assumptions',()=>{const m=createLifePlan();apply(m,'birthYear',2009);prepareLifePlanForExploration(m);const session=createDraftSession(m),run=runReadyModel(m);assert.equal(session.readiness.ready,true);assert.equal(run.ran,true);assert.equal(run.error,null);assert.equal(run.result.invariants.passes,true);const finite=value=>{if(typeof value==='number')assert(Number.isFinite(value));else if(value&&typeof value==='object')Object.values(value).forEach(finite);};finite(run.result);assert.equal(run.result.years.at(-1).ages.reference,95);assert.equal(m.household.filingStatus,'single');assert.equal(m.provenance['planning.lifePlanFiling'].classification,'planningDefault');assert.equal(m.provenance['planning.lifePlanBah'].classification,'planningDefault');assert.equal(m.provenance['planning.lifePlanOpeningBalances'].classification,'planningDefault');assert.equal(m.provenance['planning.lifePlanDutyHome'].classification,'planningDefault');assert(m.accounts.every(account=>account.openingBalanceCents===0&&account.inputState==='planningAssumption'&&account.classification==='planningDefault'));assert.equal(m.extensions.production.template.exploration.currentFinancesStatus,'notAdded');assert.equal(m.extensions.production.template.exploration.debtStatus,'notAdded');assert.equal(m.liabilities.length,0);assert.equal(m.people[1].enabled,true);assert.equal(m.extensions.production.optionalIntents.expectedPropertyTransfer.timing,null);assert.equal(m.propertyIntents.length,1);assert.equal(m.extensions.production.template.propertyStrategy.automaticPurchaseSchedule,false);assert(run.result.timeline.some(item=>item.category==='property'));});
test('exploration does not fabricate facts and Overview discloses personalization state',()=>{const m=createLifePlan();apply(m,'birthYear',2009);prepareLifePlanForExploration(m);const run=runReadyModel(m),html=overviewMarkup({row:run.result.years[0],simulation:run.result,model:m});assert.equal(m.people[0].birthDate,null);assert.equal(m.household.locationKey,null);assert.equal(m.extensions.production.optionalIntents.expectedPropertyTransfer.timing,null);assert.equal(m.plannedEvents.some(event=>event.type==='tax.filingStatus.change'),false);assert.match(html,/Current finances not added yet/);assert.match(html,/Planning assumptions/);assert.match(html,/Current high-school junior/);assert.match(html,/UT Knoxville/);assert.match(html,/These are not|not presented as personal facts/);});
test('actual finance edits replace individual placeholders with user provenance without erasing unresolved accounts',()=>{const m=createLifePlan();apply(m,'birthYear',2009);prepareLifePlanForExploration(m);configureAccountBalance(m,'general-cash',12345);assert.equal(refreshLifePlanFinanceStatus(m),'partiallyAdded');assert.equal(m.accounts.find(account=>account.id==='general-cash').classification,'userEntered');assert.equal(m.accounts.find(account=>account.id==='general-cash').inputState,'entered');assert.equal(m.accounts.find(account=>account.id==='emergency-reserve').inputState,'planningAssumption');for(const account of m.accounts)configureAccountBalance(m,account.id,account.openingBalanceCents);assert.equal(refreshLifePlanFinanceStatus(m),'added');});
