import test from 'node:test';import assert from 'node:assert/strict';
import {createLifePlan,applyLifePlanInput as apply} from '../templates/life-plan.js';
import {createDraftSession} from '../ui/editor-state.js';
import {runReadyModel,serializeModelExport,prepareImport} from '../ui/model-entry.js';
import {lifeTimelineMarkup,compositionMarkup,planAtGlanceMarkup} from '../ui/life-story.js';
import {overviewMarkup} from '../ui/overview.js';
import {configureSpending} from '../ui/model-editor-actions.js';
const ready=(partner=false)=>{const m=createLifePlan();for(const [k,v]of Object.entries({birthYear:2008,filingStatus:'single',partner:partner?'yes':'no',bah:'2400',zeroBalances:true}))apply(m,k,v);return m;};
test('Life Plan preserves unknown facts and preconfigures planning structure',()=>{const m=createLifePlan();assert.equal(createDraftSession(m).readiness.ready,false);assert(m.accounts.every(a=>a.openingBalanceCents===null));assert.equal(m.liabilities.length,0);assert.equal(m.people[1].enabled,false);assert.equal(m.careers[0].compensationRule.bahFallback,undefined);assert.equal(m.careers[0].compensationRule.locationKey,'UNSET');assert.equal(m.properties.length,0);assert.equal(m.extensions.production.optionalIntents.expectedPropertyTransfer.timing,null);assert.equal(m.goals[0].target.amountCents,150000000);assert.equal(m.spendingSchedules.reduce((n,s)=>n+s.amountCents,0),5460000);assert.equal(m.policies.reserveMonths,6);});
test('Minimum inputs produce a finite, deterministic full-horizon projection with optional partner',()=>{for(const partner of [false,true]){const m=ready(partner);assert.equal(createDraftSession(m).readiness.ready,true);const a=runReadyModel(m),b=runReadyModel(m);assert.equal(a.error,null);assert.equal(a.result.years.length,78);assert.deepEqual(a.result.years,b.result.years);assert.equal(a.manifest.outputHash,b.manifest.outputHash);const walk=v=>{if(typeof v==='number')assert(Number.isFinite(v));else if(v&&typeof v==='object')Object.values(v).forEach(walk);};walk(a.result);assert.equal(a.result.years.at(-1).ages.reference,95);assert(a.result.years.every(r=>r.cashFlow.income.pensionCents===0));assert.equal(m.plannedEvents.filter(e=>e.type==='household.combine').length,partner?1:0);assert.equal(m.household.filingStatus,'single');}});
test('Setup accepts BAH before birth, preserves explicit balances and rejects invalid amounts',()=>{const m=createLifePlan();apply(m,'bah','2400');apply(m,'balance:general-cash','123.45');apply(m,'zeroBalances',true);assert.equal(m.accounts[0].openingBalanceCents,12345);assert.throws(()=>apply(m,'balance:general-cash','nonsense'));assert.throws(()=>apply(m,'balance:general-cash','-1'));apply(m,'bah','');assert.equal(m.careers[0].compensationRule.bahFallback,undefined);});
test('Life Plan spending edits replace the existing category without double counting',()=>{const m=ready();configureSpending(m,{category:'housing',monthlyCents:100000,classification:'essential'});assert.equal(m.spendingSchedules.filter(s=>s.category==='housing').length,1);});
test('Life Plan exports, imports and renders authoritative stories without mutation',()=>{const m=ready(true),r=runReadyModel(m),before=JSON.stringify(r.result),out=serializeModelExport(m,r.manifest);assert(out.ok);assert(prepareImport(out.serialized).result.ok);for(const row of [r.result.years[0],r.result.years[30],r.result.years.at(-1)]){const html=overviewMarkup({row,model:m,simulation:r.result});assert(html.includes('Your life timeline'));assert(html.includes('Where income comes from'));assert(html.includes('What you own and owe'));assert(!/NaN|Infinity/.test(html));assert(compositionMarkup(row).includes(String(row.year)));}assert(lifeTimelineMarkup(m,r.result,2026).includes('First possible'));assert(planAtGlanceMarkup(m).includes('pension'));assert.equal(JSON.stringify(r.result),before);});

