import test from 'node:test';
import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';
import { goldenIntegratedFixture } from './golden-integrated-fixture.js';
import { simulateFinancialLife } from '../model/financial-life.js';
import { orderEvents, WITHIN_YEAR_ORDER, MONTHLY_SUBPERIOD_RULES } from '../model/event-order.js';
import { buildBalanceSheetSnapshot, yearOverYearDeltas } from '../model/snapshots.js';
import { narrateYear } from '../model/explainability.js';

const run=()=>{const fixture=goldenIntegratedFixture();return{fixture,result:simulateFinancialLife(fixture.model,{data:fixture.data,taxTables:fixture.taxTables})};};

test('authoritative entry point returns one normalized 2026-2042 simulation',()=>{const {result}=run();assert.equal(result.metadata.authoritativeEntryPoint,'simulateFinancialLife');assert.equal(result.years.length,17);assert.equal(result.years[0].year,2026);assert.equal(result.years.at(-1).year,2042);});
test('authoritative simulation is deterministic and input immutable',()=>{const fixture=goldenIntegratedFixture(),before=structuredClone(fixture.model),a=simulateFinancialLife(fixture.model,{data:fixture.data,taxTables:fixture.taxTables}),b=simulateFinancialLife(fixture.model,{data:fixture.data,taxTables:fixture.taxTables});assert.deepEqual(fixture.model,before);assert.deepEqual(a,b);});
test('within-year order and monthly rollup rules are published',()=>{assert.equal(WITHIN_YEAR_ORDER[0],'carryForward');assert.equal(WITHIN_YEAR_ORDER.at(-1),'recordClosingState');assert.ok(MONTHLY_SUBPERIOD_RULES.monthlyUses.includes('mortgage amortization'));assert.equal(MONTHLY_SUBPERIOD_RULES.annualOutput,true);});
test('same-date events use phase, priority, sequence, and id instead of insertion order',()=>{const events=[{id:'z',type:'property.saleIntent',date:'2030-01-01',phase:130},{id:'b',type:'career.stage.start',date:'2030-01-01',phase:30,priority:2},{id:'a',type:'career.stage.start',date:'2030-01-01',phase:30,priority:2}];assert.deepEqual(orderEvents(events).map(e=>e.id),['a','b','z']);});
test('integrated fixture delays and later executes the duty-station purchase once',()=>{const {result}=run(),delayed=result.decisions.filter(d=>d.intentId==='duty-home-intent'&&d.status==='delayed'),executed=result.realizedEvents.filter(e=>e.plannedEventId==='duty-home-intent');assert.ok(delayed.length>=1);assert.equal(executed.length,1);assert.equal(executed[0].actualDate,'2031-01-01');});
test('planned and realized timeline entries link and expose a two-year delay',()=>{const {result}=run(),item=result.timeline.find(i=>i.id==='timeline:planned:duty-home-intent'),delta=result.timelineDeltas.find(d=>d.timelineId===item.id);assert.equal(item.realizedDate,'2031-01-01');assert.equal(delta.deltaYears,2);assert.equal(delta.timing,'late');});
test('legacy property decisions normalize their year without invalid timeline dates',()=>{const {result}=run(),decisions=result.timeline.filter(item=>item.id.startsWith('timeline:decision:decision:duty-home-intent:'));assert.ok(decisions.length>=3);assert.ok(decisions.every(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.realizedDate)));assert.equal(decisions.find(item=>item.id.endsWith(':2029:delayed')).realizedDate,'2029-12-31');});
test('balance sheet reports authoritative net-worth definitions',()=>{const row=run().result.years.at(-1);assert.equal(row.balanceSheet.totalNetWorthCents,row.balanceSheet.grossAssetsCents-row.balanceSheet.totalLiabilitiesCents);assert.ok(Number.isSafeInteger(row.balanceSheet.liquidNetWorthCents));assert.ok(Number.isSafeInteger(row.balanceSheet.investableNetWorthCents));assert.equal(row.balanceSheet.realEstateEquityCents,(row.balanceSheet.assets.byCategory.primaryResidence??0)+(row.balanceSheet.assets.byCategory.rentalProperties??0)-(row.balanceSheet.liabilities.byType.mortgage??0));});
test('joint property ownership aggregates the asset once and preserves shares',()=>{const {result}=run(),row=result.years.find(r=>r.year===2031),property=row.properties.find(p=>p.propertyId==='duty-home'),jointValue=property.equity.marketValueCents;assert.deepEqual(property.ownership.map(o=>o.share),[.5,.5]);assert.equal(row.balanceSheet.assets.items.filter(i=>i.id==='duty-home').length,1);assert.equal(row.balanceSheet.ownership.entities.jag.grossAssetsCents+row.balanceSheet.ownership.entities.physician.grossAssetsCents>=jointValue,true);});
test('cash-flow result uses the one documented free-cash-flow definition',()=>{const row=run().result.years.find(r=>r.year===2035),expected=row.income.cashCompensationCents-row.taxes.totalTaxCents-row.spending.totalCents-row.cashFlow.debt.debtServiceCents+row.cashFlow.debt.principalCents-sumPropertyDebtService(row)-row.cashFlow.allocation.employeeRetirementCents;assert.equal(typeof row.cashFlow.definition,'string');assert.ok(Number.isSafeInteger(row.cashFlow.freeCashFlowCents));assert.ok(row.cashFlow.definition.includes('before optional investing and goals'));assert.ok(Number.isSafeInteger(expected));});
function sumPropertyDebtService(row){return row.properties.reduce((sum,p)=>sum+(p.mortgage?.paymentsCents??0),0);}
test('goal uses authoritative balances and progresses from possible to comfortable execution',()=>{const {result}=run(),possible=result.years.find(r=>r.year===2037).goals[0],executed=result.years.find(r=>r.year===2040).goals[0];assert.equal(possible.status,'possible');assert.equal(possible.comfortable,false);assert.equal(executed.status,'executed');assert.equal(executed.comfortable,true);assert.ok(executed.fundingPlan.totalPlannedCents===executed.fundingPlan.requiredCents);});
test('home execution creates one normal property and one authoritative mortgage',()=>{const row=run().result.years.find(r=>r.year===2040);assert.equal(row.balanceSheet.assets.items.filter(i=>i.id==='long-term-home').length,1);assert.equal(row.liabilities.items.filter(i=>i.id==='long-term-home:mortgage').length,1);assert.equal(row.properties.find(p=>p.propertyId==='long-term-home').status,'primaryResidence');});
test('property state exposes rent, NOI, financing cash flow, debt, and reserve state',()=>{const row=run().result.years.find(r=>r.year===2036),rental=row.properties.find(p=>p.propertyId==='duty-home');assert.equal(rental.status,'rental');assert.ok(rental.rental.effectiveRentCents>0);assert.ok(rental.rental.netOperatingIncomeCents>rental.rental.cashFlowAfterFinancingCents);assert.equal(rental.equity.equityCents,rental.equity.marketValueCents-rental.equity.debtCents);assert.equal(rental.reserve.status,'adequate');});
test('unified decision ledger contains traceable property, conversion, and goal decisions',()=>{const {result}=run();assert.ok(result.decisions.some(d=>d.type==='propertyPurchase'));assert.ok(result.decisions.some(d=>d.type==='propertyConversion'));assert.ok(result.decisions.some(d=>d.type==='homeAffordability'&&d.rules.length));assert.ok(result.decisions.every(d=>d.id));});
test('warning API distinguishes projected data, reserve/FCF health, and unresolved choice',()=>{const {result}=run();assert.ok(result.warnings.some(w=>w.code==='PROJECTED_DATA_FALLBACK'&&w.provenanceIds.length));assert.ok(result.warnings.some(w=>w.code==='NEGATIVE_FREE_CASH_FLOW'));assert.ok(result.warnings.some(w=>w.code==='UNRESOLVED_USER_CHOICE'));assert.ok(result.warnings.every(w=>w.severity&&w.explanation));});
test('unresolved choice stays deterministic and unexecuted without an explicit fallback',()=>{const fixture=goldenIntegratedFixture();fixture.model.policies.unresolvedChoice={action:'leaveUnexecuted'};const result=simulateFinancialLife(fixture.model,{data:fixture.data,taxTables:fixture.taxTables}),decision=result.years.find(r=>r.year===2039).goals[0];assert.equal(decision.status,'needsUserChoice');assert.equal(result.years.find(r=>r.year===2039).properties.some(p=>p.propertyId==='long-term-home'),false);});
test('narrator returns at most four ranked, traceable, nonduplicate observations',()=>{const {result}=run();for(const row of result.years){assert.ok(row.narrator.length<=4);assert.equal(new Set(row.narrator.map(o=>o.signature)).size,row.narrator.length);assert.ok(row.narrator.every(o=>o.trace&&o.id));}const purchase=result.years.find(r=>r.year===2031);assert.ok(purchase.narrator.some(o=>o.type==='majorRealizedEvent'));});
test('narrator repetition penalty allows a material new event to outrank repeated drivers',()=>{const {result}=run(),transfer=result.years.find(r=>r.year===2032);assert.equal(transfer.narrator[0].type,'majorRealizedEvent');assert.ok(transfer.narrator.every(o=>o.signature));});
test('upcoming milestone and year-over-year delta APIs are precomputed',()=>{const {result}=run(),row=result.years.find(r=>r.year===2030);assert.ok(row.nextMajorMilestone);assert.ok(row.nextMajorMilestone.targetYear>=2030);assert.ok(result.years.find(r=>r.year===2031).deltas.netWorthCents!==0);assert.deepEqual(yearOverYearDeltas(result.years[1],result.years[0]),result.years[1].deltas);});
test('contribution-versus-growth separates employee, employer, and transfer inflows',()=>{const row=run().result.years.find(r=>r.year===2039),detail=row.contributionVsGrowth.financialAccounts;assert.ok(detail.employeeContributionsCents>0);assert.ok(detail.employerGovernmentContributionsCents>0);assert.ok(detail.growthCents>0);assert.equal(detail.closingBalanceCents,detail.openingBalanceCents+detail.employeeContributionsCents+detail.employerGovernmentContributionsCents+detail.transfersInCents+detail.growthCents-detail.withdrawalsCents-detail.transfersOutCents);});
test('external property transfer is an asset event, never earned income',()=>{const row=run().result.years.find(r=>r.year===2032),component=row.netWorthDecomposition.components.find(c=>c.type==='externalPropertyTransfer');assert.equal(component.economicEffectCents,20000000);assert.equal(row.income.records.some(r=>r.id.includes('expected-condo')),false);});
test('property sale proceeds remain asset transactions rather than income',()=>{const row=run().result.years.find(r=>r.year===2041);assert.ok(row.cashFlow.assetTransactions.propertySaleGrossProceedsCents>0);assert.equal(row.cashFlow.income.oneTimeIncomeCents,0);});
test('cross-module transfers and principal never create economic wealth',()=>{const {result}=run();for(const row of result.years){for(const component of row.netWorthDecomposition.components.filter(c=>['accountTransfers','principalTransfers','downPaymentTransfer','mortgagePrincipalReduction','propertyReserveTransfers'].includes(c.type)))assert.equal(component.economicEffectCents,0);}});
test('rental distributions, mortgage payments, taxes, and employer contributions are represented once',()=>{const row=run().result.years.find(r=>r.year===2036);assert.equal(row.cashFlow.income.rentalDistributionsCents,row.propertyPortfolio.cashFlowAfterFinancingCents);assert.equal(row.cashFlow.taxes.totalTaxCents,row.taxes.totalTaxCents);assert.equal(row.cashFlow.allocation.employerGovernmentRetirementCents,row.retirement?.employerGovernmentRetirementCents??row.cashFlow.allocation.employerGovernmentRetirementCents);assert.equal(row.balanceSheet.assets.items.filter(i=>i.category==='emergencyReserve').length,1);});
test('every integrated year satisfies all five reconciliation invariants',()=>{const {result}=run();assert.equal(result.invariants.passes,true);for(const row of result.years){assert.equal(row.reconciliation.cash.passes,true);assert.equal(row.reconciliation.balanceSheet.passes,true);assert.equal(row.reconciliation.netWorthChange.passes,true);assert.equal(row.reconciliation.propertyEquity.passes,true);assert.equal(row.reconciliation.goalFunding.passes,true);}});
test('integrated fixture remains comfortably fast for a household horizon',()=>{const fixture=goldenIntegratedFixture(),start=performance.now();simulateFinancialLife(fixture.model,{data:fixture.data,taxTables:fixture.taxTables});assert.ok(performance.now()-start<1000);});

test('snapshot helper does not double-count a jointly owned asset',()=>{const snapshot=buildBalanceSheetSnapshot({accounts:[],accountBalances:{},properties:[{id:'joint',name:'Joint',status:'primaryResidence',currentValueCents:10000,ownership:[{ownerId:'a',share:.5},{ownerId:'b',share:.5}],linkedLiabilityIds:[]}],assets:[],liabilities:[],liabilityBalances:{}});assert.equal(snapshot.grossAssetsCents,10000);assert.equal(snapshot.ownership.entities.a.grossAssetsCents,5000);assert.equal(snapshot.ownership.entities.b.grossAssetsCents,5000);});

test('standalone narrator honors an explicit maximum',()=>{const {result}=run(),row=result.years.find(r=>r.year===2040),observations=narrateYear(row,result.years.find(r=>r.year===2039),{maxObservations:2});assert.ok(observations.length<=2);});
