import test from 'node:test';
import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';
import {
  createBaselineModel,validateProductionModel,assessSimulationReadiness,auditModel,modelHealthSummary,
  validateModelDocument,canonicalStringify,serializeModel,deserializeModel,modelFingerprint,stableFingerprint,
  migrateModelDocument,createMemoryStorage,saveModel,loadModel,exportModel,importModel,STORAGE_KEYS,
  buildDataManifest,simulateReproducibly,replaySimulation,OUTPUT_CONTRACT_VERSION,FINAL_MODEL_VERSION,SCHEMA_VERSION
} from '../index.js';
import { goldenProductionFixture,priorSchemaFixture } from './golden-production-fixture.js';

const fixture=options=>goldenProductionFixture(options);
const configured=()=>fixture().model;
const errorCodes=result=>result.errors.map(item=>item.code);

test('production baseline is structurally valid but intentionally incomplete',()=>{const model=createBaselineModel(),validation=validateProductionModel(model),readiness=assessSimulationReadiness(model);assert.equal(validation.valid,true);assert.equal(readiness.status,'INCOMPLETE_CONFIGURATION');assert.ok(readiness.missing.some(x=>x.code==='REFERENCE_BIRTH_REQUIRED'));assert.equal(model.modelVersion,FINAL_MODEL_VERSION);});
test('production baseline contains no golden-fixture personal assumptions',()=>{const text=JSON.stringify(createBaselineModel());for(const forbidden of ['12000000','TX-NORTH-DALLAS','FIXTURE-AFB','duty-home','long-term-home-goal','jag-career','physician401k'])assert.equal(text.includes(forbidden),false);});
test('intentionally unset personal fields survive baseline creation',()=>{const model=createBaselineModel();assert.equal(model.people[0].birthDate,null);assert.equal(model.household.simulationStartYear,null);assert.equal(model.accounts.every(account=>account.openingBalanceCents===null),true);assert.equal(model.extensions.production.optionalIntents.marriage,null);});
test('readiness becomes ready for the configured final fixture',()=>{const result=assessSimulationReadiness(configured());assert.equal(result.ready,true);assert.equal(result.missing.length,0);});
test('document structure and simulation readiness are distinct',()=>{const model=createBaselineModel();assert.equal(validateProductionModel(model).valid,true);assert.equal(assessSimulationReadiness(model).ready,false);});

test('dangling account and liability owners return structured paths',()=>{const model=configured();model.accounts[0].ownerId='missing';model.liabilities[0].ownerId='missing';const result=validateProductionModel(model);assert.ok(errorCodes(result).includes('ACCOUNT_OWNER_DANGLING'));assert.ok(errorCodes(result).includes('LIABILITY_OWNER_DANGLING'));assert.ok(result.errors.every(x=>x.path&&x.severity==='error'));});
test('dangling property mortgage link is rejected',()=>{const model=configured();model.properties=[{id:'bad-home',ownership:[{ownerId:'jag',share:1}],currentValueCents:10000,linkedLiabilityIds:['missing']}];assert.ok(errorCodes(validateProductionModel(model)).includes('PROPERTY_MORTGAGE_DANGLING'));});
test('ownership validates owners, shares, and exact total',()=>{const model=configured();model.propertyIntents[0].ownership=[{ownerId:'missing',share:.6},{ownerId:'physician',share:.5}];const codes=errorCodes(validateProductionModel(model));assert.ok(codes.includes('OWNER_DANGLING'));assert.ok(codes.includes('OWNERSHIP_TOTAL_INVALID'));});
test('goal funding account and sale references validate',()=>{const model=configured();model.goals[0].fundingPolicy.permittedAccountIds=['missing'];model.goals[0].fundingPolicy.permittedPropertySaleIds=['missing'];const codes=errorCodes(validateProductionModel(model));assert.ok(codes.includes('GOAL_ACCOUNT_DANGLING'));assert.ok(codes.includes('GOAL_PROPERTY_DANGLING'));});
test('career and event entity references validate',()=>{const model=configured();model.careers[0].personId='missing';model.plannedEvents.push({id:'bad-event',type:'property.saleIntent',propertyId:'missing',date:'2030-01-01'});const codes=errorCodes(validateProductionModel(model));assert.ok(codes.includes('CAREER_PERSON_DANGLING'));assert.ok(codes.includes('EVENT_PROPERTY_DANGLING'));});
test('duplicate IDs are rejected without relying on insertion order',()=>{const model=configured();model.accounts.push(structuredClone(model.accounts[0]));assert.ok(errorCodes(validateProductionModel(model)).includes('DUPLICATE_ID'));});
test('invalid dates and windows produce field-addressable errors',()=>{const model=configured();model.careers[0].startDate='nope';model.goals[0].earliestDesiredDate='2045-01-01';model.goals[0].latestAcceptableDate='2040-01-01';const result=validateProductionModel(model);assert.ok(errorCodes(result).includes('START_DATE_INVALID'));assert.ok(errorCodes(result).includes('GOAL_WINDOW_INVALID'));});
test('asset lifecycle and service retirement dates validate chronologically',()=>{const model=configured();model.properties=[{id:'bad-order',ownership:[{ownerId:'jag',share:1}],currentValueCents:10000,linkedLiabilityIds:[],status:'sold',acquisitionDate:'2035-01-01',realizedSaleDate:'2034-01-01',statusHistory:[{effectiveDate:'2035-01-01',previousStatus:'planned',newStatus:'primaryResidence'},{effectiveDate:'2034-01-01',previousStatus:'rental',newStatus:'sold'}]}];model.serviceHistories[0].retirementDate='2020-01-01';const codes=errorCodes(validateProductionModel(model));assert.ok(codes.includes('PROPERTY_DISPOSITION_ORDER_INVALID'));assert.ok(codes.includes('STATUS_HISTORY_ORDER_INVALID'));assert.ok(codes.includes('STATUS_TRANSITION_INVALID'));assert.ok(codes.includes('SERVICE_RETIREMENT_ORDER_INVALID'));});
test('financial structural limits reject impossible values',()=>{const model=configured();model.propertyIntents[0].mortgageTermMonths=-1;model.propertyIntents[0].operations.vacancyRate=1.1;model.propertyIntents[0].downPaymentCents=model.propertyIntents[0].expectedPriceCents+1;const codes=errorCodes(validateProductionModel(model));assert.ok(codes.includes('TERM_INVALID'));assert.ok(codes.includes('RATE_INVALID'));assert.ok(codes.includes('DOWN_PAYMENT_EXCEEDS_PRICE'));});
test('negative free cash flow is a result, not a schema error',()=>{const model=configured();model.extensions.expectedFinancialOutcome={freeCashFlowCents:-100};assert.equal(validateProductionModel(model).valid,true);});

test('valid official provenance passes and fake official provenance fails',()=>{const model=createBaselineModel();model.provenance.real={id:'real',classification:'researchedOfficial',unit:'USD',source:{title:'Agency data',url:'https://example.gov/data'},sourceType:'officialGovernment',effectiveYear:2026,editable:false};assert.equal(validateProductionModel(model).valid,true);model.provenance.fake={id:'fake',classification:'researchedOfficial',unit:'USD',source:{title:'Guess',url:'model://guess'},sourceType:'planning',effectiveYear:2026,editable:true};assert.ok(errorCodes(validateProductionModel(model)).includes('OFFICIAL_PROVENANCE_INVALID'));});
test('projected and user-entered provenance retain their classifications',()=>{const model=createBaselineModel();model.provenance.projected={id:'projected',classification:'projected',unit:'rate',source:{title:'Projection',url:'model://projection'},sourceType:'planning',effectiveYear:2040,editable:true,state:'projected'};model.provenance.user={id:'user',classification:'userEntered',unit:'USD',source:{title:'User input',url:'model://user'},sourceType:'user',effectiveYear:2026,editable:true};const result=validateProductionModel(model);assert.equal(result.valid,true);assert.equal(model.provenance.user.classification,'userEntered');});
test('derived provenance requires a trace rule',()=>{const model=createBaselineModel();model.provenance.derived={id:'derived',classification:'derived',unit:'USD',source:{title:'Calculation',url:'model://derived'},sourceType:'model',effectiveYear:2026,editable:false};assert.ok(errorCodes(validateProductionModel(model)).includes('DERIVATION_TRACE_REQUIRED'));model.provenance.derived.ruleId='sum.accounts';assert.equal(validateProductionModel(model).valid,true);});
test('provenance audit separates defaults, derived fields, and unset fields',()=>{const audit=auditModel(createBaselineModel());assert.equal(audit.counts.planningDefault,4);assert.ok(audit.counts.unset>=6);assert.ok(audit.details.derived.includes('household.simulationEndYear'));});

test('canonical serialization round trip is lossless and immutable',()=>{const model=configured(),before=structuredClone(model),serialized=serializeModel(model),round=deserializeModel(serialized);assert.equal(round.ok,true);assert.deepEqual(round.model,model);assert.deepEqual(model,before);});
test('canonical representation ignores object key insertion order and JSON whitespace',()=>{const a={z:1,a:{y:2,x:3}},b={a:{x:3,y:2},z:1};assert.equal(canonicalStringify(a),canonicalStringify(b));assert.equal(stableFingerprint(a),stableFingerprint(b));});
test('identity collections canonicalize by ID while ordered financial arrays remain ordered',()=>{const model=configured(),reordered=structuredClone(model);reordered.accounts.reverse();assert.equal(modelFingerprint(model),modelFingerprint(reordered));assert.notEqual(canonicalStringify({brackets:[[1,.2],[2,.3]]}),canonicalStringify({brackets:[[2,.3],[1,.2]]}));});
test('nonfinancial save timestamp and UI formatting do not change model fingerprint',()=>{const model=configured(),copy=structuredClone(model);copy.savedAt='2099-01-01T00:00:00.000Z';copy.extensions.ui={format:'compact'};assert.equal(modelFingerprint(model),modelFingerprint(copy));});
test('salary, mortgage rate, birth date, event date, home target, and return each change fingerprint',()=>{const original=configured(),base=modelFingerprint(original),mutations=[m=>m.careers[0].compensationRule.annualCents++,m=>m.propertyIntents[0].mortgageRate+=.001,m=>m.people[0].birthDate='2004-04-16',m=>m.plannedEvents[0].date='2033-02-01',m=>m.goals[0].target.amountCents++,m=>m.accounts[0].annualReturn+=.001];for(const mutate of mutations){const model=structuredClone(original);mutate(model);assert.notEqual(modelFingerprint(model),base);}});

test('current migration is a deterministic no-op',()=>{const model=configured(),result=migrateModelDocument(model);assert.equal(result.ok,true);assert.equal(result.migrated,false);assert.deepEqual(result.normalizedModel,model);});
test('supported prior schema migrates sequentially and preserves user data and provenance',()=>{const prior=priorSchemaFixture(),result=migrateModelDocument(prior);assert.equal(result.ok,true);assert.equal(result.migrated,true);assert.deepEqual(result.normalizedModel.futurePreservedField,{keep:true});assert.equal(result.normalizedModel.accounts[0].openingBalanceCents,prior.accounts[0].openingBalanceCents);assert.deepEqual(result.normalizedModel.provenance,prior.provenance);assert.ok(result.warnings.some(x=>x.code==='MIGRATION_DEFAULT_INTRODUCED'));});
test('unsupported future and malformed migrations fail without destroying input',()=>{const future={...configured(),schemaVersion:'99.0.0',keep:true},a=migrateModelDocument(future),b=migrateModelDocument(null);assert.equal(a.ok,false);assert.equal(a.normalizedModel.keep,true);assert.equal(b.ok,false);});

test('persistence save/load uses isolated V2 namespace and preserves model',()=>{const storage=createMemoryStorage(),model=configured(),saved=saveModel(storage,model),loaded=loadModel(storage);assert.equal(saved.ok,true);assert.equal(loaded.ok,true);assert.deepEqual(loaded.model,model);assert.deepEqual(storage.keys(),[STORAGE_KEYS.primary]);assert.ok(STORAGE_KEYS.primary.startsWith('lifeWealth:v2:'));});
test('second valid save creates recoverable backup',()=>{const storage=createMemoryStorage(),a=configured(),b=structuredClone(a);b.assumptions.propertyAppreciationRate=.04;saveModel(storage,a);const saved=saveModel(storage,b);assert.equal(saved.backupCreated,true);assert.notEqual(storage.getItem(STORAGE_KEYS.backup),null);assert.deepEqual(loadModel(storage).model,b);});
test('invalid save cannot overwrite a valid stored model',()=>{const storage=createMemoryStorage(),model=configured();saveModel(storage,model);const original=storage.getItem(STORAGE_KEYS.primary),bad=structuredClone(model);bad.accounts[0].ownerId='missing';const result=saveModel(storage,bad);assert.equal(result.ok,false);assert.equal(storage.getItem(STORAGE_KEYS.primary),original);});
test('malformed saved JSON returns recovery metadata without inventing a model',()=>{const storage=createMemoryStorage({[STORAGE_KEYS.primary]:'{bad',[STORAGE_KEYS.backup]:'backup'}),result=loadModel(storage);assert.equal(result.ok,false);assert.equal(result.model,null);assert.equal(result.recovery.backupAvailable,true);});

test('export/import is lossless, validated, and never persists automatically',()=>{const model=configured(),exported=exportModel(model,{pretty:true}),imported=importModel(exported.serialized);assert.equal(exported.ok,true);assert.equal(imported.ok,true);assert.deepEqual(imported.normalizedModel,model);assert.equal(imported.persisted,false);});
test('untrusted imports reject malformed, oversized, unsafe, and dangling content',()=>{assert.equal(importModel('{no').ok,false);assert.equal(importModel(' '.repeat(2_000_001)).ok,false);assert.equal(importModel('{"__proto__":{"x":1}}').ok,false);const bad=configured();bad.accounts[0].ownerId='missing';assert.equal(importModel(JSON.stringify(bad)).ok,false);});
test('unsupported import schema fails safely',()=>{const model=configured();model.schemaVersion='99.0.0';const result=importModel(JSON.stringify(model));assert.equal(result.ok,false);assert.ok(result.validation.errors.some(x=>x.code==='MIGRATION_PATH_MISSING'));});

test('data manifest and run manifest identify exact versions and fingerprints',()=>{const {model,data,taxTables}=fixture(),dataManifest=buildDataManifest(data,taxTables),{manifest}=simulateReproducibly(model,{data,taxTables,generatedAt:'2000-01-01T00:00:00.000Z'});assert.equal(manifest.schemaVersion,SCHEMA_VERSION);assert.equal(manifest.modelVersion,FINAL_MODEL_VERSION);assert.equal(manifest.outputContractVersion,OUTPUT_CONTRACT_VERSION);assert.equal(manifest.inputHash,modelFingerprint(model));assert.equal(manifest.dataFingerprint,dataManifest.fingerprint);assert.equal(manifest.deterministic,true);});
test('identical replay matches all fingerprints and output',()=>{const {model,data,taxTables}=fixture(),run=simulateReproducibly(model,{data,taxTables,generatedAt:'2000-01-01T00:00:00.000Z'}),replay=replaySimulation({model,data,taxTables,expectedManifest:run.manifest});assert.equal(replay.status,'MATCH');assert.equal(replay.matches,true);assert.deepEqual(replay.checks,{inputFingerprint:true,dataFingerprint:true,outputFingerprint:true});});
test('replay detects changed model and normalized data',()=>{const {model,data,taxTables}=fixture(),run=simulateReproducibly(model,{data,taxTables,generatedAt:'2000-01-01T00:00:00.000Z'}),changedModel=structuredClone(model);changedModel.assumptions.propertyAppreciationRate=.04;const a=replaySimulation({model:changedModel,data,taxTables,expectedManifest:run.manifest}),changedTables=structuredClone(taxTables);changedTables[2026].standardDeduction.single++;const b=replaySimulation({model,data,taxTables:changedTables,expectedManifest:run.manifest});assert.equal(a.checks.inputFingerprint,false);assert.equal(b.checks.dataFingerprint,false);});
test('unsupported engine/model replay is reported rather than approximated',()=>{const {model,data,taxTables}=fixture(),run=simulateReproducibly(model,{data,taxTables,generatedAt:'2000-01-01T00:00:00.000Z'});const expected={...run.manifest,engineVersion:'v1'};assert.equal(replaySimulation({model,data,taxTables,expectedManifest:expected}).status,'UNSUPPORTED_VERSION');});

test('long horizon reaches reference age 95 and remains deterministic',()=>{const {model,data,taxTables}=fixture({throughAge95:true}),a=simulateReproducibly(model,{data,taxTables,generatedAt:'2000-01-01T00:00:00.000Z'}),b=simulateReproducibly(model,{data,taxTables,generatedAt:'2000-01-01T00:00:00.000Z'});assert.equal(a.result.years.length,74);assert.equal(a.result.years.at(-1).ages.jag,95);assert.equal(a.manifest.outputHash,b.manifest.outputHash);});
test('every long-horizon year reconciles without asset or liability duplication',()=>{const {model,data,taxTables}=fixture({throughAge95:true}),{result}=simulateReproducibly(model,{data,taxTables});assert.equal(result.invariants.passes,true);for(const year of result.years){assert.ok(Object.values(year.reconciliation).every(x=>x.passes));assert.equal(new Set(year.balanceSheet.assets.items.map(x=>x.id)).size,year.balanceSheet.assets.items.length);assert.equal(new Set(year.balanceSheet.liabilities.items.map(x=>x.id)).size,year.balanceSheet.liabilities.items.length);}});
test('long-horizon performance remains comfortably interactive',()=>{const {model,data,taxTables}=fixture({throughAge95:true}),start=performance.now();simulateReproducibly(model,{data,taxTables});assert.ok(performance.now()-start<1500);});
test('timeline and realized-event history stay stable across long replays',()=>{const {model,data,taxTables}=fixture({throughAge95:true}),a=simulateReproducibly(model,{data,taxTables,generatedAt:'x'}).result,b=simulateReproducibly(model,{data,taxTables,generatedAt:'x'}).result;assert.deepEqual(a.timeline,b.timeline);assert.deepEqual(a.realizedEvents,b.realizedEvents);});

test('model health describes configuration quality, not financial success',()=>{const health=modelHealthSummary(createBaselineModel());assert.equal(health.modelHealthOnly,true);assert.equal(health.status,'INCOMPLETE_CONFIGURATION');assert.equal('netWorth' in health,false);});
test('final pipeline preserves the authoritative financial result',()=>{const {model,data,taxTables}=fixture(),storage=createMemoryStorage(),run=simulateReproducibly(model,{data,taxTables,generatedAt:'2000-01-01T00:00:00.000Z'}),exported=exportModel(model,{dataManifest:run.manifest.dataManifest}),imported=importModel(exported.serialized);assert.equal(saveModel(storage,imported.normalizedModel).ok,true);const loaded=loadModel(storage),replay=replaySimulation({model:loaded.model,data,taxTables,expectedManifest:run.manifest});assert.equal(replay.matches,true);assert.equal(replay.manifest.outputHash,run.manifest.outputHash);});
