import test from 'node:test';
import assert from 'node:assert/strict';
import {createBaselineModel,assessSimulationReadiness,validateProductionModel,simulateFinancialLife} from '../index.js';
import {runReadyModel} from '../ui/model-entry.js';
import {buildRuntimeInputs} from '../ui/runtime-data.js';
function model(){const m=createBaselineModel();m.people[0].birthDate='2000-01-01';Object.assign(m.household,{simulationStartYear:2026,simulationEndYear:2026,filingStatus:'single'});for(const a of m.accounts)a.openingBalanceCents=0;m.careers=[{id:'military',personId:'reference',careerType:'military',role:'Military',startDate:'2026-01-01',endDate:'2027-01-01',compensationRule:{locationKey:'TEST',bahFallback:{monthlyCents:100000,baseYear:2026}}}];m.serviceHistories=[{id:'service',personId:'reference',periods:[{startDate:'2026-01-01',endDate:'2027-01-01'}],payGradeHistory:[{effectiveDate:'2026-01-01',grade:'O-2'}]}];return m;}
test('missing service is schema valid, incomplete, structured and UI does not simulate',()=>{const m=model();m.serviceHistories=[];assert.equal(validateProductionModel(m).valid,true);const r=assessSimulationReadiness(m);assert.equal(r.status,'INCOMPLETE_CONFIGURATION');assert.ok(r.missing.some(i=>i.code==='MILITARY_SERVICE_TIMELINE_REQUIRED'&&i.entityId==='military'&&i.setupSection==='careers'));assert.equal(runReadyModel(m).ran,false);assert.equal(runReadyModel(m).error,null);});
test('missing BAH is incomplete without fabrication',()=>{const m=model();delete m.careers[0].compensationRule.bahFallback;const before=JSON.stringify(m);assert.equal(validateProductionModel(m).valid,true);assert.ok(assessSimulationReadiness(m).missing.some(i=>i.code==='MILITARY_HOUSING_ALLOWANCE_REQUIRED'));assert.equal(runReadyModel(m).ran,false);assert.equal(JSON.stringify(m),before);});
test('complete military projection is READY and simulates without retirement policy',()=>{const m=model();assert.equal(assessSimulationReadiness(m).status,'READY');const r=runReadyModel(m);assert.equal(r.ran,true);assert.equal(r.error,null);assert.equal(r.result.years.length,1);});
test('explicit zero override resolves BAH but zero fallback does not',()=>{const m=model();m.careers[0].compensationRule.bahFallback.monthlyCents=0;assert.equal(assessSimulationReadiness(m).ready,false);m.careers[0].compensationRule.bahOverride={monthlyCents:0};assert.equal(assessSimulationReadiness(m).ready,true);assert.equal(runReadyModel(m).ran,true);});
test('exact official BAH data resolves every active year when explicitly supplied',()=>{const m=model();delete m.careers[0].compensationRule.bahFallback;const inputs=buildRuntimeInputs(m);inputs.data.bah.official={'2026:TEST:O-2:without':{monthlyCents:100000,provenanceId:'test'}};assert.equal(assessSimulationReadiness(m,inputs).ready,true);assert.equal(simulateFinancialLife(m,inputs).years.length,1);assert.equal(assessSimulationReadiness(m).ready,false);});
test('generic and physician careers do not require military configuration',()=>{for(const type of ['genericEmployment','physicianAttending']){const m=model();m.serviceHistories=[];m.careers[0].careerType=type;m.careers[0].compensationRule={annualCents:1000000,case:'baseline',baseYear:2026};assert.equal(assessSimulationReadiness(m).ready,true);assert.equal(runReadyModel(m).ran,true);}});
test('disabled military person and out-of-period military career do not require inputs',()=>{const m=model();m.serviceHistories=[];m.careers[0].personId='partner';delete m.careers[0].compensationRule.bahFallback;assert.equal(assessSimulationReadiness(m).ready,true);assert.equal(runReadyModel(m).ran,true);m.careers[0].personId='reference';m.careers[0].startDate='2027-01-01';m.careers[0].endDate='2028-01-01';assert.equal(assessSimulationReadiness(m).ready,true);assert.equal(runReadyModel(m).ran,true);});
test('missing or unsupported active pay grade surfaces before simulation',()=>{for(const grades of [[],[{effectiveDate:'2026-01-01',grade:'UNSET'}]]){const m=model();m.serviceHistories[0].payGradeHistory=grades;assert.ok(assessSimulationReadiness(m).missing.some(i=>i.code==='MILITARY_PAY_GRADE_REQUIRED'));assert.equal(runReadyModel(m).ran,false);}});
