import test from 'node:test';import assert from 'node:assert/strict';
import {createBaselineModel,createExamplePlan,assessSimulationReadiness,validateProductionModel,simulateFinancialLife,canonicalStringify,resultFingerprint} from '../index.js';
import {buildRuntimeInputs} from '../ui/runtime-data.js';import {buildCashFlowSnapshot} from '../model/snapshots.js';
function model(maintenance=0){const m=createBaselineModel();m.people[0].birthDate='2000-01-01';Object.assign(m.household,{simulationStartYear:2026,simulationEndYear:2026,filingStatus:'single'});for(const a of m.accounts){a.openingBalanceCents=a.id==='general-cash'?20000000:0;a.annualReturn=0;}m.careers=[{id:'work',personId:'reference',careerType:'genericEmployment',role:'Employment',startDate:'2026-01-01',endDate:'2027-01-01',compensationRule:{annualCents:15000000,baseYear:2026}}];const p=structuredClone(createExamplePlan().propertyIntents[0]);Object.assign(p,{desiredYear:2026,earliestAcceptableYear:2026,latestAcceptableYear:2026,ownership:[{ownerId:'reference',share:1}]});p.operations.baseYear=2026;p.operations.primaryMaintenanceCents=maintenance;m.propertyIntents=[p];return m;}
const run=m=>simulateFinancialLife(m,buildRuntimeInputs(m));
test('zero versus $1000 primary maintenance changes cash FCF operations accounts and net worth exactly once',()=>{const a=model(),b=model(100000);for(const m of [a,b]){assert.equal(validateProductionModel(m).valid,true);assert.equal(assessSimulationReadiness(m).ready,true);}const ra=run(a),rb=run(b),x=ra.years[0],y=rb.years[0];assert.equal(y.cashFlow.freeCashFlowCents-x.cashFlow.freeCashFlowCents,-100000);assert.equal(y.balanceSheet.totalNetWorthCents-x.balanceSheet.totalNetWorthCents,-100000);assert.equal(y.properties[0].primary.totalCashCostCents-x.properties[0].primary.totalCashCostCents,100000);assert.equal(y.accounts.activity['general-cash'].closingBalanceCents-x.accounts.activity['general-cash'].closingBalanceCents,-100000);assert.equal(y.reconciliation.cash.actualClosingCashCents-x.reconciliation.cash.actualClosingCashCents,-100000);const component=r=>r.netWorthDecomposition.components.find(c=>c.type==='primaryResidenceCarryingCosts').economicEffectCents;assert.equal(component(y)-component(x),-100000);assert.equal(rb.invariants.passes,true);assert.doesNotThrow(()=>canonicalStringify(rb));assert.equal(resultFingerprint(rb),resultFingerprint(run(b)));});
function household(){return {income:{cashCompensationCents:1000000,militaryTaxableCents:0,militaryNontaxableCents:0,physicianCents:0,otherEmploymentCents:1000000,pensionCents:0},taxes:{totalTaxCents:100000},spending:{totalCents:200000,essentialCents:200000,discretionaryCents:0,oneTimeCents:0,entries:[{category:'housing',amountCents:100000}]},debt:{changes:[{totalPaymentCents:10000}],interestCents:2000,principalCents:8000},allocation:{employeeRetirementCents:50000},reconciliation:{cash:{entries:[]}}};}
function property(){return {propertyResults:[{primary:{totalCashCostCents:150000},mortgage:{paymentsCents:50000,interestCents:30000,principalCents:20000}}],portfolio:{cashFlowAfterFinancingCents:0,purchases:[],sales:[]},cashUses:[],cashSources:[]};}
test('primary costs replace generic housing instead of adding both',()=>{const h=household(),p=property();assert.equal(buildCashFlowSnapshot({householdYear:h,propertyYear:p}).freeCashFlowCents,640000);p.cashUses=[{type:'genericHousing',amountCents:50000}];p.propertyResults[0].primary.totalCashCostCents=75000;assert.equal(buildCashFlowSnapshot({householdYear:h,propertyYear:p}).freeCashFlowCents,665000);});
test('rental distributions include vacancy operations and financing once, NOI excludes financing',()=>{const h=household(),p=property();p.propertyResults=[{rental:{operatingExpensesCents:20000,mortgageDebtServiceCents:30000},mortgage:{paymentsCents:30000,interestCents:20000,principalCents:10000}}];p.cashUses=[{type:'genericHousing',amountCents:100000}];p.portfolio.cashFlowAfterFinancingCents=40000;const r=buildCashFlowSnapshot({householdYear:h,propertyYear:p});assert.equal(r.freeCashFlowCents,730000);assert.equal(r.income.rentalDistributionsCents,40000);});
test('retirement and reserve funding are transfers; transaction costs are expenses; sale proceeds are not income',()=>{const h=household(),p=property(),a=buildCashFlowSnapshot({householdYear:h,propertyYear:p});h.allocation.employeeRetirementCents+=100000;h.allocation.reserveRestorationCents=100000;p.cashUses.push({type:'propertyReserveFunding',amountCents:100000});p.cashSources.push({type:'propertySalePrice',amountCents:10000000},{type:'propertyReserveRelease',amountCents:500000});assert.equal(buildCashFlowSnapshot({householdYear:h,propertyYear:p}).freeCashFlowCents,a.freeCashFlowCents);p.portfolio.purchases=[{closingCostsCents:2000,setupCostsCents:1000,downPaymentCents:100000,propertyReserveCents:20000}];p.portfolio.sales=[{sellingCostsCents:5000,mortgagePayoffCents:1000000}];const b=buildCashFlowSnapshot({householdYear:h,propertyYear:p});assert.equal(b.freeCashFlowCents,a.freeCashFlowCents-8000);assert.equal(b.income.totalCashIncomeCents,1000000);});
test('cash interest is a cash resource but unrealized investment growth is not',()=>{const h=household();const a=buildCashFlowSnapshot({householdYear:h});h.reconciliation.cash.entries=[{type:'cashInterest',amountCents:1000}];assert.equal(buildCashFlowSnapshot({householdYear:h}).freeCashFlowCents-a.freeCashFlowCents,1000);});
