import test from 'node:test';
import assert from 'node:assert/strict';
import { simulateFinancialLife } from '../model/financial-life.js';
import { simulateReproducibly, replaySimulation, ENGINE_VERSION } from '../model/reproducibility.js';
import { stableFingerprint } from '../storage/canonical.js';
import { OUTPUT_CONTRACT_VERSION, SCHEMA_VERSION, FINAL_MODEL_VERSION } from '../storage/schema.js';
import { goldenIntegratedFixture } from './golden-integrated-fixture.js';
import { goldenProductionFixture } from './golden-production-fixture.js';

const integrated=({unresolved=false}={})=>{const fixture=goldenIntegratedFixture();if(unresolved)fixture.model.policies.unresolvedChoice={action:'leaveUnexecuted'};const result=simulateFinancialLife(fixture.model,{data:fixture.data,taxTables:fixture.taxTables});return{...fixture,result};};
const decision=(result,year)=>result.years.find(row=>row.year===year).decisions.find(item=>item.goalId==='long-term-home-goal');
const stripComparison=value=>Array.isArray(value)?value.map(stripComparison):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([key])=>key!=='strategyComparison').map(([key,item])=>[key,stripComparison(item)])):value;
const financialProjection=result=>({years:result.years,timeline:result.timeline,timelineDeltas:result.timelineDeltas,realizedEvents:result.realizedEvents,decisions:result.decisions,goalResults:result.goalResults,goals:result.goals,warnings:result.warnings,errors:result.errors,invariants:result.invariants});

test('years without alternatives do not fabricate a strategy comparison',()=>{const {result}=integrated();assert.equal(Object.hasOwn(decision(result,2038),'strategyComparison'),false);});
test('comparison year exposes stable baseline and alternative strategy identities',()=>{const {result}=integrated(),comparison=decision(result,2039).strategyComparison;assert.ok(comparison);assert.equal(comparison.status,'needsUserChoice');assert.equal(comparison.needsUserChoice,true);assert.deepEqual(comparison.evaluations.map(item=>item.strategyId),['keep-rental','sell-rental']);});
test('baseline decision remains authoritative and equals its already-calculated comparison evaluation',()=>{const {result}=integrated(),actual=decision(result,2039),keep=actual.strategyComparison.evaluations.find(item=>item.strategyId==='keep-rental');for(const key of ['targetPriceRealCents','targetPriceNominalCents','requiredUpfrontCents','permittedFundingAvailableCents','fundingPlan','blockers','primaryBlocker','housingBurden','prePurchaseFreeCashFlowCents','postPurchaseFreeCashFlowCents','retainedPropertyIds','proposedSalePropertyIds','estimatedSaleProceedsCents','rentalCashFlowEffectCents'])assert.deepEqual(actual[key],keep[key]);assert.equal(actual.status,'possible');});
test('sell evaluation preserves authoritative net proceeds, rental effect, funding, burden, and reserves',()=>{const {result}=integrated(),sell=decision(result,2039).strategyComparison.evaluations.find(item=>item.strategyId==='sell-rental');assert.equal(sell.estimatedSaleProceedsCents,26_000_000);assert.equal(sell.rentalCashFlowEffectCents,-800_000);assert.deepEqual(sell.proposedSalePropertyIds,['duty-home']);assert.deepEqual(sell.retainedPropertyIds,[]);assert.equal(sell.requiredUpfrontCents,26_585_744);assert.equal(sell.permittedFundingAvailableCents,208_163_666);assert.equal(sell.postPurchaseFreeCashFlowCents,18_801_884);assert.equal(sell.housingBurden.burden,0.2418587444508881);assert.equal(sell.propertyReservesAfterCents,0);});
test('unresolved policy keeps decision and goal at needsUserChoice with the existing warning',()=>{const {result}=integrated({unresolved:true}),row=result.years.find(item=>item.year===2039),actual=decision(result,2039);assert.equal(actual.status,'needsUserChoice');assert.equal(row.goals[0].status,'needsUserChoice');assert.ok(result.warnings.some(item=>item.code==='UNRESOLVED_USER_CHOICE'&&item.year===2039));assert.equal(row.properties.some(item=>item.propertyId==='long-term-home'),false);});
test('comparison exposes no recommendation or winner field',()=>{const {result}=integrated(),comparison=decision(result,2039).strategyComparison;for(const key of ['recommendedStrategy','bestStrategy','optimalStrategy','winner','expectedWinner','preferredStrategy'])assert.equal(Object.hasOwn(comparison,key),false);});
test('all pre-extension financial output remains byte-stable after removing the additive field',()=>{const {result}=integrated();assert.equal(stableFingerprint(stripComparison(financialProjection(result))),'fnv1a64:7f22bf407e94bc21');assert.equal(result.invariants.passes,true);});
test('approved version identities change only engine and output contract versions',()=>{const fixture=goldenProductionFixture(),run=simulateReproducibly(fixture.model,{data:fixture.data,taxTables:fixture.taxTables,generatedAt:'2000-01-01T00:00:00.000Z'});assert.equal(run.manifest.modelVersion,FINAL_MODEL_VERSION);assert.equal(run.manifest.schemaVersion,SCHEMA_VERSION);assert.equal(run.manifest.outputContractVersion,'2.0.1');assert.equal(run.manifest.engineVersion,'v2.0.1');assert.equal(OUTPUT_CONTRACT_VERSION,'2.0.1');assert.equal(ENGINE_VERSION,'v2.0.1');});
test('input, assumption, and data fingerprints stay fixed while output changes intentionally',()=>{const fixture=goldenIntegratedFixture(),run=simulateReproducibly(fixture.model,{data:fixture.data,taxTables:fixture.taxTables,generatedAt:'2000-01-01T00:00:00.000Z'});assert.equal(run.manifest.inputHash,'fnv1a64:1cf42bfaa13c0bad');assert.equal(run.manifest.assumptionsHash,'fnv1a64:069db142e7fc73e4');assert.equal(run.manifest.dataFingerprint,'fnv1a64:27d1135505884f14');assert.equal(run.manifest.outputHash,'fnv1a64:cb1021fd0d63a067');assert.notEqual(run.manifest.outputHash,'fnv1a64:82ddd5a9c73da759');assert.equal(run.manifest.runId,'run:1cf42bfaa13c0bad:27d1135505884f14');});
test('v2.0.1 replay is deterministic and matches itself',()=>{const fixture=goldenIntegratedFixture(),a=simulateReproducibly(fixture.model,{data:fixture.data,taxTables:fixture.taxTables,generatedAt:'2000-01-01T00:00:00.000Z'}),b=simulateReproducibly(fixture.model,{data:fixture.data,taxTables:fixture.taxTables,generatedAt:'2000-01-01T00:00:00.000Z'}),replay=replaySimulation({model:fixture.model,data:fixture.data,taxTables:fixture.taxTables,expectedManifest:a.manifest});assert.equal(a.manifest.outputHash,b.manifest.outputHash);assert.equal(replay.status,'MATCH');assert.equal(replay.matches,true);});
