import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createBaselineModel, assessSimulationReadiness, validateProductionModel } from '../index.js';
import { createDraftSession, editDraft, discardDraft, parseMoneyInput, formatMoneyInput, stableEntityId, canDeleteEntity, sectionStatuses, setupProgress, summarizeChanges, issuesForEditorField } from '../ui/editor-state.js';
import { configureAccountBalance, configureReference, configurePartner, addGenericCareer, addJagTemplate, configureMilitaryBahFallback, addPediatricsTemplate, addLiability, configureSpending, configureAssumption, configureExpectedTransfer, configureLongTermHome } from '../ui/model-editor-actions.js';
import { modelSetupMarkup } from '../ui/model-setup-view.js';
import { inspectModel, persistModel, loadSavedModel, runReadyModel } from '../ui/model-entry.js';

const memoryStorage=()=>{const values=new Map();return{getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key),key:index=>[...values.keys()][index]??null,get length(){return values.size;}};};
function minimallyReady(){const model=createBaselineModel();configureReference(model,{name:'Me',birthDate:'2004-04-15'});model.household.simulationStartYear=2026;model.household.simulationEndYear=2030;model.household.filingStatus='single';for(const account of model.accounts)configureAccountBalance(model,account.id,0);addGenericCareer(model,{personId:'reference',role:'Employment',startDate:'2026-01-01',endDate:'2031-01-01',annualCents:6_000_000});return model;}

test('money parser preserves integer cents and distinguishes unset from zero',()=>{assert.equal(parseMoneyInput(''),null);assert.equal(parseMoneyInput('$0'),0);assert.equal(parseMoneyInput('$0.01'),1);assert.equal(parseMoneyInput('$10.99'),1099);assert.equal(parseMoneyInput('$15,000'),1_500_000);assert.equal(parseMoneyInput('$1,000,000.37'),100_000_037);assert.equal(formatMoneyInput(100_000_037),'1,000,000.37');assert.throws(()=>parseMoneyInput('10.999'));});
test('draft edits never mutate persisted model and discard restores it',()=>{const model=createBaselineModel(),session=createDraftSession(model),edited=editDraft(session,draft=>{draft.household.simulationStartYear=2026;});assert.equal(model.household.simulationStartYear,null);assert.equal(edited.dirty,true);assert.equal(discardDraft(edited).draft.household.simulationStartYear,null);});
test('stable entity IDs do not depend on array indexes',()=>{assert.equal(stableEntityId('career',[{id:'career'},{id:'career-2'}]),'career-3');});
test('minimum UI configuration transitions readiness without fixture input',()=>{const model=minimallyReady();assert.equal(assessSimulationReadiness(model).ready,true);assert.equal(validateProductionModel(model).valid,true);});
test('account setup preserves explicit zero, ownership, and user provenance',()=>{const model=createBaselineModel();configureAccountBalance(model,'general-cash',0);assert.equal(model.accounts[0].openingBalanceCents,0);assert.equal(model.accounts[0].ownerId,'household');assert.equal(model.provenance['user.account.general-cash.openingBalance'].classification,'userEntered');});
test('second person supports age offset and exact date without changing reference person',()=>{const model=createBaselineModel();configurePartner(model,{enabled:true,name:'Partner',birthMode:'offset',ageOffset:-2});const partner=model.people.find(p=>!p.isReference);assert.equal(partner.ageOffsetFromReference,-2);configurePartner(model,{enabled:true,name:'Partner',birthMode:'date',birthDate:'2005-01-01'});assert.equal(partner.isReference,false);assert.equal(model.people.filter(p=>p.isReference).length,1);});
test('referenced person deletion is blocked with explanatory references',()=>{const model=createBaselineModel(),result=canDeleteEntity(model,'people','reference');assert.equal(result.allowed,false);assert.ok(result.references.some(row=>row.startsWith('accounts:')));});
test('generic debt and explicit no-debt states remain valid model inputs',()=>{const model=createBaselineModel();assert.equal(model.liabilities.length,0);const id=addLiability(model,{name:'Law school debt',ownerId:'reference',balanceCents:5_000_000,annualRate:.05,scheduledPaymentCents:600_000,startYear:2026,endYear:2030});assert.equal(model.liabilities.find(x=>x.id===id).scheduledPayments.length,5);});
test('career editor creates generic frozen-model stages without salary calculation',()=>{const model=createBaselineModel(),id=addGenericCareer(model,{personId:'reference',role:'Legal work',startDate:'2026-01-01',endDate:'2030-01-01',annualCents:8_000_000,growthRate:.02});const stage=model.careers.find(x=>x.id===id);assert.equal(stage.careerType,'genericEmployment');assert.equal(stage.compensationRule.annualCents,8_000_000);});
test('JAG preset requires an explicit editable BAH fallback and preserves independent service history',()=>{const model=createBaselineModel();model.household.simulationStartYear=2026;model.household.simulationEndYear=2050;assert.throws(()=>addJagTemplate(model,{personId:'reference',startDate:'2029-07-01',endDate:'2051-01-01'}),/positive monthly BAH/);addJagTemplate(model,{personId:'reference',startDate:'2029-07-01',endDate:'2051-01-01',bahFallbackMonthlyCents:210_000});assert.equal(model.careers[0].careerType,'military');assert.equal(model.careers[0].compensationRule.bahFallback.monthlyCents,210_000);assert.match(model.careers[0].compensationRule.bahFallback.provenanceIds[0],/^user\./);assert.equal(model.serviceHistories[0].payGradeHistory[0].grade,'O-2');assert.equal(model.serviceHistories[0].payGradeHistory[1].grade,'O-3');});
test('JAG BAH edits remain user-entered with complete provenance',()=>{const model=createBaselineModel();addJagTemplate(model,{personId:'reference',startDate:'2029-07-01',endDate:'2035-01-01',bahFallbackMonthlyCents:210_000});configureMilitaryBahFallback(model,'air-force-jag',225_000);const id=model.careers[0].compensationRule.bahFallback.provenanceIds[0];assert.equal(model.careers[0].compensationRule.bahFallback.monthlyCents,225_000);assert.equal(model.provenance[id].classification,'userEntered');assert.equal(model.provenance[id].value,225_000);});
test('pediatrics preset produces PGY progression and attending stage',()=>{const model=createBaselineModel();addPediatricsTemplate(model,{personId:'reference',residencyStart:'2028-07-01',attendingEnd:'2040-01-01'});assert.deepEqual(model.careers.map(x=>x.careerType),['physicianResidency','physicianResidency','physicianResidency','physicianAttending']);});
test('spending editor stores monthly inputs as annual cents with frozen classification',()=>{const model=createBaselineModel();model.household.simulationStartYear=2026;model.household.simulationEndYear=2030;configureSpending(model,{category:'housing',monthlyCents:150_000,classification:'essential'});assert.equal(model.spendingSchedules[0].amountCents,1_800_000);assert.equal(model.spendingSchedules[0].classification,'essential');});
test('assumption override becomes user-entered and reset restores planning default provenance',()=>{const model=createBaselineModel();configureAssumption(model,{key:'investmentReturn',value:.055});assert.equal(model.provenance['user.assumption.investmentReturn'].classification,'userEntered');assert.equal(model.accounts.find(a=>a.type==='retirementInvestment').annualReturn,.055);configureAssumption(model,{key:'investmentReturn',reset:true});assert.equal(model.assumptions.investmentReturn,.06);assert.equal(model.provenance['user.assumption.investmentReturn'],undefined);});
test('expected transfer is an event and does not imply rental use',()=>{const model=createBaselineModel();configureExpectedTransfer(model,{enabled:true,date:'2032-01-01',valueCents:20_000_000,ownerId:'reference',status:'other'});const event=model.plannedEvents[0];assert.equal(event.type,'asset.transfer.expected');assert.equal(event.property.initialStatus,'other');assert.equal(event.property.monthlyRentCents,undefined);});
test('long-term-home setup stores a real 2025-dollar target and no future nominal UI value',()=>{const model=createBaselineModel();configureLongTermHome(model,{enabled:true,targetCents:150_000_000,startDate:'2040-01-01',endDate:'2045-12-31',locationKey:'TX-DALLAS',downPaymentRate:.2,allowTaxableInvestments:true});const goal=model.goals[0];assert.equal(goal.target.basis,'real');assert.equal(goal.target.baseYear,2025);assert.equal(goal.target.nominalAmountCents,undefined);});
test('setup progress derives from actual readiness areas',()=>{const model=minimallyReady(),statuses=sectionStatuses(model),progress=setupProgress(statuses);assert.equal(progress.complete,5);assert.equal(progress.total,5);});
test('setup markup is sectioned, labeled, accessible, and exposes origin',()=>{const model=createBaselineModel(),editor=createDraftSession(model),inspection=inspectModel(model),html=modelSetupMarkup({model,editor,...inspection,setupSection:'people'});assert.match(html,/aria-label="Model setup sections"/);assert.match(html,/Reference person/);assert.match(html,/type="date"/);assert.match(html,/Unsaved changes|Saved/);});
test('structured readiness and validation issues map to their editor fields',()=>{const editor=createDraftSession(createBaselineModel());assert.equal(issuesForEditorField(editor,'referenceBirthDate')[0].code,'REFERENCE_BIRTH_REQUIRED');assert.equal(issuesForEditorField(editor,'simulationStartYear')[0].code,'SIMULATION_START_REQUIRED');assert.equal(issuesForEditorField(editor,'account:general-cash')[0].code,'STARTING_BALANCE_REQUIRED');const invalid=editDraft(editor,draft=>{draft.accounts[0].ownerId='missing';});assert.equal(issuesForEditorField(invalid,'accountOwner:general-cash')[0].code,'ACCOUNT_OWNER_DANGLING');});
test('draft health and audit refresh from production APIs after an edit',()=>{const editor=createDraftSession(createBaselineModel()),edited=editDraft(editor,draft=>configureAccountBalance(draft,'general-cash',0));assert.equal(edited.health.modelHealthOnly,true);assert.equal(edited.audit.counts.userEntered,editor.audit.counts.userEntered+1);});
test('review summary reports meaningful changes rather than metadata noise',()=>{const before=createBaselineModel(),after=structuredClone(before);after.household.filingStatus='single';const rows=summarizeChanges(before,after);assert.deepEqual(rows.map(x=>x.label),['Filing status']);});
test('valid incomplete draft can save and reload through production persistence',()=>{const storage=memoryStorage(),model=createBaselineModel(),saved=persistModel(storage,model);assert.equal(saved.ok,true);const loaded=loadSavedModel(storage);assert.equal(loaded.model.household.simulationStartYear,null);assert.equal(loaded.readiness.status,'INCOMPLETE_CONFIGURATION');});
test('invalid draft never replaces the last valid persisted model',()=>{const storage=memoryStorage(),model=createBaselineModel();assert.equal(persistModel(storage,model).ok,true);const invalid=structuredClone(model);invalid.accounts[0].ownerId='missing';assert.equal(persistModel(storage,invalid).ok,false);assert.equal(loadSavedModel(storage).model.accounts[0].ownerId,'household');});
test('ready save runs authoritative simulation once and keeps UI slider concerns separate',()=>{const model=minimallyReady(),run=runReadyModel(model);assert.equal(run.ran,true);assert.equal(run.result.years.length,5);});
test('production setup imports no fixtures and V2.0 frozen files remain untouched',()=>{const files=['ui/editor-state.js','ui/model-editor-actions.js','ui/model-setup-view.js'].map(file=>fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8'));assert.ok(files.every(source=>!source.includes('golden-')&&!source.includes('/tests/')));});
test('responsive form CSS, focus styles, and setup landmarks are present',()=>{const css=fs.readFileSync(new URL('../../../v2/app.css',import.meta.url),'utf8'),html=fs.readFileSync(new URL('../../../v2/index.html',import.meta.url),'utf8');assert.match(css,/\.editor-layout/);assert.match(css,/@media \(max-width: 760px\)/);assert.match(css,/:focus-visible/);assert.match(html,/<main id="app-main"/);});
