import { escapeHtml, formatCurrency, formatSignedCurrency, titleCase } from './formatting.js';
import { referenceAge } from './app-state.js';
import { periodExplorerMarkup, ownerLabels, ownershipLabel, reconciliationBadge, modelScopeNote } from './analysis-shared.js';

const GROUPS={generalCash:'Cash & reserves',emergencyReserve:'Cash & reserves',dedicatedGoalFunds:'Cash & reserves',taxableInvestments:'Investments',otherFinancialAssets:'Investments',retirementAccounts:'Retirement',primaryResidence:'Real estate',rentalProperties:'Real estate',otherMaterialAssets:'Other assets'};
const LIABILITY_GROUPS={educationDebt:'Education / personal debt',mortgage:'Mortgages'};

export function assetsViewModel(row){return {year:row.year,balanceSheet:row.balanceSheet,accounts:row.accounts,liabilities:row.liabilities,properties:row.properties,contributionVsGrowth:row.contributionVsGrowth,netWorthDecomposition:row.netWorthDecomposition,reconciliation:row.reconciliation,warnings:row.warnings??[]};}

export function assetsMarkup({row,simulation,model}){
  const data=assetsViewModel(row),bs=data.balanceSheet,labels=ownerLabels(model),age=referenceAge(row,model),assets=bs.assets.items,liabilities=bs.liabilities.items;
  return `<section class="view analysis-view" aria-labelledby="assets-title">${periodExplorerMarkup({row,simulation,model,title:'Balance-sheet period'})}
    <header class="analysis-heading"><div><p class="eyebrow">Closing balance sheet</p><h1 id="assets-title">Assets</h1><p>Age ${age} · ${row.year} · Values reflect year-end modeled balances.</p></div><div class="hero-number"><span>Total net worth</span><strong>${formatCurrency(bs.totalNetWorthCents)}</strong><small>Assets minus liabilities</small></div></header>
    <section class="balance-hero" aria-label="Selected-year balance sheet summary">
      <article><span>Total assets</span><strong>${formatCurrency(bs.grossAssetsCents,{compact:true})}</strong></article><i aria-hidden="true">−</i><article><span>Total liabilities</span><strong>${formatCurrency(bs.totalLiabilitiesCents,{compact:true})}</strong></article><i aria-hidden="true">=</i><article class="net"><span>Net worth</span><strong>${formatCurrency(bs.totalNetWorthCents,{compact:true})}</strong></article>
    </section>
    <section class="supporting-metrics"><article><span>Liquid net worth</span><strong title="${formatCurrency(bs.liquidNetWorthCents)}">${formatCurrency(bs.liquidNetWorthCents,{compact:true})}</strong><small>Per the frozen V2 liquidity definition</small></article><article><span>Investable net worth</span><strong title="${formatCurrency(bs.investableNetWorthCents)}">${formatCurrency(bs.investableNetWorthCents,{compact:true})}</strong><small>Cash and marketable financial accounts</small></article><article><span>Real-estate equity</span><strong title="${formatCurrency(bs.realEstateEquityCents)}">${formatCurrency(bs.realEstateEquityCents,{compact:true})}</strong><small>Property value less linked property debt</small></article></section>
    <section class="analysis-grid assets-grid">
      <section class="panel panel-pad composition-panel"><div class="panel-header"><div><p class="section-label">Selected-year composition</p><h2>Where assets are held</h2><p>Closing asset balances grouped only for presentation.</p></div></div>${compositionVisual(bs.assets.byCategory,bs.grossAssetsCents)}</section>
      <section class="panel panel-pad"><div class="panel-header"><div><p class="section-label">Ownership</p><h2>Household view</h2><p>Shared assets are counted once, with ownership preserved.</p></div></div>${ownershipSummary(bs.ownership,labels)}</section>
      <section class="panel panel-pad balance-column"><div class="panel-header"><div><p class="section-label">What is owned</p><h2>Assets</h2></div><strong>${formatCurrency(bs.grossAssetsCents)}</strong></div>${assetGroups(assets,data,labels)}</section>
      <section class="panel panel-pad balance-column"><div class="panel-header"><div><p class="section-label">What is owed</p><h2>Liabilities</h2></div><strong>${formatCurrency(bs.totalLiabilitiesCents)}</strong></div>${liabilityGroups(liabilities,data,labels)}</section>
      <section class="panel panel-pad growth-panel"><div class="panel-header"><div><p class="section-label">Annual account activity</p><h2>Contribution vs growth</h2><p>Contributions and transfers are shown separately from asset earnings.</p></div></div>${contributionGrowth(data.contributionVsGrowth)}</section>
      <section class="panel panel-pad drivers-panel"><div class="panel-header"><div><p class="section-label">Economic explanation</p><h2>Why net worth changed</h2><p>Zero-effect transfers remain visible but are not counted as wealth creation.</p></div>${reconciliationBadge(data.reconciliation.netWorthChange,'Change reconciled')}</div>${decompositionRows(data.netWorthDecomposition)}</section>
      <section class="panel panel-pad audit-card full-width"><div class="panel-header"><div><p class="section-label">Audit</p><h2>Balance-sheet reconciliation</h2></div>${reconciliationBadge(data.reconciliation.balanceSheet,'Balance sheet reconciled')}</div><dl class="recon-list"><div><dt>Reported assets</dt><dd>${formatCurrency(data.reconciliation.balanceSheet.reportedGrossAssetsCents)}</dd></div><div><dt>Reported liabilities</dt><dd>${formatCurrency(data.reconciliation.balanceSheet.reportedLiabilitiesCents)}</dd></div><div><dt>Reported net worth</dt><dd>${formatCurrency(data.reconciliation.balanceSheet.reportedNetWorthCents)}</dd></div><div><dt>Difference</dt><dd>${formatCurrency(data.reconciliation.balanceSheet.netWorthDifferenceCents)}</dd></div></dl><details class="inline-details"><summary>Net-worth change identity</summary><dl class="recon-list"><div><dt>Opening net worth</dt><dd>${formatCurrency(data.reconciliation.netWorthChange.openingNetWorthCents)}</dd></div><div><dt>Explained change</dt><dd>${formatSignedCurrency(data.reconciliation.netWorthChange.explainedChangeCents)}</dd></div><div><dt>Closing net worth</dt><dd>${formatCurrency(data.reconciliation.netWorthChange.closingNetWorthCents)}</dd></div><div><dt>Difference</dt><dd>${formatCurrency(data.reconciliation.netWorthChange.differenceCents)}</dd></div></dl></details></section>
    </section>${modelScopeNote(data.warnings)}</section>`;
}

function compositionVisual(byCategory,total){
  const palette=['tone-1','tone-2','tone-3','tone-4','tone-5'],entries=Object.entries(byCategory??{}).filter(([,value])=>value>0).map(([key,value])=>({key,label:GROUPS[key]??titleCase(key),value}));
  const grouped=new Map();for(const item of entries)grouped.set(item.label,(grouped.get(item.label)??0)+item.value);const rows=[...grouped].map(([label,value],i)=>({label,value,tone:palette[i%palette.length]}));
  if(!rows.length)return '<p class="muted empty-copy">No modeled assets at this year-end.</p>';
  return `<figure class="composition"><div class="composition-rail" aria-hidden="true">${rows.map(row=>`<span class="${row.tone}" style="width:${total>0?row.value/total*100:0}%"></span>`).join('')}</div><figcaption>${rows.map(row=>`<div><span class="composition-key ${row.tone}" aria-hidden="true"></span><strong>${escapeHtml(row.label)}</strong><span>${formatCurrency(row.value)} · ${total>0?Math.round(row.value/total*100):0}%</span></div>`).join('')}</figcaption><p class="sr-only">${rows.map(row=>`${row.label}: ${formatCurrency(row.value)}`).join('. ')}</p></figure>`;
}
function ownershipSummary(ownership,labels){const entities=Object.entries(ownership?.entities??{}).filter(([id,row])=>labels.has(id)&&(row.grossAssetsCents||row.liabilitiesCents));return entities.length?`<div class="ownership-list">${entities.map(([id,row])=>`<div><strong>${escapeHtml(labels.get(id))}</strong><span>Assets ${formatCurrency(row.grossAssetsCents,{compact:true})}</span><span>Liabilities ${formatCurrency(row.liabilitiesCents,{compact:true})}</span><b>${formatCurrency(row.netWorthCents,{compact:true})}</b></div>`).join('')}</div>`:'<p class="muted">No ownership-specific balances are active.</p>';}
function assetGroups(items,data,labels){
  if(!items.length)return '<div class="empty-inline"><strong>No modeled assets</strong><span>Closing balances will appear here when present.</span></div>';
  const groups=new Map();for(const item of items){const name=GROUPS[item.category]??'Other assets';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(item);}
  return [...groups].map(([name,rows])=>`<div class="balance-group"><h3>${escapeHtml(name)}</h3>${rows.map(item=>assetRow(item,data,labels)).join('')}</div>`).join('');
}
function assetRow(item,data,labels){
  const activity=item.kind==='account'?data.accounts.activity?.[item.id]:null,property=item.kind==='property'?data.properties.find(row=>row.propertyId===item.id):null,owner=ownershipLabel(item.ownership,labels),details=activity?`<dl class="activity-list"><div><dt>Opening</dt><dd>${formatCurrency(activity.openingBalanceCents)}</dd></div><div><dt>Employee / household contributions</dt><dd>${formatCurrency(activity.employeeContributionsCents)}</dd></div><div><dt>Employer / government</dt><dd>${formatCurrency(activity.employerGovernmentContributionsCents)}</dd></div><div><dt>Transfers in / out</dt><dd>${formatCurrency(activity.transfersInCents)} / ${formatCurrency(activity.transfersOutCents)}</dd></div><div><dt>Growth</dt><dd>${formatSignedCurrency(activity.growthCents)}</dd></div><div><dt>Closing</dt><dd>${formatCurrency(activity.closingBalanceCents)}</dd></div></dl>`:property?propertyDetail(property):'';
  return `<details class="balance-row"><summary><div><strong>${escapeHtml(item.name||titleCase(item.type))}</strong><span>${escapeHtml(owner)} · ${escapeHtml(titleCase(item.liquidity))}${item.status?` · ${escapeHtml(titleCase(item.status))}`:''}</span></div><b>${formatCurrency(item.valueCents)}</b></summary>${details||'<p class="muted">No annual activity detail is available for this asset.</p>'}</details>`;
}
function propertyDetail(property){const equity=property.equity;return `<dl class="activity-list"><div><dt>Market value</dt><dd>${formatCurrency(equity.marketValueCents)}</dd></div><div><dt>Linked debt</dt><dd>${formatCurrency(equity.debtCents)}</dd></div><div><dt>Equity</dt><dd>${formatCurrency(equity.equityCents)}</dd></div>${property.reserve?`<div><dt>Property reserve</dt><dd>${formatCurrency(property.reserve.actualCents)}</dd></div>`:''}</dl>`;}
function liabilityGroups(items,data,labels){
  if(!items.length)return '<div class="empty-inline"><strong>No outstanding modeled liabilities</strong><span>No year-end debt balances are recorded.</span></div>';
  const groups=new Map();for(const item of items){const name=LIABILITY_GROUPS[item.type]??'Other liabilities';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(item);}
  return [...groups].map(([name,rows])=>`<div class="balance-group"><h3>${escapeHtml(name)}</h3>${rows.map(item=>liabilityRow(item,data,labels)).join('')}</div>`).join('');
}
function liabilityRow(item,data,labels){const activity=matchingLiabilityActivity(item,data),owner=labels.get(item.ownerId)??item.ownerId,linked=item.linkedAssetId?` · Linked to ${item.linkedAssetId}`:'';return `<details class="balance-row"><summary><div><strong>${escapeHtml(item.name||titleCase(item.type))}</strong><span>${escapeHtml(owner)}${escapeHtml(linked)}</span></div><b>${formatCurrency(item.balanceCents)}</b></summary>${activity?`<dl class="activity-list"><div><dt>Opening</dt><dd>${formatCurrency(activity.openingBalanceCents)}</dd></div><div><dt>Interest</dt><dd>${formatCurrency(activity.interestCents)}</dd></div><div><dt>Principal</dt><dd>${formatCurrency(activity.principalPaidCents??activity.principalCents)}</dd></div><div><dt>Payment</dt><dd>${formatCurrency(activity.totalPaymentCents??activity.paymentsCents)}</dd></div><div><dt>Closing</dt><dd>${formatCurrency(activity.closingBalanceCents)}</dd></div></dl>`:'<p class="muted">No annual liability activity detail is available.</p>'}</details>`;}
function matchingLiabilityActivity(item,data){const exact=data.liabilities.activity?.find(row=>row.id===item.id);if(exact)return exact;const property=data.properties.find(row=>row.propertyId===item.linkedAssetId);return property?.mortgage??null;}
function contributionGrowth(data){const financial=data?.financialAccounts??{},property=data?.property??{};return `<div class="growth-columns"><div><h3>Financial accounts</h3><dl class="activity-list"><div><dt>Household contributions</dt><dd>${formatCurrency(financial.employeeContributionsCents)}</dd></div><div><dt>Employer / government</dt><dd>${formatCurrency(financial.employerGovernmentContributionsCents)}</dd></div><div><dt>Investment and cash growth</dt><dd>${formatSignedCurrency(financial.growthCents)}</dd></div><div><dt>Transfers</dt><dd>${formatCurrency(financial.transfersInCents)} in · ${formatCurrency(financial.transfersOutCents)} out</dd></div></dl></div><div><h3>Property equity</h3><dl class="activity-list"><div><dt>Appreciation</dt><dd>${formatSignedCurrency(property.appreciationCents)}</dd></div><div><dt>Mortgage principal movement</dt><dd>${formatCurrency(property.mortgagePrincipalMovementCents)}</dd></div><div><dt>Operating economics</dt><dd>${formatSignedCurrency(property.operatingEconomicsCents)}</dd></div><div><dt>Transaction costs</dt><dd>${formatSignedCurrency(property.transactionCostsCents)}</dd></div></dl></div></div>`;}
function decompositionRows(decomp){const components=decomp?.components??[],economic=components.filter(item=>item.economicEffectCents!==0),transfers=components.filter(item=>item.transferCents&&item.economicEffectCents===0),label=item=>titleCase(item.label??item.type);return `<div class="driver-breakdown">${economic.length?economic.map(item=>`<div><span>${escapeHtml(label(item))}</span><strong>${formatSignedCurrency(item.economicEffectCents)}</strong></div>`).join(''):'<p class="muted">No economic change drivers are recorded.</p>'}</div>${transfers.length?`<details class="inline-details"><summary>Zero-effect transfers</summary><p class="definition-note">These movements change where wealth is held, not total wealth.</p><div class="driver-breakdown transfers">${transfers.map(item=>`<div><span>${escapeHtml(label(item))}</span><strong>${formatCurrency(item.transferCents)}</strong></div>`).join('')}</div></details>`:''}`;}
