import { escapeHtml, formatCurrency, formatPercent, titleCase } from './formatting.js';
import { referenceAge } from './app-state.js';
import { periodExplorerMarkup, reconciliationBadge, financialRows, modelScopeNote } from './analysis-shared.js';

const PRIORITY={hard:0,protected:1,important:2,optional:3};
const statusTag=status=>`<span class="status-tag ${String(status).toLowerCase()}">${escapeHtml(titleCase(status))}</span>`;

export function goalsViewModel({row,simulation,selectedGoalId}){
  const records=[...(simulation.goals??[])].filter(goal=>goal.enabled!==false).sort((a,b)=>(PRIORITY[a.priority]??9)-(PRIORITY[b.priority]??9)||(a.priorityOrder??999)-(b.priorityOrder??999)||a.id.localeCompare(b.id));
  const annual=new Map((row.goals??[]).map(goal=>[goal.goalId,goal])),selectedRecord=records.find(goal=>goal.id===selectedGoalId)??records[0]??null,result=selectedRecord?annual.get(selectedRecord.id)??null:null,decision=result?.decisionId?(row.decisions??[]).find(item=>item.id===result.decisionId)??(simulation.decisions??[]).find(item=>item.id===result.decisionId):null;
  return{year:row.year,records,annual,selectedRecord,result,decision,warnings:row.warnings??[],reconciliation:row.reconciliation.goalFunding};
}

export function goalsMarkup({row,simulation,model,selectedGoalId}){
  const data=goalsViewModel({row,simulation,selectedGoalId}),age=referenceAge(row,model),counts=countStatuses(data.records,data.annual);
  return `<section class="view analysis-view goals-view" aria-labelledby="goals-title">${periodExplorerMarkup({row,simulation,model,title:'Goal-planning period'})}
    <header class="analysis-heading"><div><p class="eyebrow">Capital planning & milestones</p><h1 id="goals-title">Goals</h1><p>Age ${age} · ${row.year} · Funding, feasibility, comfort, and decision context.</p></div><a class="button small" href="#model" data-open-setup="events">Edit goals</a></header>
    <section class="goal-statement panel" aria-label="Goal summary"><div><span>Modeled goals</span><strong>${data.records.length}</strong></div><div><span>Funding / planned</span><strong>${counts.planned}</strong></div><div><span>Possible</span><strong>${counts.possible}</strong></div><div><span>Comfortable</span><strong>${counts.comfortable}</strong></div><div><span>Delayed</span><strong>${counts.delayed}</strong></div><div><span>Needs a choice</span><strong>${counts.choice}</strong></div></section>
    ${data.selectedRecord?goalWorkspace(data,simulation):goalEmpty()}
    ${goalDecisionHistory(data)}${modelScopeNote(data.warnings)}
  </section>`;
}

function countStatuses(records,annual){const statuses=records.map(goal=>annual.get(goal.id)?.status??goal.status);return{planned:statuses.filter(x=>['planned','funding'].includes(x)).length,possible:statuses.filter(x=>x==='possible').length,comfortable:statuses.filter(x=>x==='comfortablyAffordable').length,delayed:statuses.filter(x=>x==='delayed').length,choice:statuses.filter(x=>x==='needsUserChoice').length};}
function goalEmpty(){return `<section class="panel empty goal-empty"><div><span class="empty-icon" aria-hidden="true">◇</span><h2>No modeled goals yet</h2><p>Add a goal in Model Setup when there is a future purchase or milestone to evaluate.</p><a class="button small" href="#model" data-open-setup="events">Open Model Setup</a></div></section>`;}
function goalWorkspace(data,simulation){const goal=data.selectedRecord,result=data.result,decision=data.decision,status=result?.status??goal.status;return `<section class="goals-grid"><aside class="panel goal-picker" aria-label="Goal list">${data.records.map(item=>{const annual=data.annual.get(item.id),itemStatus=annual?.status??item.status,shortfall=annual?.shortfallCents;return`<button type="button" data-goal-id="${escapeHtml(item.id)}" aria-pressed="${item.id===goal.id}"><span><small>${escapeHtml(titleCase(item.priority))} priority</small><strong>${escapeHtml(item.name)}</strong>${statusTag(itemStatus)}${Number.isSafeInteger(shortfall)&&shortfall>0?`<em>Shortfall ${formatCurrency(shortfall,{compact:true})}</em>`:''}</span><b>${formatCurrency(annual?.targetPriceRealCents??item.target?.amountCents,{compact:true})}</b></button>`;}).join('')}</aside>
    <article class="panel panel-pad goal-detail"><div class="property-title"><div><p class="section-label">Selected goal · ${escapeHtml(titleCase(goal.priority))}</p><h2>${escapeHtml(goal.name)}</h2><p>${timing(goal)} · ${goal.target?.basis==='real'?`${goal.target.baseYear} purchasing power`:'Nominal target'}</p></div>${statusTag(status)}</div>
      ${result?goalPosition(result,decision,goal):`<div class="empty-inline"><strong>No selected-year evaluation</strong><span>This configured goal has no authoritative annual result for ${data.year}.</span></div>`}
      ${result&&goal.type==='longTermHome'?homeAnalysis(result,decision):''}
      ${strategyComparison(decision)}
      ${result?fundingPlan(result):''}
      ${goalStatusHistory(goal,data.year)}
      ${provenance(goal)}
      ${goalPropertyLink(goal,simulation)}
    </article></section>`;}

function timing(goal){const window=goal.preferredWindow;return window?`Preferred ${window.startDate} – ${window.endDate}`:goal.earliestDesiredDate?`Earliest ${goal.earliestDesiredDate}`:'Timing not configured';}
function goalPosition(result,decision,goal){return `<section class="goal-position"><div><span>${goal.target?.basis==='real'?`${goal.target.baseYear}-dollar target`:'Target'}</span><strong>${formatCurrency(result.targetPriceRealCents)}</strong></div>${Number.isSafeInteger(result.targetPriceNominalCents)?`<div><span>${result.evaluatedYear??''} nominal target</span><strong>${formatCurrency(result.targetPriceNominalCents)}</strong></div>`:''}<div><span>Required upfront</span><strong>${formatCurrency(decision?.requiredUpfrontCents??result.fundingPlan?.requiredCents)}</strong></div><div><span>Permitted funding</span><strong>${formatCurrency(result.permittedFundingCents)}</strong></div><div><span>Shortfall</span><strong>${formatCurrency(result.shortfallCents)}</strong></div></section>`;}
function homeAnalysis(result,decision){if(!decision)return'';const burden=decision.housingBurden;return `<section class="home-analysis"><div class="possible-comfort"><article><span>Minimum feasibility</span><strong>${result.possible?'Possible':'Not possible'}</strong><small>Hard engine constraints</small></article><article><span>Comfort policy</span><strong>${result.comfortable?'Comfortably affordable':'Not comfortable'}</strong><small>Configured planning policy—not lender approval</small></article></div><div class="home-columns"><section><p class="section-label">Housing burden</p><h3>${burden?formatPercent(burden.burden):'Not available'}</h3>${burden?`<p>Configured comfort threshold ${formatPercent(burden.comfortThreshold)} · ${burden.pass?'passes':'exceeds by '+formatCurrency(burden.excessCents)}</p><small>Denominator: ${escapeHtml(titleCase(burden.denominator))} · ${formatCurrency(burden.denominatorCents)}</small>`:''}</section><section><p class="section-label">Free cash flow</p><h3>${formatCurrency(decision.postPurchaseFreeCashFlowCents)}</h3><p>Before purchase ${formatCurrency(decision.prePurchaseFreeCashFlowCents)}</p><small>Authoritative forward calculation after modeled housing costs.</small></section><section><p class="section-label">Reserve preservation</p><h3>${formatCurrency(decision.householdReserveAfterCents)}</h3><p>Household reserve after · property reserves ${formatCurrency(decision.propertyReservesAfterCents)}</p><small>Protected reserves are not treated as spendable goal funding.</small></section></div>${blockers(result,decision)}</section>`;}
function blockers(result,decision){const list=result.blockers??decision.blockers??[];return `<section class="blocker-section"><div class="panel-header"><div><p class="section-label">Decision constraints</p><h3>${list.length?'What blocks this goal':'All evaluated constraints pass'}</h3></div></div>${list.length?`<ol class="blocker-list">${list.map((blocker,index)=>`<li><b>${index===0?'Primary':'Secondary'}</b><div><strong>${escapeHtml(titleCase(blocker.ruleId))}</strong><p>${escapeHtml(blocker.explanation)}</p>${Number.isSafeInteger(blocker.shortfallCents)&&blocker.shortfallCents>0?`<small>Numerical gap ${formatCurrency(blocker.shortfallCents)}</small>`:''}</div></li>`).join('')}</ol>`:'<p class="muted">The authoritative decision reports no blockers for this year.</p>'}${result.status==='needsUserChoice'?`<aside class="choice-card"><strong>Needs user choice</strong><p>${escapeHtml(decision?.explanation??'The engine found a preference-dependent decision and did not choose automatically.')}</p><a class="button small" href="#model" data-open-setup="events">Configure policy in Model Setup</a></aside>`:''}</section>`;}
function strategyComparison(decision){const comparison=decision?.strategyComparison;if(!comparison?.evaluations?.length)return'';return `<section class="strategy-section"><div class="panel-header"><div><p class="section-label">Authoritative strategy comparison</p><h3>${comparison.needsUserChoice?'Keep or sell requires your preference':'Evaluated property strategies'}</h3><p>${escapeHtml(comparison.explanation)}</p></div>${comparison.needsUserChoice?statusTag('needsUserChoice'):statusTag(comparison.status)}</div><div class="strategy-grid">${comparison.evaluations.map(strategyEvaluation).join('')}</div><p class="definition-note">Alternatives are shown by stable strategy identity, not ranked. The engine does not recommend a winner or optimize this preference.</p></section>`;}
function strategyEvaluation(item){const selling=(item.proposedSalePropertyIds??[]).length>0,label=selling?'SELL':'KEEP',propertyEffect=selling?`Proposed sale: ${item.proposedSalePropertyIds.join(', ')}`:`Retained: ${(item.retainedPropertyIds??[]).join(', ')||'none'}`;return `<details class="strategy-card" open><summary><span><small>${escapeHtml(item.strategyId)}</small><strong>${label}</strong></span>${statusTag(item.status)}</summary><p>${escapeHtml(item.explanation??item.primaryBlocker?.explanation??'Strategy evaluated by the authoritative home decision system.')}</p><dl class="strategy-metrics"><div><dt>Required upfront</dt><dd>${formatCurrency(item.requiredUpfrontCents)}</dd></div><div><dt>Permitted funding</dt><dd>${formatCurrency(item.permittedFundingAvailableCents)}</dd></div><div><dt>Post-purchase FCF</dt><dd>${formatCurrency(item.postPurchaseFreeCashFlowCents)}</dd></div><div><dt>Housing burden</dt><dd>${item.housingBurden?formatPercent(item.housingBurden.burden):'Not available'}</dd></div><div><dt>Net sale proceeds</dt><dd>${formatCurrency(item.estimatedSaleProceedsCents)}</dd></div><div><dt>Rental cash-flow effect</dt><dd>${formatCurrency(item.rentalCashFlowEffectCents)}</dd></div><div><dt>Property reserves after</dt><dd>${formatCurrency(item.propertyReservesAfterCents)}</dd></div></dl><small>${escapeHtml(propertyEffect)}</small>${item.primaryBlocker?`<p class="strategy-blocker">Primary blocker · ${escapeHtml(item.primaryBlocker.explanation)}</p>`:''}</details>`;}
function fundingPlan(result){const plan=result.fundingPlan;if(!plan)return'';return `<section class="funding-section"><div class="panel-header"><div><p class="section-label">Funding plan</p><h3>Permitted sources</h3><p>Transfers fund the goal; they are not wealth creation.</p></div></div>${financialRows((plan.composition??[]).map(row=>({label:titleCase(row.type),value:row.amountCents,detail:row.sourceId})),{empty:'No permitted funding is allocated this year.'})}<div class="funding-rail" role="img" aria-label="Required ${formatCurrency(plan.requiredCents)}, planned ${formatCurrency(plan.totalPlannedCents)}, shortfall ${formatCurrency(plan.shortfallCents)}"><span style="width:${plan.requiredCents>0?Math.min(100,plan.totalPlannedCents/plan.requiredCents*100):0}%"></span></div><dl class="recon-list"><div><dt>Required</dt><dd>${formatCurrency(plan.requiredCents)}</dd></div><div><dt>Planned from permitted sources</dt><dd>${formatCurrency(plan.totalPlannedCents)}</dd></div><div><dt>Shortfall</dt><dd>${formatCurrency(plan.shortfallCents)}</dd></div><div><dt>Retirement used</dt><dd>${formatCurrency(plan.retirementUsedCents)}</dd></div><div><dt>Emergency reserve used</dt><dd>${formatCurrency(plan.emergencyReserveUsedCents)}</dd></div><div><dt>Property reserves used</dt><dd>${formatCurrency(plan.propertyReservesUsedCents)}</dd></div></dl></section>`;}
function goalStatusHistory(goal,year){const rows=goal.statusHistory??[];return `<section class="goal-history"><p class="section-label">Status history</p><h3>How the goal changes</h3>${rows.length?`<ol>${rows.map(row=>`<li class="${String(row.date).startsWith(String(year))?'selected':''}"><time>${escapeHtml(row.date)}</time>${statusTag(row.status)}<p>${escapeHtml(row.reason??'Status updated.')}</p></li>`).join('')}</ol>`:'<p class="muted">No status transitions have been recorded.</p>'}</section>`;}
function provenance(goal){const ids=goal.provenanceIds??[];return ids.length?`<details class="inline-details"><summary>Assumption provenance</summary><p class="definition-note">${ids.map(escapeHtml).join(' · ')}</p></details>`:'';}
function goalPropertyLink(goal,simulation){const id=goal.home?.resultingPropertyId;if(!id)return'';const exists=simulation.years.some(row=>row.properties.some(property=>property.propertyId===id));return exists?`<div class="cross-link"><span>Resulting property · ${escapeHtml(id)}</span><button type="button" class="button small" data-property-link="${escapeHtml(id)}">View property</button></div>`:'';}
function goalDecisionHistory(data){const content=data.decision?goalDecisionMarkup(data.decision):'<p class="muted empty-copy">No goal decision is linked to the selected goal in this year.</p>';return `<section class="panel panel-pad decision-log"><div class="panel-header"><div><p class="section-label">Decision history</p><h2>Selected-year goal decision</h2></div>${reconciliationBadge(data.reconciliation,'Goal funding reconciled')}</div>${content}</section>`;}
function goalDecisionMarkup(item){const sales=item.proposedSalePropertyIds?.length?`<p>Proposed property sales: ${escapeHtml(item.proposedSalePropertyIds.join(', '))} · authoritative estimated proceeds ${formatCurrency(item.estimatedSaleProceedsCents)}</p>`:'',retained=item.retainedPropertyIds?.length?`<p>Retained properties: ${escapeHtml(item.retainedPropertyIds.join(', '))}</p>`:'';return `<details open><summary>${statusTag(item.status)}<strong>${escapeHtml(item.id)}</strong></summary><p>${escapeHtml(item.explanation??item.primaryBlocker?.explanation??'Goal decision recorded.')}</p>${sales}${retained}</details>`;}
