import {escapeHtml as e,formatCurrency as money,titleCase} from './formatting.js';
const panel=(title,body)=>`<section class="panel panel-pad life-story"><h2>${title}</h2>${body}</section>`;
export function lifeMilestones(model,simulation){
 const meta=model.extensions?.production?.template,ref=model.people.find(p=>p.isReference),birth=ref.birthYear??Number(ref.birthDate?.slice(0,4)),rows=[];
 const personYear=p=>p.birthYear??(p.birthDate?Number(p.birthDate.slice(0,4)):birth-(p.ageOffsetFromReference??0));
 for(const ed of meta?.education??[]){const p=model.people.find(p=>p.id===ed.personId),year=Number.isInteger(ed.startYear)?ed.startYear:personYear(p)+ed.startAge,detail=ed.detail??(Number.isInteger(ed.endYear)?`Through ${ed.endYear}`:`Through age ${ed.endAge}`);if(p?.enabled!==false)rows.push({year,title:`${p.isReference?'':p.name+' · '}${ed.stage}`,status:Number.isInteger(ed.startYear)?'Current':'Planned',detail});}
 for(const c of model.careers){const p=model.people.find(p=>p.id===c.personId);if(p?.enabled===false||!c.startDate)continue;rows.push({year:Number(c.startDate.slice(0,4)),title:c.role,status:'Planned',detail:'Editable career stage'});if(c.careerType==='military')rows.push({year:Number(c.endDate.slice(0,4)),title:'Military service transition',status:'Planned',detail:'End of configured service; pension is not automatic'});}
 for(const ev of model.plannedEvents??[])if(ev.type==='household.combine')rows.push({year:Number(ev.date.slice(0,4)),title:'Household finances combine',status:'Planned',detail:'Separate from marriage and tax status'});
 for(const item of simulation.timeline??[])if(item.category==='property'){if(rows.some(r=>r.title===item.title&&r.status===item.status))continue;rows.push({year:Number((item.realizedDate??item.plannedDate??'').slice(0,4)),title:item.title,status:titleCase(item.status??'Modeled'),detail:item.summary??'See Timeline'});}
 for(const goal of model.goals??[]){for(const [key,label]of [['possible','First possible'],['comfortable','First comfortable']]){const year=simulation.years.find(r=>r.goals?.some(g=>g.goalId===goal.id&&g[key]));if(year)rows.push({year:year.year,title:goal.name,status:label,detail:'Authoritative modeled feasibility; not an executed purchase'});}const executed=simulation.years.find(r=>r.goals?.some(g=>g.goalId===goal.id&&g.status==='executed'));if(executed)rows.push({year:executed.year,title:goal.name,status:'Executed in model',detail:'See funding and property details'});}
 return rows.filter(r=>Number.isInteger(r.year)).sort((a,b)=>a.year-b.year);
}
export function lifeTimelineMarkup(model,simulation,selectedYear){
 const rows=lifeMilestones(model,simulation),ref=model.people.find(p=>p.isReference),birth=ref.birthYear??Number(ref.birthDate?.slice(0,4));
 const intent=model.extensions?.production?.optionalIntents?.expectedPropertyTransfer;
 return panel('Your life timeline',`<p>Planned milestones are assumptions, not guaranteed events. Financial decisions come from the simulation.</p><div class="life-milestones">${rows.map(r=>`<div class="life-stop" ${r.year===selectedYear?'aria-current="date"':''}><small>${e(r.status)} · ${r.year} · age ${r.year-birth}</small><strong>${e(r.title)}</strong><small>${e(r.detail)}</small></div>`).join('')}${intent&&intent.timing==null?`<div class="life-stop"><small>Unresolved · no date</small><strong>${money(intent.estimatedValueCents)} expected paid-off property</strong><small>Excluded from current wealth and rent. Configure transfer timing in Future events.</small></div>`:''}</div>`);
}
function bars(entries){const scale=Math.max(1,...entries.map(([,v])=>Math.abs(v)));return `<div class="story-bars">${entries.map(([label,value])=>`<div><div class="story-value"><span>${e(label)}</span><strong>${money(value)}</strong></div><div class="story-bar" style="width:${Math.abs(value)/scale*100}%"></div></div>`).join('')}</div>`;}
export function compositionMarkup(row){const inc=row.cashFlow.income,bs=row.balanceSheet;const income=[['Military taxable pay',inc.militaryTaxableCents],['Military allowances',inc.militaryNontaxableCents],['Physician',inc.physicianCents],['Other employment',inc.otherEmploymentCents],['Pension',inc.pensionCents],['Rental distributions',inc.rentalDistributionsCents],['Other recurring',inc.otherRecurringCents],['One-time income',inc.oneTimeIncomeCents]].filter(([,v])=>v!==0);return `<section class="panel panel-pad"><h2>Where income comes from · ${row.year}</h2><p>Annual authoritative cash sources before tax. Explore another age to see the mix change.</p>${income.length?bars(income):'<p>No cash income is modeled this year.</p>'}</section><section class="panel panel-pad"><h2>What you own and owe · ${row.year}</h2><p>Closing asset categories and total debts shown separately; property equity is available in Real Estate.</p>${bars(Object.entries(bs.assets.byCategory).map(([k,v])=>[titleCase(k),v]))}<p>Total debts: <strong>${money(bs.totalLiabilitiesCents)}</strong> · Net worth: <strong>${money(bs.totalNetWorthCents)}</strong></p><small>Negative cash is an unfunded shortfall, not an available bank balance.</small></section>`;}
export function planAtGlanceMarkup(model){const meta=model.extensions?.production?.template,goal=model.goals.find(g=>g.type==='longTermHome'),mil=model.careers.filter(c=>c.careerType==='military'),partner=model.people.find(p=>!p.isReference&&p.enabled);const education=meta?.education?.filter(row=>row.personId===model.people.find(p=>p.isReference)?.id).map(row=>row.stage).join(' → ');return panel('Plan at a glance',`<dl class="plan-facts"><div><dt>Education</dt><dd>${e(education||'Not configured')}</dd></div><div><dt>Career</dt><dd>${e(mil.map(c=>c.role).join(', ')||'No military path')}</dd></div><div><dt>Partner</dt><dd>${partner?e(model.careers.filter(c=>c.personId===partner.id).map(c=>c.role).join(' → ')):'Not included'}</dd></div><div><dt>Long-term home</dt><dd>${goal?money(goal.target.amountCents)+' in '+goal.target.baseYear+' dollars · '+e(goal.home.locationKey):'Not configured'}</dd></div><div><dt>Reserve policy</dt><dd>${model.policies.reserveMonths} months of essential expenses; property funds separate</dd></div><div><dt>Horizon</dt><dd>${model.household.simulationStartYear}–${model.household.simulationEndYear}</dd></div><div><dt>Property strategy</dt><dd>${meta?.propertyStrategy?'Single-family primary when feasible; evaluate keep or sell after PCS. No automatic purchase schedule.':'Inspect configured property intentions in Real Estate.'}</dd></div></dl>${meta?.retirementNote?`<p class="muted">${e(meta.retirementNote)}</p>`:''}`);}
