import { escapeHtml, titleCase } from './formatting.js';

const statusLabel=status=>({READY:'Healthy',READY_WITH_WARNINGS:'Has warnings',INCOMPLETE_CONFIGURATION:'Needs configuration',INVALID:'Needs attention'}[status]??titleCase(status));
const healthRows=({health,readiness,loadState})=>[
  ['Validity',health?.validation?.valid?'Valid':'Needs attention'],
  ['Configuration',statusLabel(readiness?.status)],
  ['Provenance',health?.validation?.warnings?.length?`${health.validation.warnings.length} warning${health.validation.warnings.length===1?'':'s'}`:'Complete'],
  ['Projected fallbacks',String(health?.projectedFallbacks?.length??0)],
  ['Unresolved choices',String(health?.unresolvedChoices?.length??0)],
  ['Migration',loadState==='MIGRATED_MODEL'?'Applied':'Current']
];

export function readinessPanel(readiness){const issues=readiness?.status==='INVALID'?readiness.errors:readiness?.missing??[];return `<section class="panel panel-pad"><div class="panel-header"><div><p class="section-label">Simulation readiness</p><h2>${escapeHtml(statusLabel(readiness?.status))}</h2><p>${readiness?.ready?'The model can produce projections.':'Complete the required configuration before projections are available.'}</p></div><span class="status-tag ${readiness?.ready?'healthy':'warning'}">${escapeHtml(readiness?.status??'Unknown')}</span></div>${issues.length?`<ul class="checklist">${issues.map(item=>`<li><span class="check-icon" aria-hidden="true">!</span><div><strong>${escapeHtml(titleCase(item.code))}</strong><small>${escapeHtml(item.message)}</small></div></li>`).join('')}</ul>`:'<p class="muted">All required configuration checks pass.</p>'}</section>`;}

export function healthPanel(context){return `<section class="panel panel-pad"><div class="panel-header"><div><p class="section-label">Model health</p><h2>${escapeHtml(statusLabel(context.health?.status))}</h2><p>This describes configuration quality—not financial success.</p></div></div><div class="health-list">${healthRows(context).map(([label,value])=>`<div class="health-row"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`).join('')}</div></section>`;}

export function auditPanel(audit){const keys=['userEntered','researchedOfficial','researchedEstimate','planningDefault','projected','derived','eventDriven','unset'];return `<section class="panel panel-pad"><div class="panel-header"><div><p class="section-label">Assumption audit</p><h2>Where the numbers come from</h2><p>Grouped by the classifications preserved in the model.</p></div></div><div class="audit-grid">${keys.map(key=>`<div class="audit-item"><strong>${audit?.counts?.[key]??0}</strong><span>${escapeHtml(titleCase(key))}</span></div>`).join('')}</div></section>`;}

export function modelViewMarkup(context){const {model,readiness,health,audit,manifest,loadState,importCandidate,importResult}=context;if(!model)return noModelMarkup();return `<section class="view" aria-labelledby="model-title"><div class="page-heading"><div><p class="eyebrow">Model &amp; assumptions</p><h1 id="model-title">A model you can audit.</h1><p>Review readiness, provenance, and the exact version identity behind every projection.</p></div><div class="button-row"><button class="button" type="button" data-action="import">Import</button><button class="button" type="button" data-action="export">Export</button><button class="button primary" type="button" data-action="save">Save model</button></div></div>${importCandidate?importReviewPanel(importCandidate,importResult):''}<div class="model-grid">${readinessPanel(readiness)}${healthPanel({health,readiness,loadState})}${auditPanel(audit)}${identityPanel(model,manifest)}</div></section>`;}

function importReviewPanel(candidate,result){const inspection=result.inspection,migration=result.result.migration,warnings=result.result.warnings??[];return `<section class="panel panel-pad import-review" aria-labelledby="import-review-title"><div class="panel-header"><div><p class="section-label">Import review</p><h2 id="import-review-title">Valid model ready for confirmation</h2><p>The current saved model has not been changed.</p></div><span class="status-tag ${inspection.readiness.ready?'healthy':'warning'}">${escapeHtml(inspection.readiness.status)}</span></div><div class="health-list"><div class="health-row"><span>Schema version</span><strong>${escapeHtml(candidate.schemaVersion)}</strong></div><div class="health-row"><span>Model version</span><strong>${escapeHtml(candidate.modelVersion)}</strong></div><div class="health-row"><span>Migration</span><strong>${migration?.migrated?'Required and validated':'Not required'}</strong></div><div class="health-row"><span>Validation errors</span><strong>${inspection.validation.errors.length}</strong></div><div class="health-row"><span>Warnings</span><strong>${warnings.length}</strong></div></div><div class="button-row import-actions"><button class="button primary" type="button" data-action="confirm-import">Use and save this model</button><button class="button" type="button" data-action="cancel-import">Cancel</button></div></section>`;}

export function identityPanel(model,manifest){const rows=[['Engine version',manifest?.engineVersion??'Not run'],['Model version',model.modelVersion],['Schema version',model.schemaVersion],['Output contract',manifest?.outputContractVersion??'2.0.0'],['Base currency year',String(model.baseCurrencyYear)],['Run ID',manifest?.runId??'Available after simulation'],['Input hash',manifest?.inputHash??'Available after simulation'],['Data fingerprint',manifest?.dataFingerprint??'Available after simulation']];return `<section class="panel panel-pad"><div class="panel-header"><div><p class="section-label">Reproducibility</p><h2>Run identity</h2><p>Technical detail for verifying exactly what produced a result.</p></div></div><dl class="identity-list">${rows.map(([term,value])=>`<div><dt>${escapeHtml(term)}</dt><dd>${escapeHtml(value)}</dd></div>`).join('')}</dl></section>`;}

export function noModelMarkup(){return `<section class="view start-layout" aria-labelledby="start-title"><div class="panel start-card"><p class="eyebrow">Life &amp; Wealth V2</p><h1 id="start-title">Model the life behind the number.</h1><p class="lede">Start with a clean, versioned model—or bring in an existing V2 export. Nothing personal is guessed, and incomplete models never display fake projections.</p><div class="button-row"><button class="button primary" type="button" data-action="create">Create new model</button><button class="button" type="button" data-action="import">Import model</button></div><div class="trust-row"><div><strong>Deterministic</strong><span>Same inputs, same result.</span></div><div><strong>Traceable</strong><span>Assumptions retain provenance.</span></div><div><strong>Private by default</strong><span>Saved in this browser.</span></div></div></div></section>`;}

export function blockedProjectionMarkup(readiness){return `<section class="view" aria-labelledby="blocked-title"><div class="page-heading"><div><p class="eyebrow">Overview</p><h1 id="blocked-title">Your projection is waiting for its inputs.</h1><p>V2 will not invent the missing facts required to simulate your financial life.</p></div><div class="button-row"><a class="button primary" href="#model">Review model setup</a></div></div><div class="setup-grid">${readinessPanel(readiness)}<section class="panel panel-pad empty"><div><div class="empty-icon" aria-hidden="true">—</div><h2>No projection yet</h2><p>Complete model setup before projections are available. Optional future goals can remain unset.</p></div></section></div></section>`;}

export function loadErrorMarkup(loadState,loaded){const code=loaded?.code??loadState;return `<section class="view start-layout" aria-labelledby="load-error-title"><div class="panel start-card"><p class="eyebrow">Model recovery</p><h1 id="load-error-title">The saved model needs attention.</h1><p class="lede">The existing save was preserved. ${loaded?.recovery?.backupAvailable?'A previous valid backup is available.':'No backup is currently available.'}</p><span class="error-code">${escapeHtml(code)}</span><div class="button-row" style="margin-top:1.5rem"><button class="button" type="button" data-action="import">Import another model</button><button class="button primary" type="button" data-action="create">Create a clean model</button></div></div></section>`;}
