import { escapeHtml, formatCurrency, formatDate, titleCase } from './formatting.js';

const major=item=>['career','household','property','goal','decision'].includes(item.category)&&!String(item.type).includes('allocation');
const statusClass=value=>String(value??'planned').replaceAll(/[^a-zA-Z]/g,'').toLowerCase();

export function timelineItems(simulation,category='all'){return simulation.timeline.filter(item=>major(item)&&(category==='all'||item.category===category));}

export function timelineMarkup({simulation,selectedTimelineItemId,category='all'}){const items=timelineItems(simulation,category),categories=['all',...new Set(simulation.timeline.filter(major).map(item=>item.category))];return `<section class="view" aria-labelledby="timeline-title"><div class="page-heading"><div><p class="eyebrow">Planned vs realized</p><h1 id="timeline-title">The financial plan as a life story.</h1><p>Major career, household, property, goal, and decision events—linked directly to the modeled year.</p></div></div><section class="panel panel-pad"><div class="timeline-toolbar"><div><span class="section-label">Major events</span><p class="muted">Select an event to focus its age and year throughout V2.</p></div><div class="filter-row" aria-label="Filter timeline">${categories.map(value=>`<button type="button" data-timeline-filter="${escapeHtml(value)}" aria-pressed="${value===category}">${escapeHtml(titleCase(value))}</button>`).join('')}</div></div>${items.length?`<div class="timeline">${items.map(item=>timelineItem(item,simulation.timelineDeltas,selectedTimelineItemId)).join('')}</div>`:'<div class="empty"><div><div class="empty-icon" aria-hidden="true">·</div><h2>No major events yet</h2><p>The model has no major events in this category. Technical bookkeeping remains intentionally hidden.</p></div></div>'}</section></section>`;}

function timelineItem(item,deltas,selectedId){const date=item.realizedDate??item.plannedDate,delta=deltas?.find(row=>row.timelineId===item.id),raw=item.financialEffects??[],effects=(Array.isArray(raw)?raw:Object.values(raw)).filter(row=>row&&Number.isSafeInteger(row.amountCents??row.economicEffectCents));return `<article class="timeline-item" tabindex="0" role="button" aria-label="Focus ${escapeHtml(item.title)} in ${escapeHtml(String(date).slice(0,4))}" data-timeline-id="${escapeHtml(item.id)}" data-status="${escapeHtml(item.status)}" data-selected="${item.id===selectedId}"><time class="timeline-date" datetime="${escapeHtml(date)}">${escapeHtml(formatDate(date))}</time><div><div class="timeline-meta"><span>${escapeHtml(titleCase(item.category))}</span><span>·</span><span>${escapeHtml(titleCase(item.type))}</span></div><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.summary??item.reason??'No additional explanation recorded.')}</p>${delta&&delta.deltaDays!==0?`<div class="timing-delta">Planned ${formatDate(delta.plannedDate)} · realized ${formatDate(delta.actualDate)} · ${delta.deltaYears>0?'+':''}${delta.deltaYears} years</div>`:''}${effects.length?`<div class="timing-delta">Financial effect: ${formatCurrency(effects[0].amountCents??effects[0].economicEffectCents)}</div>`:''}</div><span class="status-tag ${statusClass(item.status)}">${escapeHtml(titleCase(item.status))}</span></article>`;}
