export const SCHEMA_VERSION='2.0.0';
export const MODEL_VERSION='2.0.0-m4';
export const FINAL_MODEL_VERSION='2.0.0';
export const OUTPUT_CONTRACT_VERSION='2.0.0';

export const ASSUMPTION_CLASSIFICATIONS=Object.freeze(['userEntered','researchedOfficial','researchedEstimate','planningDefault','scenarioControlled','eventDriven','derived','projected','official','estimated','scenarioAdjusted']);
const ACCOUNT_TYPES=new Set(['generalCash','emergencyReserve','goalCash','taxableInvestment','retirementInvestment']);
const GOAL_PRIORITIES=new Set(['hard','protected','important','optional']);
const ISO_DATE=/^\d{4}-\d{2}-\d{2}$/;
const COLLECTIONS=['people','accounts','liabilities','assets','properties','propertyIntents','careers','serviceHistories','plannedEvents','goals'];
const issue=(code,severity,path,message,expected,actual,entityId)=>({code,severity,path,entityId:entityId??null,message,...(expected!==undefined?{expected}:{}),...(actual!==undefined?{actual}:{})});
const err=(code,path,message,expected,actual,entityId)=>issue(code,'error',path,message,expected,actual,entityId);
const warn=(code,path,message,expected,actual,entityId)=>issue(code,'warning',path,message,expected,actual,entityId);
const isDate=value=>typeof value==='string'&&ISO_DATE.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`));

export function createModelDocument(input={}){
  const reference=input.people?.find(person=>person.isReference),birthYear=reference?.birthYear??(reference?.birthDate?Number(reference.birthDate.slice(0,4)):2007);
  return {schemaVersion:SCHEMA_VERSION,modelVersion:MODEL_VERSION,baseCurrencyYear:2025,savedAt:new Date(0).toISOString(),household:{id:'household',simulationStartYear:birthYear+18,simulationEndYear:birthYear+95,filingStatus:'single',...input.household},people:structuredClone(input.people??[{id:'reference',isReference:true,birthYear}]),assumptions:structuredClone(input.assumptions??{}),accounts:structuredClone(input.accounts??[]),liabilities:structuredClone(input.liabilities??[]),assets:structuredClone(input.assets??[]),properties:structuredClone(input.properties??[]),propertyIntents:structuredClone(input.propertyIntents??[]),propertySimulation:structuredClone(input.propertySimulation??null),goalSimulation:structuredClone(input.goalSimulation??null),genericGoalSimulation:structuredClone(input.genericGoalSimulation??null),income:structuredClone(input.income??[]),spending:structuredClone(input.spending??[]),spendingSchedules:structuredClone(input.spendingSchedules??[]),spendingAdjustments:structuredClone(input.spendingAdjustments??[]),careers:structuredClone(input.careers??[]),retirementPolicies:structuredClone(input.retirementPolicies??{}),plannedEvents:structuredClone(input.plannedEvents??[]),goals:structuredClone(input.goals??[]),policies:structuredClone(input.policies??{}),provenance:structuredClone(input.provenance??{}),serviceHistories:structuredClone(input.serviceHistories??[]),extensions:structuredClone(input.extensions??{})};
}

export function validateModelDocument(model,{provenanceCompleteness=false,strictReferences=false}={}){
  const errors=[],warnings=[];
  if(!model||typeof model!=='object'||Array.isArray(model))return{valid:false,errors:[err('MODEL_TYPE_INVALID','model','Model must be a plain object.','object',typeof model)],warnings};
  if(model.schemaVersion!==SCHEMA_VERSION)errors.push(err('SCHEMA_VERSION_UNSUPPORTED','schemaVersion',`Expected ${SCHEMA_VERSION}.`,SCHEMA_VERSION,model.schemaVersion));
  if(typeof model.modelVersion!=='string'||!model.modelVersion)errors.push(err('MODEL_VERSION_REQUIRED','modelVersion','modelVersion is required.','non-empty string',model.modelVersion));
  if(!Number.isInteger(model.baseCurrencyYear))errors.push(err('BASE_YEAR_INVALID','baseCurrencyYear','baseCurrencyYear must be an integer.','integer',model.baseCurrencyYear));
  if(!Array.isArray(model.people)||!model.people.length)errors.push(err('PEOPLE_REQUIRED','people','At least one person is required.','non-empty array',model.people));
  for(const key of COLLECTIONS)if(model[key]!==undefined&&!Array.isArray(model[key]))errors.push(err('COLLECTION_TYPE_INVALID',key,`${key} must be an array.`,'array',typeof model[key]));
  for(const key of COLLECTIONS){const seen=new Set();for(const [index,entity] of (model[key]??[]).entries()){if(!entity?.id){errors.push(err('ENTITY_ID_REQUIRED',`${key}.${index}.id`,`${key} entry requires an id.`));continue;}if(seen.has(entity.id))errors.push(err('DUPLICATE_ID',`${key}.${index}.id`,`Duplicate ${key} id ${entity.id}.`,'unique id',entity.id,entity.id));seen.add(entity.id);}}

  const owners=new Set(['household',model.household?.id,...(model.people??[]).map(x=>x.id)].filter(Boolean));
  const accounts=new Map((model.accounts??[]).map(x=>[x.id,x])),liabilities=new Map((model.liabilities??[]).map(x=>[x.id,x])),properties=new Map((model.properties??[]).map(x=>[x.id,x])),intentProperties=new Set((model.propertyIntents??[]).map(x=>x.propertyId)),transferredProperties=new Set((model.plannedEvents??[]).filter(x=>x.type==='asset.transfer.expected').map(x=>x.property?.id)),goals=new Map((model.goals??[]).map(x=>[x.id,x]));
  if((model.people??[]).filter(x=>x.isReference).length>1)errors.push(err('REFERENCE_PERSON_DUPLICATE','people','Only one reference person is allowed.',1,(model.people??[]).filter(x=>x.isReference).length));
  if(!(model.people??[]).some(x=>x.isReference&&x.enabled!==false))errors.push(err('REFERENCE_PERSON_ACTIVE_REQUIRED','people','An active reference person is required.','one enabled reference person',0));
  for(const person of model.people??[]){if(person.birthDate!=null&&!isDate(person.birthDate))errors.push(err('BIRTH_DATE_INVALID',`people.${person.id}.birthDate`,'birthDate must be an ISO calendar date.','YYYY-MM-DD',person.birthDate,person.id));if(person.birthYear!=null&&!Number.isInteger(person.birthYear))errors.push(err('BIRTH_YEAR_INVALID',`people.${person.id}.birthYear`,'birthYear must be an integer.','integer',person.birthYear,person.id));if(person.ageOffsetFromReference!=null&&!Number.isFinite(person.ageOffsetFromReference))errors.push(err('AGE_OFFSET_INVALID',`people.${person.id}.ageOffsetFromReference`,'Age offset must be numeric.','number',person.ageOffsetFromReference,person.id));if(person.enabled!==false&&person.birthDate==null&&person.birthYear==null&&person.ageOffsetFromReference==null)warnings.push(warn('PERSON_TIMING_UNSET',`people.${person.id}`,'Birth timing is intentionally unset.',undefined,undefined,person.id));}
  const start=model.household?.simulationStartYear,end=model.household?.simulationEndYear;if(start!=null&&!Number.isInteger(start))errors.push(err('SIMULATION_START_INVALID','household.simulationStartYear','Simulation start year must be an integer or null.','integer|null',start));if(end!=null&&!Number.isInteger(end))errors.push(err('SIMULATION_END_INVALID','household.simulationEndYear','Simulation end year must be an integer or null.','integer|null',end));if(Number.isInteger(start)&&Number.isInteger(end)&&start>end)errors.push(err('SIMULATION_WINDOW_INVALID','household','Simulation start must not be after end.','start <= end',`${start} > ${end}`));

  for(const account of model.accounts??[]){const path=`accounts.${account.id}`;if(!owners.has(account.ownerId))errors.push(err('ACCOUNT_OWNER_DANGLING',`${path}.ownerId`,'Account owner does not exist.','known owner',account.ownerId,account.id));if(!ACCOUNT_TYPES.has(account.type))errors.push(err('ACCOUNT_TYPE_INVALID',`${path}.type`,'Account type is unsupported.',[...ACCOUNT_TYPES],account.type,account.id));if(account.openingBalanceCents!==null&&!Number.isSafeInteger(account.openingBalanceCents))errors.push(err('ACCOUNT_BALANCE_INVALID',`${path}.openingBalanceCents`,'Opening balance must use integer cents or be intentionally unset.','integer cents|null',account.openingBalanceCents,account.id));rate(account.annualReturn,`${path}.annualReturn`,account.id,errors,-1,2);}
  for(const liability of model.liabilities??[]){const path=`liabilities.${liability.id}`;if(!owners.has(liability.ownerId))errors.push(err('LIABILITY_OWNER_DANGLING',`${path}.ownerId`,'Liability owner does not exist.','known owner',liability.ownerId,liability.id));money(liability.openingBalanceCents,`${path}.openingBalanceCents`,'LIABILITY_BALANCE_INVALID',liability.id,errors);rate(liability.annualRate,`${path}.annualRate`,liability.id,errors,0,2);if(liability.termMonths!=null&&(!Number.isInteger(liability.termMonths)||liability.termMonths<=0))errors.push(err('TERM_INVALID',`${path}.termMonths`,'Term must be positive whole months.','positive integer',liability.termMonths,liability.id));datePair(liability.startDate,liability.endDate,path,liability.id,errors);}
  for(const property of model.properties??[]){const path=`properties.${property.id}`;ownership(property.ownership,owners,path,property.id,errors);for(const id of property.linkedLiabilityIds??[])if(!liabilities.has(id))errors.push(err('PROPERTY_MORTGAGE_DANGLING',`${path}.linkedLiabilityIds`,'Linked property liability does not exist.','known liability id',id,property.id));money(property.currentValueCents??property.estimatedValueCents,`${path}.currentValueCents`,'PROPERTY_VALUE_INVALID',property.id,errors);rate(property.appreciationRate,`${path}.appreciationRate`,property.id,errors,-1,2);propertyTimeline(property,path,errors);}
  for(const intent of model.propertyIntents??[]){const path=`propertyIntents.${intent.id}`;ownership(intent.ownership,owners,path,intent.id,errors);money(intent.expectedPriceCents,`${path}.expectedPriceCents`,'PURCHASE_PRICE_INVALID',intent.id,errors);if(Number.isSafeInteger(intent.downPaymentCents)&&Number.isSafeInteger(intent.expectedPriceCents)&&intent.downPaymentCents>intent.expectedPriceCents)errors.push(err('DOWN_PAYMENT_EXCEEDS_PRICE',`${path}.downPaymentCents`,'Down payment cannot exceed purchase price.',`<= ${intent.expectedPriceCents}`,intent.downPaymentCents,intent.id));rate(intent.mortgageRate,`${path}.mortgageRate`,intent.id,errors,0,2);rate(intent.operations?.vacancyRate,`${path}.operations.vacancyRate`,intent.id,errors,0,1);if(intent.mortgageTermMonths!=null&&(!Number.isInteger(intent.mortgageTermMonths)||intent.mortgageTermMonths<=0))errors.push(err('TERM_INVALID',`${path}.mortgageTermMonths`,'Mortgage term must be positive whole months.','positive integer',intent.mortgageTermMonths,intent.id));if(intent.propertyReserveMonths!=null&&(!Number.isFinite(intent.propertyReserveMonths)||intent.propertyReserveMonths<0))errors.push(err('RESERVE_MONTHS_INVALID',`${path}.propertyReserveMonths`,'Reserve months cannot be negative.','>= 0',intent.propertyReserveMonths,intent.id));if(intent.earliestAcceptableYear!=null&&intent.latestAcceptableYear!=null&&intent.earliestAcceptableYear>intent.latestAcceptableYear)errors.push(err('PROPERTY_WINDOW_INVALID',path,'Earliest property year must not exceed latest year.','earliest <= latest',`${intent.earliestAcceptableYear} > ${intent.latestAcceptableYear}`,intent.id));}
  for(const career of model.careers??[]){const path=`careers.${career.id}`;if(!owners.has(career.personId)||career.personId==='household')errors.push(err('CAREER_PERSON_DANGLING',`${path}.personId`,'Career person does not exist.','known person id',career.personId,career.id));datePair(career.startDate,career.endDate,path,career.id,errors);}
  for(const history of model.serviceHistories??[]){if(!owners.has(history.personId)||history.personId==='household')errors.push(err('SERVICE_PERSON_DANGLING',`serviceHistories.${history.id}.personId`,'Service-history person does not exist.','known person id',history.personId,history.id));for(const period of history.periods??[])datePair(period.startDate,period.endDate,`serviceHistories.${history.id}.periods`,history.id,errors);const entry=history.periods?.map(x=>x.startDate).filter(isDate).toSorted()[0];if(isDate(history.retirementDate)&&isDate(entry)&&Date.parse(history.retirementDate)<Date.parse(entry))errors.push(err('SERVICE_RETIREMENT_ORDER_INVALID',`serviceHistories.${history.id}.retirementDate`,'Retirement cannot precede service entry.',`>= ${entry}`,history.retirementDate,history.id));}
  for(const goal of model.goals??[]){const path=`goals.${goal.id}`;if(!GOAL_PRIORITIES.has(goal.priority))errors.push(err('GOAL_PRIORITY_INVALID',`${path}.priority`,'Goal priority is invalid.',[...GOAL_PRIORITIES],goal.priority,goal.id));if(!Array.isArray(goal.fundingPolicy?.permittedSources)||!goal.fundingPolicy.permittedSources.length)errors.push(err('GOAL_FUNDING_POLICY_INVALID',`${path}.fundingPolicy.permittedSources`,'Goal permitted funding sources are required.','non-empty array',goal.fundingPolicy?.permittedSources,goal.id));if(goal.fundingPolicy?.permittedSources?.includes('retirement'))errors.push(err('GOAL_RETIREMENT_PROTECTED',`${path}.fundingPolicy.permittedSources`,'Retirement funding is protected in V2.0.',undefined,'retirement',goal.id));for(const id of goal.fundingPolicy?.permittedAccountIds??[])if(!accounts.has(id))errors.push(err('GOAL_ACCOUNT_DANGLING',`${path}.fundingPolicy.permittedAccountIds`,'Goal funding account does not exist.','known account id',id,goal.id));if(strictReferences)for(const id of goal.fundingPolicy?.permittedPropertySaleIds??[])if(!properties.has(id)&&!intentProperties.has(id)&&!transferredProperties.has(id))errors.push(err('GOAL_PROPERTY_DANGLING',`${path}.fundingPolicy.permittedPropertySaleIds`,'Permitted sale property does not exist.','known property id',id,goal.id));goalDates(goal,path,errors);money(goal.target?.amountCents,`${path}.target.amountCents`,'GOAL_TARGET_INVALID',goal.id,errors);}
  for(const event of model.plannedEvents??[]){const path=`plannedEvents.${event.id}`;if(event.date!=null&&!isDate(event.date))errors.push(err('EVENT_DATE_INVALID',`${path}.date`,'Event date must be a valid ISO date.','YYYY-MM-DD',event.date,event.id));if(event.startDate||event.endDate)datePair(event.startDate,event.endDate,path,event.id,errors);if(event.personId&&!owners.has(event.personId))errors.push(err('EVENT_PERSON_DANGLING',`${path}.personId`,'Event person does not exist.','known person id',event.personId,event.id));if(event.goalId&&!goals.has(event.goalId))errors.push(err('EVENT_GOAL_DANGLING',`${path}.goalId`,'Event goal does not exist.','known goal id',event.goalId,event.id));if(strictReferences&&event.propertyId&&['property.convertToRentalIntent','property.saleIntent'].includes(event.type)&&!properties.has(event.propertyId)&&!intentProperties.has(event.propertyId)&&!transferredProperties.has(event.propertyId))errors.push(err('EVENT_PROPERTY_DANGLING',`${path}.propertyId`,'Event property does not exist.','known property id',event.propertyId,event.id));}
  for(const [id,record] of Object.entries(model.provenance??{}))provenance(id,record,errors,warnings);
  if(provenanceCompleteness)materialProvenance(model,warnings);
  const known=new Set(['schemaVersion','modelVersion','baseCurrencyYear','savedAt','household','people','assumptions','accounts','liabilities','assets','properties','propertyIntents','propertySimulation','goalSimulation','genericGoalSimulation','income','spending','spendingSchedules','spendingAdjustments','careers','retirementPolicies','plannedEvents','goals','policies','provenance','serviceHistories','extensions']);for(const key of Object.keys(model))if(!known.has(key))warnings.push(warn('UNKNOWN_FIELD_PRESERVED',key,'Unknown field will be preserved.'));
  return{valid:errors.length===0,errors,warnings};
}

function ownership(list,owners,path,id,errors){if(!Array.isArray(list)||!list.length){errors.push(err('OWNERSHIP_REQUIRED',`${path}.ownership`,'Ownership is required.','non-empty array',list,id));return;}let total=0;for(const [i,x] of list.entries()){if(!owners.has(x.ownerId))errors.push(err('OWNER_DANGLING',`${path}.ownership.${i}.ownerId`,'Owner does not exist.','known owner',x.ownerId,id));if(!Number.isFinite(x.share)||x.share<=0||x.share>1)errors.push(err('OWNERSHIP_SHARE_INVALID',`${path}.ownership.${i}.share`,'Ownership share must be greater than 0 and at most 1.','0 < share <= 1',x.share,id));total+=x.share??0;}if(Math.abs(total-1)>1e-9)errors.push(err('OWNERSHIP_TOTAL_INVALID',`${path}.ownership`,'Ownership shares must total 1.',1,total,id));}
function datePair(start,end,path,id,errors){if(start!=null&&!isDate(start))errors.push(err('START_DATE_INVALID',`${path}.startDate`,'Start date must be valid ISO.','YYYY-MM-DD',start,id));if(end!=null&&!isDate(end))errors.push(err('END_DATE_INVALID',`${path}.endDate`,'End date must be valid ISO.','YYYY-MM-DD',end,id));if(isDate(start)&&isDate(end)&&Date.parse(start)>Date.parse(end))errors.push(err('DATE_ORDER_INVALID',path,'Start date must not be after end date.','start <= end',`${start} > ${end}`,id));}
function goalDates(goal,path,errors){for(const [key,value] of [['earliestDesiredDate',goal.earliestDesiredDate],['latestAcceptableDate',goal.latestAcceptableDate],['preferredWindow.startDate',goal.preferredWindow?.startDate],['preferredWindow.endDate',goal.preferredWindow?.endDate]])if(value!=null&&!isDate(value))errors.push(err('GOAL_DATE_INVALID',`${path}.${key}`,'Goal date must be valid ISO.','YYYY-MM-DD',value,goal.id));if(isDate(goal.earliestDesiredDate)&&isDate(goal.latestAcceptableDate)&&Date.parse(goal.earliestDesiredDate)>Date.parse(goal.latestAcceptableDate))errors.push(err('GOAL_WINDOW_INVALID',path,'Earliest desired date must not exceed latest acceptable date.','earliest <= latest',`${goal.earliestDesiredDate} > ${goal.latestAcceptableDate}`,goal.id));const a=goal.preferredWindow?.startDate,b=goal.preferredWindow?.endDate;if(isDate(a)&&isDate(b)&&Date.parse(a)>Date.parse(b))errors.push(err('GOAL_PREFERRED_WINDOW_INVALID',`${path}.preferredWindow`,'Preferred start must not exceed end.','start <= end',`${a} > ${b}`,goal.id));}
function propertyTimeline(property,path,errors){const statuses=new Set(['planned','primaryResidence','rental','vacantTransition','pendingSale','sold','other']);if(property.status!=null&&!statuses.has(property.status))errors.push(err('PROPERTY_STATUS_INVALID',`${path}.status`,'Property status is unsupported.',[...statuses],property.status,property.id));if(property.acquisitionDate!=null&&!isDate(property.acquisitionDate))errors.push(err('ACQUISITION_DATE_INVALID',`${path}.acquisitionDate`,'Acquisition date must be valid ISO.','YYYY-MM-DD',property.acquisitionDate,property.id));const saleDate=property.realizedSaleDate??property.disposition?.realizedSaleDate;if(saleDate!=null&&!isDate(saleDate))errors.push(err('SALE_DATE_INVALID',`${path}.realizedSaleDate`,'Sale date must be valid ISO.','YYYY-MM-DD',saleDate,property.id));if(isDate(property.acquisitionDate)&&isDate(saleDate)&&Date.parse(saleDate)<Date.parse(property.acquisitionDate))errors.push(err('PROPERTY_DISPOSITION_ORDER_INVALID',path,'Sale cannot precede acquisition.',`sale >= ${property.acquisitionDate}`,saleDate,property.id));let previous=null;for(const [index,row] of (property.statusHistory??[]).entries()){if(!isDate(row.effectiveDate))errors.push(err('STATUS_DATE_INVALID',`${path}.statusHistory.${index}.effectiveDate`,'Status transition date must be valid ISO.','YYYY-MM-DD',row.effectiveDate,property.id));if(previous&&isDate(row.effectiveDate)&&Date.parse(row.effectiveDate)<Date.parse(previous.effectiveDate))errors.push(err('STATUS_HISTORY_ORDER_INVALID',`${path}.statusHistory.${index}`,'Status transitions must be chronological.',`>= ${previous.effectiveDate}`,row.effectiveDate,property.id));if(previous&&row.previousStatus!==previous.newStatus)errors.push(err('STATUS_TRANSITION_INVALID',`${path}.statusHistory.${index}.previousStatus`,'Status transition must continue from the prior state.',previous.newStatus,row.previousStatus,property.id));previous=row;}}
function money(value,path,code,id,errors){if(value!=null&&(!Number.isSafeInteger(value)||value<0))errors.push(err(code,path,'Value must be nonnegative integer cents.','>= 0 integer cents',value,id));}
function rate(value,path,id,errors,min,max){if(value!=null&&(!Number.isFinite(value)||value<min||value>max))errors.push(err('RATE_INVALID',path,`Rate must be a decimal from ${min} through ${max}.`,`${min}..${max}`,value,id));}
function provenance(id,record,errors,warnings){const path=`provenance.${id}`,kind=record?.classification;if(!ASSUMPTION_CLASSIFICATIONS.includes(kind)){errors.push(err('PROVENANCE_CLASSIFICATION_INVALID',`${path}.classification`,'Unsupported assumption classification.',ASSUMPTION_CLASSIFICATIONS,kind,id));return;}if(['official','researchedOfficial'].includes(kind)&&(!record.source?.url||String(record.source.url).startsWith('model://')||!record.sourceType||record.editable!==false))errors.push(err('OFFICIAL_PROVENANCE_INVALID',path,'Official values require a non-model source, source type, and editable=false.',undefined,record,id));if(kind==='projected'&&record.state==='official')errors.push(err('PROJECTED_LABELED_OFFICIAL',`${path}.state`,'Projected values cannot be labeled official.','projected',record.state,id));if(kind==='derived'&&!record.derivedFrom&&!record.ruleId)errors.push(err('DERIVATION_TRACE_REQUIRED',path,'Derived values require derivedFrom or ruleId.',undefined,record,id));if(!record.unit)warnings.push(warn('PROVENANCE_UNIT_MISSING',`${path}.unit`,'Material provenance record does not identify its unit.',undefined,record.unit,id));}
function materialProvenance(model,warnings){const registry=model.provenance??{};for(const entity of [...(model.accounts??[]),...(model.liabilities??[]),...(model.careers??[]),...(model.propertyIntents??[]),...(model.goals??[]),...(model.spendingSchedules??[])]){const ids=entity.provenanceIds??(entity.provenanceId?[entity.provenanceId]:[]);if(!ids.length&&entity.classification&&entity.classification!=='userEntered')warnings.push(warn('MATERIAL_PROVENANCE_INCOMPLETE',entity.id,'Material configured input has no provenance reference.',undefined,entity.classification,entity.id));for(const id of ids)if(!registry[id])warnings.push(warn('PROVENANCE_REFERENCE_MISSING',`${entity.id}.provenanceIds`,'Referenced provenance is not embedded in this model payload.',undefined,id,entity.id));}}

export function assessSimulationReadiness(model){
  const validation=validateModelDocument(model,{provenanceCompleteness:true,strictReferences:true}),missing=[],reference=(model.people??[]).find(x=>x.isReference&&x.enabled!==false);
  if(reference&&(reference.birthDate==null&&!Number.isInteger(reference.birthYear)))missing.push({code:'REFERENCE_BIRTH_REQUIRED',path:'people.reference.birthDate',message:'Reference birth date or birth year is required.'});
  for(const person of (model.people??[]).filter(x=>x.enabled!==false&&!x.isReference))if(person.birthDate==null&&!Number.isInteger(person.birthYear)&&!Number.isInteger(person.ageOffsetFromReference))missing.push({code:'PERSON_TIMING_REQUIRED',path:`people.${person.id}`,entityId:person.id,message:`Birth date, birth year, or age offset is required for enabled person ${person.name??person.id}.`});
  if(!Number.isInteger(model.household?.simulationStartYear))missing.push({code:'SIMULATION_START_REQUIRED',path:'household.simulationStartYear',message:'Simulation start year is required.'});
  if(!Number.isInteger(model.household?.simulationEndYear))missing.push({code:'SIMULATION_END_REQUIRED',path:'household.simulationEndYear',message:'Simulation end year is required.'});
  if(!model.household?.filingStatus)missing.push({code:'FILING_STATUS_REQUIRED',path:'household.filingStatus',message:'Initial filing status is required.'});
  for(const account of model.accounts??[])if(account.openingBalanceCents===null)missing.push({code:'STARTING_BALANCE_REQUIRED',path:`accounts.${account.id}.openingBalanceCents`,entityId:account.id,message:`Starting balance for ${account.name??account.id} is required, including zero.`});
  if(!(model.careers??[]).length)missing.push({code:'CAREER_TIMING_REQUIRED',path:'careers',message:'At least one career or income stage is required.'});
  const status=!validation.valid?'INVALID':missing.length?'INCOMPLETE_CONFIGURATION':validation.warnings.length?'READY_WITH_WARNINGS':'READY';return{status,ready:['READY','READY_WITH_WARNINGS'].includes(status),missing,errors:validation.errors,warnings:validation.warnings};
}
