export const SCHEMA_VERSION='2.0.0';
export const MODEL_VERSION='2.0.0-m4';

export function createModelDocument(input={}){
  const referenceBirthYear=input.people?.find(p=>p.isReference)?.birthYear??2007;
  return {schemaVersion:SCHEMA_VERSION,modelVersion:MODEL_VERSION,baseCurrencyYear:2025,savedAt:new Date(0).toISOString(),household:{id:'household',simulationStartYear:referenceBirthYear+18,simulationEndYear:referenceBirthYear+95,filingStatus:'single',...input.household},people:structuredClone(input.people??[{id:'reference',isReference:true,birthYear:referenceBirthYear}]),assumptions:structuredClone(input.assumptions??{}),accounts:structuredClone(input.accounts??[]),liabilities:structuredClone(input.liabilities??[]),assets:structuredClone(input.assets??[]),properties:structuredClone(input.properties??[]),propertyIntents:structuredClone(input.propertyIntents??[]),propertySimulation:structuredClone(input.propertySimulation??null),goalSimulation:structuredClone(input.goalSimulation??null),genericGoalSimulation:structuredClone(input.genericGoalSimulation??null),income:structuredClone(input.income??[]),spending:structuredClone(input.spending??[]),spendingSchedules:structuredClone(input.spendingSchedules??[]),spendingAdjustments:structuredClone(input.spendingAdjustments??[]),careers:structuredClone(input.careers??[]),retirementPolicies:structuredClone(input.retirementPolicies??{}),plannedEvents:structuredClone(input.plannedEvents??[]),goals:structuredClone(input.goals??[]),policies:structuredClone(input.policies??{}),provenance:structuredClone(input.provenance??{}),serviceHistories:structuredClone(input.serviceHistories??[]),extensions:structuredClone(input.extensions??{})};
}

export function validateModelDocument(model){
  const errors=[],warnings=[];
  if(model?.schemaVersion!==SCHEMA_VERSION)errors.push({code:'SCHEMA_VERSION_UNSUPPORTED',path:'schemaVersion',message:`Expected ${SCHEMA_VERSION}.`});
  if(!model?.modelVersion)errors.push({code:'MODEL_VERSION_REQUIRED',path:'modelVersion',message:'modelVersion is required.'});
  if(!Number.isInteger(model?.baseCurrencyYear))errors.push({code:'BASE_YEAR_INVALID',path:'baseCurrencyYear',message:'baseCurrencyYear must be an integer.'});
  if(!Array.isArray(model?.people)||!model.people.length)errors.push({code:'PEOPLE_REQUIRED',path:'people',message:'At least one person is required.'});
  for(const account of model?.accounts??[]){if(!account.id)errors.push({code:'ACCOUNT_ID_REQUIRED',path:'accounts',message:'Account id is required.'});if(!Number.isSafeInteger(account.openingBalanceCents))errors.push({code:'ACCOUNT_BALANCE_INVALID',path:`accounts.${account.id}`,message:'openingBalanceCents must be integer cents.'});}
  for(const property of model?.properties??[])try{validatePropertyOwnership(property.ownership);}catch(error){errors.push({code:'PROPERTY_OWNERSHIP_INVALID',path:`properties.${property.id}`,message:error.message});}
  for(const goal of model?.goals??[]){const allowed=['hard','protected','important','optional'];if(!goal.id)errors.push({code:'GOAL_ID_REQUIRED',path:'goals',message:'Goal id is required.'});if(!allowed.includes(goal.priority))errors.push({code:'GOAL_PRIORITY_INVALID',path:`goals.${goal.id}`,message:'Goal priority is invalid.'});if(!Array.isArray(goal.fundingPolicy?.permittedSources)||!goal.fundingPolicy.permittedSources.length)errors.push({code:'GOAL_FUNDING_POLICY_INVALID',path:`goals.${goal.id}`,message:'Goal permitted funding sources are required.'});if(goal.fundingPolicy?.permittedSources?.includes('retirement'))errors.push({code:'GOAL_RETIREMENT_PROTECTED',path:`goals.${goal.id}`,message:'Retirement funding is protected in V2.0.'});}
  const known=new Set(['schemaVersion','modelVersion','baseCurrencyYear','savedAt','household','people','assumptions','accounts','liabilities','assets','properties','propertyIntents','propertySimulation','goalSimulation','genericGoalSimulation','income','spending','spendingSchedules','spendingAdjustments','careers','retirementPolicies','plannedEvents','goals','policies','provenance','serviceHistories','extensions']);
  for(const key of Object.keys(model??{}))if(!known.has(key))warnings.push({code:'UNKNOWN_FIELD_PRESERVED',path:key,message:'Unknown field will be preserved.'});
  return {valid:errors.length===0,errors,warnings};
}

function validatePropertyOwnership(ownership){if(!Array.isArray(ownership)||!ownership.length)throw new TypeError('Ownership is required.');const total=ownership.reduce((s,o)=>s+o.share,0);if(ownership.some(o=>!o.ownerId||o.share<=0)||Math.abs(total-1)>1e-9)throw new TypeError('Ownership shares must total 1.');}
