import { createBaselineModel } from '../model/production-model.js';

// Fictional, self-contained production model. It does not import test data.
export function createExamplePlan(){
  const model=createBaselineModel(),ref=model.people[0],partner=model.people[1];
  model.extensions.presentation={examplePlan:true,label:'EXAMPLE PLAN'};
  model.household={...model.household,simulationStartYear:2026,simulationEndYear:2065,filingStatus:'single'};
  ref.name='Alex Morgan';ref.birthDate='2004-04-15';ref.inputState='entered';partner.enabled=true;partner.name='Jordan Morgan';partner.ageOffsetFromReference=-1;partner.inputState='entered';
  for(const account of model.accounts)account.openingBalanceCents=account.id==='general-cash'?2500000:account.id==='emergency-reserve'?1800000:account.id==='taxable-investments'?3500000:900000;
  model.accounts.push({id:'partner-retirement',name:'Partner retirement',ownerId:partner.id,type:'retirementInvestment',openingBalanceCents:400000,annualReturn:.06,protected:true});
  model.liabilities=[{id:'education-loan',name:'Education loan',ownerId:ref.id,type:'educationDebt',originalPrincipalCents:6500000,openingBalanceCents:6500000,annualRate:.055,scheduledPayments:Array.from({length:20},(_,i)=>({year:2026+i,amountCents:i<6?350000:1200000})),classification:'planningDefault',provenanceIds:['planning.futureInflation']}];
  model.careers=[
    {id:'law-school-work',personId:ref.id,careerType:'genericEmployment',role:'Law school / part-time work',startDate:'2026-01-01',endDate:'2029-06-30',compensationRule:{annualCents:3200000,baseYear:2026,annualGrowth:.02},classification:'planningDefault',provenanceIds:['planning.futureInflation']},
    {id:'jag-career',personId:ref.id,careerType:'military',role:'Air Force JAG',startDate:'2029-07-01',endDate:'2053-07-01',compensationRule:{locationKey:'UNSET',withDependents:false,bahFallback:{monthlyCents:240000,baseYear:2026,annualGrowth:.025,provenanceIds:['planning.futureInflation']},payGrowth:.025,allowanceGrowth:.025},classification:'planningDefault',provenanceIds:['planning.futureInflation']},
    {id:'pgy1',personId:partner.id,careerType:'physicianResidency',role:'PGY1',startDate:'2028-07-01',endDate:'2029-06-30',classification:'planningDefault',provenanceIds:['planning.futureInflation']},
    {id:'pgy2',personId:partner.id,careerType:'physicianResidency',role:'PGY2',startDate:'2029-07-01',endDate:'2030-06-30',classification:'planningDefault',provenanceIds:['planning.futureInflation']},
    {id:'pgy3',personId:partner.id,careerType:'physicianResidency',role:'PGY3',startDate:'2030-07-01',endDate:'2031-06-30',classification:'planningDefault',provenanceIds:['planning.futureInflation']},
    {id:'attending',personId:partner.id,careerType:'physicianAttending',role:'Attending pediatrician',startDate:'2031-07-01',endDate:'2065-01-01',compensationRule:{case:'baseline',baseYear:2031,annualGrowth:.025},classification:'planningDefault',provenanceIds:['planning.futureInflation']}
  ];
  model.serviceHistories=[{id:'air-force-service',personId:ref.id,periods:[{startDate:'2029-07-01',endDate:'2053-07-01'}],payGradeHistory:[{effectiveDate:'2029-07-01',grade:'O-2',expected:true},{effectiveDate:'2030-01-01',grade:'O-3',expected:true}],metadata:{initialServiceCommitmentYears:4}}];
  model.retirementPolicies={'jag-career':{accountId:'retirement-investments',traditionalRate:.08,rothRate:.02},attending:{accountId:'partner-retirement',employeeRate:.1,employerMatchRate:.04,taxTreatment:'traditional'}};
  model.spendingSchedules=[['housing',2400000,'essential'],['utilities',420000,'essential'],['food',900000,'essential'],['transportation',600000,'essential'],['insurance',500000,'essential'],['travel',500000,'discretionary'],['lifestyle',800000,'discretionary']].map(([category,amountCents,classification])=>({id:`spending-${category}`,ownerId:'household',category,classification,amountCents,valueBasis:'real',baseYear:2025,startYear:2026,endYear:2065,classificationOrigin:'planningDefault',provenanceIds:['planning.reserveMonths']}));
  model.plannedEvents=[{id:'combine',type:'household.combine',date:'2033-01-01',target:'household'},{id:'file-joint',type:'tax.filingStatus.change',date:'2034-01-01',target:'household',filingStatus:'marriedFilingJointly'}];
  model.propertyIntents=[{id:'duty-home-intent',propertyId:'duty-home',name:'Fictional duty-station home',desiredYear:2033,earliestAcceptableYear:2033,latestAcceptableYear:2036,enabled:true,propertyRole:'primaryResidence',locationKey:'EXAMPLE-LOCATION',ownership:[{ownerId:ref.id,share:.5},{ownerId:partner.id,share:.5}],expectedPriceCents:42000000,downPaymentCents:8400000,financedAmountCents:33600000,buyerClosingCostsCents:840000,initialSetupCostsCents:300000,initialPropertyReserveCents:1800000,propertyReserveMonths:6,mortgageId:'duty-home-mortgage',mortgageRate:.055,mortgageTermMonths:360,estimatedAnnualDebtServiceCents:2280000,minimumPostPurchaseFreeCashFlowCents:0,fundingPolicy:{sources:['generalCash'],allowTaxableInvestments:false},operations:{baseYear:2033,monthlyRentCents:310000,rentGrowthRate:.025,vacancyRate:.05,propertyTaxCents:500000,insuranceCents:180000,hoaCents:0,maintenanceRate:.01,capexRate:.005,managementRate:.08,primaryMaintenanceCents:350000},provenanceIds:['planning.futureInflation']}];
  model.plannedEvents.push({id:'example-pcs',type:'property.convertToRentalIntent',propertyId:'duty-home',date:'2040-07-01',title:'Fictional PCS rental evaluation',preferenceSensitive:false},{id:'expected-property-transfer',type:'asset.transfer.expected',date:'2044-01-01',title:'Fictional expected future property transfer',property:{id:'future-property',name:'Expected future property',estimatedValueCents:20000000,ownership:[{ownerId:ref.id,share:1}],initialStatus:'other',wealthRole:'personal-use',locationKey:'UNSET'}});
  model.goals=[{id:'long-term-home',name:'Fictional long-term home',type:'longTermHome',scope:'household',ownerIds:[ref.id,partner.id],enabled:true,earliestDesiredDate:'2048-01-01',preferredWindow:{startDate:'2048-01-01',endDate:'2065-12-31'},latestAcceptableDate:'2065-12-31',plannedTiming:{date:'2048-01-01'},target:{amountCents:150000000,basis:'real',baseYear:2025,inflationTreatment:'priceIndex'},priority:'important',priorityOrder:null,samePriorityPolicy:'proportional',fundingPolicy:{permittedSources:['generalCash','taxableInvestments'],allowTaxableInvestments:true,permittedAccountIds:['general-cash','taxable-investments'],permittedPropertySaleIds:['duty-home']},constraints:{housingBurdenDenominator:'afterTaxIncome',maxComfortHousingBurden:.27,minimumPossibleFreeCashFlowCents:0,minimumComfortFreeCashFlowCents:0,minimumDiscretionaryCapacityCents:0,minimumPostPurchaseLiquidityCents:5000000},home:{targetRole:'primaryResidence',locationKey:'TX-NORTH-DALLAS',downPaymentRate:.2,buyerClosingCostRate:.02,moveSetupCostsCents:2000000,moveSetupCostsBasis:'real',initialHomeReserveCents:2000000,initialHomeReserveMonths:0,mortgageRate:.055,mortgageTermMonths:360,propertyTaxRate:.018,insuranceRate:.005,maintenanceRate:.01,hoaAnnualCents:240000,otherAnnualCarryingCostsCents:0,resultingPropertyId:'long-term-home-property',ownership:[{ownerId:ref.id,share:.5},{ownerId:partner.id,share:.5}],existingPrimaryDispositionPlan:null},status:'planned',statusHistory:[],provenanceIds:['planning.futureInflation']}];
  model.assumptions={...model.assumptions,propertyAppreciationRate:.03,sellerTransactionCostRate:.06};
  model.extensions.integrated={autoExecuteGoals:true,openingPropertyLiabilities:{}};
  model.policies={...model.policies,reserveMonths:6,taxableInvestmentAnnualCents:1800000};
  return model;
}
